"""Closure adapter (STAGED PROPOSAL — not wired into the repo).

Derived from the ClosureMap in the sibling research document:
  2026-08-10-08-13-baml-chat-path-wiring.md

Behavior: a user's chat message on a configured endpoint produces a persisted
assistant message generated by that endpoint's provider.
Pin: b46393b39265cf4dabe2cf1c81e56c001ef358ae

This file is a proposal only. It is deliberately placed beside the research
document rather than under any source tree so no build picks it up. Promote it
into /home/maceo/Dev/silmari-chat and complete each TODO(promote) before use.

Speaks the 7-op contract apps/closure-oracle already talks to (mock_adapter.py).
"""

import http.server
import json
import sys

ASYNC_EDGES = ["model-instantiation->persisted-message"]
CONNECTOR = {e: True for e in ASYNC_EDGES}
SINK = []


def handle(op, p):
    if op == "/reset":
        SINK.clear()
        CONNECTOR.update({e: True for e in ASYNC_EDGES})
        return {"ok": True}

    if op == "/set_connector":
        CONNECTOR[p["edge"]] = p["enabled"]
        return {"ok": True}

    if op == "/seed_sink":
        SINK.append(p["value"])
        return {"ok": True}

    if op == "/seed":
        # TODO(promote): seed AppConfig.endpoints with p["data"]
        #   loadEndpoints — packages/data-schemas/src/app/endpoints.ts:81-93
        return {"ok": True}

    if op == "/trigger":
        # TODO(promote): drive the mounted chat route with p["args"]
        #   buildEndpointOption — api/server/middleware/buildEndpointOption.js:28-39
        #   agents.buildOptions  — api/server/services/Endpoints/agents/build.js:9-20
        return {"ok": True}

    if op == "/drive":
        if not CONNECTOR.get(p["edge"], True):
            return {"ok": True}  # oracle disabled this edge = red-at-seam
        # TODO(promote): drain the terminal job for p["edge"]
        #   finishTerminalJob — packages/api/src/stream/GenerationJobManager.ts:3308-3313
        return {"ok": True}

    if op == "/observe":
        # TODO(promote): return json.dumps(getMessages(conversationId))
        #   persistence is performed by the default handlers —
        #   api/server/controllers/agents/callbacks.js:408,438,474,499,515,589,598
        return {"ok": True, "value": json.dumps(SINK)}

    return {"ok": False, "error": "unknown op"}


class Hn(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        out = json.dumps(handle(self.path, json.loads(self.rfile.read(n) or "{}"))).encode()
        self.send_response(200)
        self.send_header("Content-Length", str(len(out)))
        self.end_headers()
        self.wfile.write(out)

    def log_message(self, *a):
        pass


http.server.HTTPServer(("127.0.0.1", int(sys.argv[1])), Hn).serve_forever()
