/**
 * Canonical action identifiers for admin audit log entries.
 * Keys and values are kept identical so consumers can use either
 * form interchangeably.
 */
export const AdminAuditActions = {
  USER_LIST: 'USER_LIST',
  USER_VIEW: 'USER_VIEW',
  USER_BAN: 'USER_BAN',
  USER_UNBAN: 'USER_UNBAN',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_DELETE: 'USER_DELETE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_INVITE: 'USER_INVITE',
  USER_IMPERSONATE_ISSUED: 'USER_IMPERSONATE_ISSUED',
  USER_IMPERSONATE_CONSUMED: 'USER_IMPERSONATE_CONSUMED',

  SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
  SUBSCRIPTION_GRANT: 'SUBSCRIPTION_GRANT',
  SUBSCRIPTION_REVOKE: 'SUBSCRIPTION_REVOKE',
  SUBSCRIPTION_CLEAR_OVERRIDE: 'SUBSCRIPTION_CLEAR_OVERRIDE',
  SUBSCRIPTION_REFRESH: 'SUBSCRIPTION_REFRESH',

  BALANCE_VIEW: 'BALANCE_VIEW',
  BALANCE_ADJUST: 'BALANCE_ADJUST',
  BALANCE_SET: 'BALANCE_SET',

  USAGE_VIEW: 'USAGE_VIEW',
  MESSAGES_VIEW_LIST: 'MESSAGES_VIEW_LIST',
  MESSAGES_VIEW_CONTENT: 'MESSAGES_VIEW_CONTENT',
  CONVERSATION_VIEW: 'CONVERSATION_VIEW',

  TRANSACTION_VIEW: 'TRANSACTION_VIEW',

  AUDIT_VIEW: 'AUDIT_VIEW',
} as const;

export type AdminAuditAction = (typeof AdminAuditActions)[keyof typeof AdminAuditActions];
