{{- if .Values.librechat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librechat.fullname" $ }}-config
data:
  librechat.yaml: |
{{ .Values.librechat.configYamlContent | nindent 4 }}

{{- end }}
