apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librechat.fullname" . }}
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "librechat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librechat.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.initContainers }}
      # Init containers are specialized containers that run before app containers in a Pod.
      # They can contain utilities or setup scripts not present in an app image.
      # For more info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librechat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "librechat.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{ if .Values.config.envSecrets.secretRef }}
            - secretRef:
                name: {{ .Values.config.envSecrets.secretRef }}
            {{- end }}
            - configMapRef:
                name: {{ include "librechat.fullname" . }}-env
          env:
            {{- range $secretKeyRef := .Values.config.envSecrets.secretKeyRef }}
            - name: {{ $secretKeyRef.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretKeyRef.secretName }}
                  key: {{ $secretKeyRef.secretKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/librechat.yaml
              subPath: config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
