# Custom values for LibreChat Helm chart
# This file contains the customizations needed to deploy our fork to Kubernetes

replicaCount: 1

image:
  repository: registry.totalsoft.local/librechat-custom
  tag: latest
  pullPolicy: Always

# Image pull secrets configuration
# This will be populated from the command line, but you can also set it manually here
imagePullSecrets: []
# - name: regcred

# Disable persistence as it's not being used currently
persistence:
  enabled: false

volumes:
  - name: librechat-config
    configMap:
      name: librechat-config

volumeMounts:
  - name: librechat-config
    mountPath: /app/librechat.yaml
    subPath: librechat.yaml

# Environment variables structure moved under config.env as expected by the Helm chart
config:
  env:
    NODE_ENV: "production"
    # Connection to existing MongoDB instance
    MONGO_URI: "f"
    # Encryption keys for sensitive data
    CREDS_KEY: "f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0"
    CREDS_IV: "e2341419ec3dd3d19b13a1a87fafcbfb"
    # JWT Authentication
    JWT_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"
    JWT_REFRESH_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"
    # Session
    SESSION_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"
    ENDPOINTS: "azureOpenAI"
    # API keys (will be moved to secrets in a future phase)
    AZURE_OPENAI_API_KEY: "z"
    AZURE_OPENAI_INSTANCE: "r"
    
# Resources configuration
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: false #error if set to true with the api version, needs to be fixed in the main branch
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Custom ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: librechat.totalsoft.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: totalsoft-wildcard-tls
      hosts:
        - librechat.totalsoft.local

# MongoDB configuration - DISABLED (using external MongoDB)
mongodb:
  enabled: false
  # No other MongoDB settings needed since we're using an external instance

# Vector database configuration - Disabled since no persistence is being used
vectordb:
  enabled: false

# Search service configuration - Disabled since no persistence is being used
meilisearch:
  enabled: false

# RAG API configuration - Disabled since vectordb is disabled
rag_api:
  enabled: false

# Node selector configuration 
nodeSelector:
  kubernetes.io/os: linux
  # Add any additional node selectors specific to your environment
  # example:
  # custom-label: value 
