# Custom values for LibreChat Helm chart
# This file contains the customizations needed to deploy our fork to Kubernetes
# 
# To deploy with certificates from custom/cert folder:
# helm upgrade --install librechat ./charts/librechat -f custom/config/k8s/custom-values.yaml --include-dir custom

replicaCount: 1

image:
  repository: registry.totalsoft.local/librechat-custom
  tag: latest
  pullPolicy: Always

# Image pull secrets configuration
# This will be populated from the command line, but you can also set it manually here
imagePullSecrets: []
# - name: regcred

# TLS certificate secret configuration
tlsSecret:
  enabled: true
  name: "totalsoft-wildcard-tls"
  # Path to certificate files (relative to the chart directory)
  certFile: "../../custom/cert/wildcard-totalsoft.crt"
  keyFile: "../../custom/cert/wildcard-totalsoft.key"
  # Alternative: Base64-encoded certificate and key data
  # You can generate these values with:
  # cat wildcard-totalsoft.crt | base64 -w 0
  # cat wildcard-totalsoft.key | base64 -w 0
  # cert: "" # Add your base64-encoded certificate here
  # key: "" # Add your base64-encoded private key here

# Enable custom file storage using PVC
persistence:
  enabled: true
  storageClass: "smb"  # Use your cluster's storage class
  size: 10Gi
  
  # Mount points for custom data
  customMounts:
    - name: custom-data
      mountPath: /app/custom/data
      subPath: data
    - name: custom-images
      mountPath: /app/client/public/images
      subPath: images
    - name: custom-logs
      mountPath: /app/api/logs
      subPath: logs
    - name: custom-uploads
      mountPath: /app/uploads
      subPath: uploads

# Environment variables structure moved under config.env as expected by the Helm chart
config:
  env:
    NODE_ENV: "production"
    # Connection to existing MongoDB instance
    MONGO_URI: "mongodb://mongodb:ch%40r1sm%40@10.1.48.99:27017"
    # Encryption keys for sensitive data
    CREDS_KEY: "f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0"
    CREDS_IV: "e2341419ec3dd3d19b13a1a87fafcbfb"
    # JWT Authentication
    JWT_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"
    JWT_REFRESH_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"
    # Session
    SESSION_SECRET: "09d57da76cb0e2870e1db59e564a71e3e8b956fdbd2907874a62ff58516868558f5f0fb18285690cede8b7705e3d7274650a6a"

# Resources configuration
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: false #error if set to true with the api version, needs to be fixed in the main branch
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Custom ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: librechat.totalsoft.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: totalsoft-wildcard-tls
      hosts:
        - librechat.totalsoft.local

# MongoDB configuration - DISABLED (using external MongoDB)
mongodb:
  enabled: false
  # No other MongoDB settings needed since we're using an external instance

# Vector database configuration
vectordb:
  enabled: true
  image:
    repository: ankane/pgvector
    tag: latest
  env:
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "replace-with-secure-password"
  persistence:
    enabled: true
    storageClass: "smb"
    size: 5Gi

# Search service configuration
meilisearch:
  enabled: true
  environment:
    MEILI_NO_ANALYTICS: "true"
  masterKey: "replace-with-secure-key"
  persistence:
    enabled: true
    storageClass: "smb"
    size: 5Gi

# RAG API configuration
rag_api:
  enabled: true
  image:
    repository: ghcr.io/danny-avila/librechat-rag-api-dev-lite
    tag: latest
  env:
    DB_HOST: "vectordb"

# Node selector configuration 
nodeSelector:
  kubernetes.io/os: linux
  # Add any additional node selectors specific to your environment
  # example:
  # custom-label: value 