replicaCount: 1

image:
  repository: registry.totalsoft.local/librechat-custom
  tag: latest
  pullPolicy: Always

# This will be populated from the command line, but you can also set it manually here
imagePullSecrets: []
# - name: regcred

persistence:
  enabled: false

volumes:
  - name: librechat-config
    configMap:
      name: librechat-config

volumeMounts:
  - name: librechat-config
    mountPath: /app/librechat.yaml
    subPath: librechat.yaml

config:
  envSecrets:
    secretRef: librechat-secrets

  env:
    NODE_ENV: "production"
    ALLOW_PASSWORD_RESET: "true"
    SEARCH: "true"
    
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false #error if set to true with the api version, needs to be fixed in the main branch
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: librechat.totalsoft.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: totalsoft-wildcard-tls
      hosts:
        - librechat.totalsoft.local

mongodb:
  enabled: false

vectordb:
  enabled: false

meilisearch:
  enabled: false

rag_api:
  enabled: false

nodeSelector:
  kubernetes.io/os: linux