spec:
  inputs:
    app_name: "librechat-svt"
---
include:
  - project: 'aurora/pipelines/includes'
    ref: v1
    file: '/image.yml'

stages:
  - build
  - test
  - post build dev
  - post build app
  - deploy

"build docker $[[ inputs.app_name ]]":
  stage: build
  tags:
    - k8s
  extends:
    - .buildkit_build_image
  variables:
    IMAGE: "${AURORA_HARBOR_URI}/llm/$[[ inputs.app_name ]]:$CI_COMMIT_SHORT_SHA"
    BUILDKIT_EXTRA_ARGS: --opt build-arg:version=$CI_COMMIT_SHORT_SHA

"release image STAGE $[[ inputs.app_name ]]":
  stage: deploy
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  tags:
    - k8s
  when: manual
  needs:
    - "build docker $[[ inputs.app_name ]]"
  script:
    - echo "$AURORA_HARBOR_PASS" | crane auth login -u "$AURORA_HARBOR_USER" --password-stdin "$AURORA_HARBOR_URI"
    - >
      crane tag
      "$DOCKER_IMAGE":"$CI_COMMIT_SHORT_SHA"
      "dev-$CI_COMMIT_SHORT_SHA-$(date +%s)"
  variables:
    DOCKER_IMAGE: "${AURORA_HARBOR_URI}/llm/$[[ inputs.app_name ]]"

"release image PROD $[[ inputs.app_name ]]":
  stage: deploy
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  tags:
    - k8s
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        paths:
          - $[[ inputs.directory ]]/**/*
          - CI/**/*
      when: manual
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        paths:
          - $[[ inputs.directory ]]/**/*
          - CI/**/*
      when: never
  needs:
    - "build docker $[[ inputs.app_name ]]"
  script:
    - echo "$AURORA_HARBOR_PASS" | crane auth login -u "$AURORA_HARBOR_USER" --password-stdin "$AURORA_HARBOR_URI"
    - >
      crane tag
      "$DOCKER_IMAGE":"$CI_COMMIT_SHORT_SHA"
      "prod-$CI_COMMIT_SHORT_SHA-$(date +%s)"
  variables:
    DOCKER_IMAGE: "${AURORA_HARBOR_URI}/llm/$[[ inputs.app_name ]]"
