services:
  api:
    container_name: LibreChat
    image: ghcr.io/<DEIN_GITHUB_USER_ODER_ORG>/librechat-custom:latest
    # build: .   <-- RAUS
    ports:
      - '${PORT:-3080}:${PORT:-3080}'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - HOST=0.0.0.0
      - 'MONGO_URI=mongodb://mongodb:27017/LibreChat'
      - 'MEILI_HOST=http://meilisearch:7700'
      - RAG_PORT=8000
      - 'RAG_API_URL=http://rag_api:8000'
      - DEFAULT_THEME=dark
    volumes:
      - 'librechat-images:/app/client/public/images'
      - 'librechat-uploads:/app/uploads'
      - 'librechat-logs:/app/logs'
      - './librechat.yaml:/app/librechat.yaml:ro'
