services:
  mongodb:
    container_name: librechat-mongodb-local
    image: mongo:8.2.2
    ports:
      - "27017:27017"
    volumes:
      - librechat-db-data:/data/db
    command: mongod --noauth

  # meilisearch:
  #   container_name: librechat-meilisearch
  #   image: getmeili/meilisearch:v1.26.0
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_HOST=${MEILI_HOST}
  #     - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
  #     - MEILI_NO_ANALYTICS=true
  #   volumes:
  #     - librechat-meilisearch-data:/meili_data

  # vectordb:
  #   container_name: vectordb
  #   image: pgvector/pgvector:0.8.0-pg15-trixie
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_HOST_AUTH_METHOD: md5
  #   restart: always
  #   volumes:
  #     - pgdata2:/var/lib/postgresql/data

  # rag_api:
  #   container_name: rag_api
  #   image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_HOST=vectordb
  #     - RAG_PORT=${RAG_PORT:-8000}
  #   restart: always
  #   depends_on:
  #     - vectordb
  #   env_file:
  #     - .env
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  # redis:
  #   container_name: librechat-redis
  #   image: redis:8.6.1-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - librechat-redis-data:/data

volumes:
  librechat-db-data:
    name: librechat-db-data

  # librechat-meilisearch-data:
  #   name: librechat-meilisearch-data

  # pgdata2:
  
  # librechat-redis-data:
  #   name: librechat-redis-data
