/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// baml-cli is available with the baml package.

import { defineFunction } from "@boundaryml/baml-bridge";
import type * as baml from "../baml/index.js";

export class Envelope$stream {
  tool!: string | null;
  constructor(init: {
    tool: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Envelope {
  tool!: string;
  constructor(init: {
    tool: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectDynTool = defineFunction("user.toolloop.SelectDynTool", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Envelope;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectDynTool_async = defineFunction("user.toolloop.SelectDynTool", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<Envelope>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$build_request = defineFunction("user.toolloop.SelectDynTool$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$build_request_async = defineFunction("user.toolloop.SelectDynTool$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$build_request_stream = defineFunction("user.toolloop.SelectDynTool$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$build_request_stream_async = defineFunction("user.toolloop.SelectDynTool$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws ParseError
 */
export const SelectDynTool$parse = defineFunction("user.toolloop.SelectDynTool$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Envelope;

/**
 * @throws ParseError
 */
export const SelectDynTool$parse_async = defineFunction("user.toolloop.SelectDynTool$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<Envelope>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectDynTool$parse_stream = defineFunction("user.toolloop.SelectDynTool$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<Envelope$stream | null, Envelope>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectDynTool$parse_stream_async = defineFunction("user.toolloop.SelectDynTool$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<Envelope$stream | null, Envelope>>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$render_prompt = defineFunction("user.toolloop.SelectDynTool$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectDynTool$render_prompt_async = defineFunction("user.toolloop.SelectDynTool$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectDynTool$stream = defineFunction("user.toolloop.SelectDynTool$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<Envelope$stream | null, Envelope>;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectDynTool$stream_async = defineFunction("user.toolloop.SelectDynTool$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<Envelope$stream | null, Envelope>>;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const EscapeProbe = defineFunction("user.toolloop.EscapeProbe", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const EscapeProbe_async = defineFunction("user.toolloop.EscapeProbe", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$build_request = defineFunction("user.toolloop.EscapeProbe$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$build_request_async = defineFunction("user.toolloop.EscapeProbe$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$build_request_stream = defineFunction("user.toolloop.EscapeProbe$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$build_request_stream_async = defineFunction("user.toolloop.EscapeProbe$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws ParseError
 */
export const EscapeProbe$parse = defineFunction("user.toolloop.EscapeProbe$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * @throws ParseError
 */
export const EscapeProbe$parse_async = defineFunction("user.toolloop.EscapeProbe$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const EscapeProbe$parse_stream = defineFunction("user.toolloop.EscapeProbe$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const EscapeProbe$parse_stream_async = defineFunction("user.toolloop.EscapeProbe$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$render_prompt = defineFunction("user.toolloop.EscapeProbe$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const EscapeProbe$render_prompt_async = defineFunction("user.toolloop.EscapeProbe$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const EscapeProbe$stream = defineFunction("user.toolloop.EscapeProbe$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const EscapeProbe$stream_async = defineFunction("user.toolloop.EscapeProbe$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * Streaming selection against the local capture server.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const StreamTools = defineFunction("user.toolloop.StreamTools", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => (GetWeather | WebSearch | RunCode)[];

/**
 * Streaming selection against the local capture server.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const StreamTools_async = defineFunction("user.toolloop.StreamTools", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<(GetWeather | WebSearch | RunCode)[]>;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$build_request = defineFunction("user.toolloop.StreamTools$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$build_request_async = defineFunction("user.toolloop.StreamTools$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$build_request_stream = defineFunction("user.toolloop.StreamTools$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$build_request_stream_async = defineFunction("user.toolloop.StreamTools$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Streaming selection against the local capture server.
 * @throws ParseError
 */
export const StreamTools$parse = defineFunction("user.toolloop.StreamTools$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => (GetWeather | WebSearch | RunCode)[];

/**
 * Streaming selection against the local capture server.
 * @throws ParseError
 */
export const StreamTools$parse_async = defineFunction("user.toolloop.StreamTools$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<(GetWeather | WebSearch | RunCode)[]>;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const StreamTools$parse_stream = defineFunction("user.toolloop.StreamTools$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const StreamTools$parse_stream_async = defineFunction("user.toolloop.StreamTools$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>>;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$render_prompt = defineFunction("user.toolloop.StreamTools$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * Streaming selection against the local capture server.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const StreamTools$render_prompt_async = defineFunction("user.toolloop.StreamTools$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * Streaming selection against the local capture server.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const StreamTools$stream = defineFunction("user.toolloop.StreamTools$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>;

/**
 * Streaming selection against the local capture server.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const StreamTools$stream_async = defineFunction("user.toolloop.StreamTools$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolGeneric = defineFunction("user.toolloop.SelectToolGeneric", "sync", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => T;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolGeneric_async = defineFunction("user.toolloop.SelectToolGeneric", "async", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<T>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$build_request = defineFunction("user.toolloop.SelectToolGeneric$build_request", "sync", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$build_request_async = defineFunction("user.toolloop.SelectToolGeneric$build_request", "async", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$build_request_stream = defineFunction("user.toolloop.SelectToolGeneric$build_request_stream", "sync", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$build_request_stream_async = defineFunction("user.toolloop.SelectToolGeneric$build_request_stream", "async", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws ParseError
 */
export const SelectToolGeneric$parse = defineFunction("user.toolloop.SelectToolGeneric$parse", "sync", ["json"], ["client"], { typeParams: ["T"] }) as <T>(json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => T;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws ParseError
 */
export const SelectToolGeneric$parse_async = defineFunction("user.toolloop.SelectToolGeneric$parse", "async", ["json"], ["client"], { typeParams: ["T"] }) as <T>(json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<T>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectToolGeneric$parse_stream = defineFunction("user.toolloop.SelectToolGeneric$parse_stream", "sync", ["sse"], ["client"], { typeParams: ["T"] }) as <T>(sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<T | null, T>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectToolGeneric$parse_stream_async = defineFunction("user.toolloop.SelectToolGeneric$parse_stream", "async", ["sse"], ["client"], { typeParams: ["T"] }) as <T>(sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<T | null, T>>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$render_prompt = defineFunction("user.toolloop.SelectToolGeneric$render_prompt", "sync", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolGeneric$render_prompt_async = defineFunction("user.toolloop.SelectToolGeneric$render_prompt", "async", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolGeneric$stream = defineFunction("user.toolloop.SelectToolGeneric$stream", "sync", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<T | null, T>;

/**
 * v1 runtime type binding: the return type is a GENERIC parameter, so the host
 * supplies the concrete type (including a UNION built at runtime) via `$types`.
 * This is the seam that replaces v0's TypeBuilder.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolGeneric$stream_async = defineFunction("user.toolloop.SelectToolGeneric$stream", "async", ["user_message"], ["client"], { typeParams: ["T"] }) as <T>(user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<T | null, T>>;

/**
 * The single renderer for prior tool turns. `Answer` interpolates THIS
 * function, so what the offline tests assert is the exact text the model sees
 * — the test and the production prompt cannot drift apart.
 */
export const render_transcript = defineFunction("user.toolloop.render_transcript", "sync", ["turns"]) as (turns: ToolTurn[]) => string;

/**
 * The single renderer for prior tool turns. `Answer` interpolates THIS
 * function, so what the offline tests assert is the exact text the model sees
 * — the test and the production prompt cannot drift apart.
 */
export const render_transcript_async = defineFunction("user.toolloop.render_transcript", "async", ["turns"]) as (turns: ToolTurn[]) => Promise<string>;

/**
 * TURN 1 — model selects a tool.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTool = defineFunction("user.toolloop.SelectTool", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => ToolInvocation;

/**
 * TURN 1 — model selects a tool.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTool_async = defineFunction("user.toolloop.SelectTool", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<ToolInvocation>;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$build_request = defineFunction("user.toolloop.SelectTool$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$build_request_async = defineFunction("user.toolloop.SelectTool$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$build_request_stream = defineFunction("user.toolloop.SelectTool$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$build_request_stream_async = defineFunction("user.toolloop.SelectTool$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 1 — model selects a tool.
 * @throws ParseError
 */
export const SelectTool$parse = defineFunction("user.toolloop.SelectTool$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => ToolInvocation;

/**
 * TURN 1 — model selects a tool.
 * @throws ParseError
 */
export const SelectTool$parse_async = defineFunction("user.toolloop.SelectTool$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<ToolInvocation>;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectTool$parse_stream = defineFunction("user.toolloop.SelectTool$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<ToolInvocation$stream | null, ToolInvocation>;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectTool$parse_stream_async = defineFunction("user.toolloop.SelectTool$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<ToolInvocation$stream | null, ToolInvocation>>;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$render_prompt = defineFunction("user.toolloop.SelectTool$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * TURN 1 — model selects a tool.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTool$render_prompt_async = defineFunction("user.toolloop.SelectTool$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * TURN 1 — model selects a tool.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTool$stream = defineFunction("user.toolloop.SelectTool$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<ToolInvocation$stream | null, ToolInvocation>;

/**
 * TURN 1 — model selects a tool.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTool$stream_async = defineFunction("user.toolloop.SelectTool$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<ToolInvocation$stream | null, ToolInvocation>>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const Answer = defineFunction("user.toolloop.Answer", "sync", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const Answer_async = defineFunction("user.toolloop.Answer", "async", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$build_request = defineFunction("user.toolloop.Answer$build_request", "sync", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$build_request_async = defineFunction("user.toolloop.Answer$build_request", "async", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$build_request_stream = defineFunction("user.toolloop.Answer$build_request_stream", "sync", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$build_request_stream_async = defineFunction("user.toolloop.Answer$build_request_stream", "async", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws ParseError
 */
export const Answer$parse = defineFunction("user.toolloop.Answer$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws ParseError
 */
export const Answer$parse_async = defineFunction("user.toolloop.Answer$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const Answer$parse_stream = defineFunction("user.toolloop.Answer$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const Answer$parse_stream_async = defineFunction("user.toolloop.Answer$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$render_prompt = defineFunction("user.toolloop.Answer$render_prompt", "sync", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const Answer$render_prompt_async = defineFunction("user.toolloop.Answer$render_prompt", "async", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const Answer$stream = defineFunction("user.toolloop.Answer$stream", "sync", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * TURN 2 — the tool result is fed back in and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const Answer$stream_async = defineFunction("user.toolloop.Answer$stream", "async", ["user_message", "turns"], ["client"]) as (user_message: string, turns: ToolTurn[], $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * One full turn-1 -> execute -> turn-2 cycle, with turn 1 supplied as a canned
 * model output so the whole loop runs offline with no API key.
 * @throws InvalidArgument
 * @throws ParseError
 */
export const loop_offline = defineFunction("user.toolloop.loop_offline", "sync", ["user_message", "turn1_model_output"]) as (user_message: string, turn1_model_output: string) => string;

/**
 * One full turn-1 -> execute -> turn-2 cycle, with turn 1 supplied as a canned
 * model output so the whole loop runs offline with no API key.
 * @throws InvalidArgument
 * @throws ParseError
 */
export const loop_offline_async = defineFunction("user.toolloop.loop_offline", "async", ["user_message", "turn1_model_output"]) as (user_message: string, turn1_model_output: string) => Promise<string>;

/**
 * Same cycle against a live model. Needs OPENAI_API_KEY; not run by `baml test`.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const loop_live = defineFunction("user.toolloop.loop_live", "sync", ["user_message"]) as (user_message: string) => string;

/**
 * Same cycle against a live model. Needs OPENAI_API_KEY; not run by `baml test`.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const loop_live_async = defineFunction("user.toolloop.loop_live", "async", ["user_message"]) as (user_message: string) => Promise<string>;

/**
 * Bridge-safe transcript renderer. A JS host cannot hand BAML a `ToolTurn[]`
 * (arrays of class instances lower to maps — see B3), so the host-driven path
 * passes parallel primitive arrays instead. Same output as `render_transcript`.
 */
export const render_transcript_flat = defineFunction("user.toolloop.render_transcript_flat", "sync", ["names", "args", "results"]) as (names: string[], args: string[], results: string[]) => string;

/**
 * Bridge-safe transcript renderer. A JS host cannot hand BAML a `ToolTurn[]`
 * (arrays of class instances lower to maps — see B3), so the host-driven path
 * passes parallel primitive arrays instead. Same output as `render_transcript`.
 */
export const render_transcript_flat_async = defineFunction("user.toolloop.render_transcript_flat", "async", ["names", "args", "results"]) as (names: string[], args: string[], results: string[]) => Promise<string>;

/**
 * One pending call. Built internally so the spawn closure captures a FRESH
 * binding per element — see the while-loop footgun noted on `execute_tools`.
 */
export class ToolCallReq$stream {
  tool_name!: string | null;
  args_json!: string | null;
  constructor(init: {
    tool_name: string | null;
    args_json: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailed$stream {
  tool_name!: string | null;
  message!: string | null;
  constructor(init: {
    tool_name: string | null;
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolOutcome$stream {
  tool_name!: string | null;
  result_json!: string | null;
  failed!: boolean | null;
  constructor(init: {
    tool_name: string | null;
    result_json: string | null;
    failed: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One pending call. Built internally so the spawn closure captures a FRESH
 * binding per element — see the while-loop footgun noted on `execute_tools`.
 */
export class ToolCallReq {
  tool_name!: string;
  args_json!: string;
  constructor(init: {
    tool_name: string;
    args_json: string;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailed {
  tool_name!: string;
  message!: string;
  constructor(init: {
    tool_name: string;
    message: string;
  }) {
    Object.assign(this, init);
  }
}

export class ToolOutcome {
  tool_name!: string;
  result_json!: string;
  failed!: boolean;
  constructor(init: {
    tool_name: string;
    result_json: string;
    failed: boolean;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Stand-in for host tool execution. Odd-length args simulate a failure so the
 * per-call catch arm is actually exercised.
 * @throws ToolFailed
 */
export const run_one_tool = defineFunction("user.toolloop.run_one_tool", "sync", ["name", "args_json"]) as (name: string, args_json: string) => string;

/**
 * Stand-in for host tool execution. Odd-length args simulate a failure so the
 * per-call catch arm is actually exercised.
 * @throws ToolFailed
 */
export const run_one_tool_async = defineFunction("user.toolloop.run_one_tool", "async", ["name", "args_json"]) as (name: string, args_json: string) => Promise<string>;

/**
 * Execute a whole turn's tool calls with at most `max_in_flight` running.
 * Extras queue FIFO inside the group.
 */
export const execute_tools = defineFunction("user.toolloop.execute_tools", "sync", ["names", "args", "max_in_flight"]) as (names: string[], args: string[], max_in_flight: number) => ToolOutcome[];

/**
 * Execute a whole turn's tool calls with at most `max_in_flight` running.
 * Extras queue FIFO inside the group.
 */
export const execute_tools_async = defineFunction("user.toolloop.execute_tools", "async", ["names", "args", "max_in_flight"]) as (names: string[], args: string[], max_in_flight: number) => Promise<ToolOutcome[]>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolBareUnion = defineFunction("user.toolloop.SelectToolBareUnion", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => WeatherAPI | SearchAPI;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolBareUnion_async = defineFunction("user.toolloop.SelectToolBareUnion", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<WeatherAPI | SearchAPI>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$build_request = defineFunction("user.toolloop.SelectToolBareUnion$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$build_request_async = defineFunction("user.toolloop.SelectToolBareUnion$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$build_request_stream = defineFunction("user.toolloop.SelectToolBareUnion$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$build_request_stream_async = defineFunction("user.toolloop.SelectToolBareUnion$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws ParseError
 */
export const SelectToolBareUnion$parse = defineFunction("user.toolloop.SelectToolBareUnion$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => WeatherAPI | SearchAPI;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws ParseError
 */
export const SelectToolBareUnion$parse_async = defineFunction("user.toolloop.SelectToolBareUnion$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<WeatherAPI | SearchAPI>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectToolBareUnion$parse_stream = defineFunction("user.toolloop.SelectToolBareUnion$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<WeatherAPI$stream | SearchAPI$stream | null, WeatherAPI | SearchAPI>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectToolBareUnion$parse_stream_async = defineFunction("user.toolloop.SelectToolBareUnion$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<WeatherAPI$stream | SearchAPI$stream | null, WeatherAPI | SearchAPI>>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$render_prompt = defineFunction("user.toolloop.SelectToolBareUnion$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectToolBareUnion$render_prompt_async = defineFunction("user.toolloop.SelectToolBareUnion$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolBareUnion$stream = defineFunction("user.toolloop.SelectToolBareUnion$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<WeatherAPI$stream | SearchAPI$stream | null, WeatherAPI | SearchAPI>;

/**
 * Bare-union control. Exists only so a test can pin the `$parse` limitation.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectToolBareUnion$stream_async = defineFunction("user.toolloop.SelectToolBareUnion$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<WeatherAPI$stream | SearchAPI$stream | null, WeatherAPI | SearchAPI>>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectWeatherOnly = defineFunction("user.toolloop.SelectWeatherOnly", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => WeatherAPI;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectWeatherOnly_async = defineFunction("user.toolloop.SelectWeatherOnly", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<WeatherAPI>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$build_request = defineFunction("user.toolloop.SelectWeatherOnly$build_request", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$build_request_async = defineFunction("user.toolloop.SelectWeatherOnly$build_request", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$build_request_stream = defineFunction("user.toolloop.SelectWeatherOnly$build_request_stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$build_request_stream_async = defineFunction("user.toolloop.SelectWeatherOnly$build_request_stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws ParseError
 */
export const SelectWeatherOnly$parse = defineFunction("user.toolloop.SelectWeatherOnly$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => WeatherAPI;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws ParseError
 */
export const SelectWeatherOnly$parse_async = defineFunction("user.toolloop.SelectWeatherOnly$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<WeatherAPI>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectWeatherOnly$parse_stream = defineFunction("user.toolloop.SelectWeatherOnly$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<WeatherAPI$stream | null, WeatherAPI>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectWeatherOnly$parse_stream_async = defineFunction("user.toolloop.SelectWeatherOnly$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<WeatherAPI$stream | null, WeatherAPI>>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$render_prompt = defineFunction("user.toolloop.SelectWeatherOnly$render_prompt", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectWeatherOnly$render_prompt_async = defineFunction("user.toolloop.SelectWeatherOnly$render_prompt", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectWeatherOnly$stream = defineFunction("user.toolloop.SelectWeatherOnly$stream", "sync", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<WeatherAPI$stream | null, WeatherAPI>;

/**
 * Single-class control — the `$parse` path that DOES work offline.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectWeatherOnly$stream_async = defineFunction("user.toolloop.SelectWeatherOnly$stream", "async", ["user_message"], ["client"]) as (user_message: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<WeatherAPI$stream | null, WeatherAPI>>;

export const TURN1_WEATHER = defineFunction("user.toolloop.TURN1_WEATHER", "sync", []) as () => string;

export const TURN1_WEATHER_async = defineFunction("user.toolloop.TURN1_WEATHER", "async", []) as () => Promise<string>;

export const TURN1_SEARCH = defineFunction("user.toolloop.TURN1_SEARCH", "sync", []) as () => string;

export const TURN1_SEARCH_async = defineFunction("user.toolloop.TURN1_SEARCH", "async", []) as () => Promise<string>;

export class GetWeather$stream {
  tool!: "get_weather";
  city!: string | null;
  constructor(init: {
    tool: "get_weather";
    city: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class RunCode$stream {
  tool!: "run_code";
  language!: "python" | "typescript";
  source!: string | null;
  constructor(init: {
    tool: "run_code";
    language: "python" | "typescript";
    source: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class WebSearch$stream {
  tool!: "web_search";
  query!: string | null;
  constructor(init: {
    tool: "web_search";
    query: string | null;
  }) {
    Object.assign(this, init);
  }
}

export type BoundTool$stream = GetWeather$stream | WebSearch$stream | RunCode$stream;

export class GetWeather {
  tool!: "get_weather";
  city!: string;
  constructor(init: {
    tool: "get_weather";
    city: string;
  }) {
    Object.assign(this, init);
  }
}

export class WebSearch {
  tool!: "web_search";
  query!: string;
  constructor(init: {
    tool: "web_search";
    query: string;
  }) {
    Object.assign(this, init);
  }
}

export class RunCode {
  tool!: "run_code";
  language!: "python" | "typescript";
  source!: string;
  constructor(init: {
    tool: "run_code";
    language: "python" | "typescript";
    source: string;
  }) {
    Object.assign(this, init);
  }
}

export type BoundTool = GetWeather | WebSearch | RunCode;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTools = defineFunction("user.toolloop.SelectTools", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => (GetWeather | WebSearch | RunCode)[];

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTools_async = defineFunction("user.toolloop.SelectTools", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<(GetWeather | WebSearch | RunCode)[]>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$build_request = defineFunction("user.toolloop.SelectTools$build_request", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$build_request_async = defineFunction("user.toolloop.SelectTools$build_request", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$build_request_stream = defineFunction("user.toolloop.SelectTools$build_request_stream", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$build_request_stream_async = defineFunction("user.toolloop.SelectTools$build_request_stream", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws ParseError
 */
export const SelectTools$parse = defineFunction("user.toolloop.SelectTools$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => (GetWeather | WebSearch | RunCode)[];

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws ParseError
 */
export const SelectTools$parse_async = defineFunction("user.toolloop.SelectTools$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<(GetWeather | WebSearch | RunCode)[]>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectTools$parse_stream = defineFunction("user.toolloop.SelectTools$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const SelectTools$parse_stream_async = defineFunction("user.toolloop.SelectTools$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$render_prompt = defineFunction("user.toolloop.SelectTools$render_prompt", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const SelectTools$render_prompt_async = defineFunction("user.toolloop.SelectTools$render_prompt", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTools$stream = defineFunction("user.toolloop.SelectTools$stream", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>;

/**
 * TURN 1 — selection. The return type is STATIC, so `${ctx.output_format}`
 * renders normally and `$build_request` does not hit the type-var panic.
 * A list-of-union gives parallel tool calls.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const SelectTools$stream_async = defineFunction("user.toolloop.SelectTools$stream", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<(GetWeather$stream | WebSearch$stream | RunCode$stream)[], (GetWeather | WebSearch | RunCode)[]>>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const AnswerWithTools = defineFunction("user.toolloop.AnswerWithTools", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const AnswerWithTools_async = defineFunction("user.toolloop.AnswerWithTools", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$build_request = defineFunction("user.toolloop.AnswerWithTools$build_request", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$build_request_async = defineFunction("user.toolloop.AnswerWithTools$build_request", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$build_request_stream = defineFunction("user.toolloop.AnswerWithTools$build_request_stream", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.http.Request;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$build_request_stream_async = defineFunction("user.toolloop.AnswerWithTools$build_request_stream", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws ParseError
 */
export const AnswerWithTools$parse = defineFunction("user.toolloop.AnswerWithTools$parse", "sync", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => string;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws ParseError
 */
export const AnswerWithTools$parse_async = defineFunction("user.toolloop.AnswerWithTools$parse", "async", ["json"], ["client"]) as (json: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<string>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const AnswerWithTools$parse_stream = defineFunction("user.toolloop.AnswerWithTools$parse_stream", "sync", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 */
export const AnswerWithTools$parse_stream_async = defineFunction("user.toolloop.AnswerWithTools$parse_stream", "async", ["sse"], ["client"]) as (sse: baml.http.SseStream, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$render_prompt = defineFunction("user.toolloop.AnswerWithTools$render_prompt", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.PromptAst;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws InvalidArgument
 * @throws LlmClient
 * @throws RenderPrompt
 */
export const AnswerWithTools$render_prompt_async = defineFunction("user.toolloop.AnswerWithTools$render_prompt", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.PromptAst>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const AnswerWithTools$stream = defineFunction("user.toolloop.AnswerWithTools$stream", "sync", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => baml.llm.Stream<string | null, string>;

/**
 * TURN 2 — the tool results are fed back and the model answers.
 * @throws DevOther
 * @throws InvalidArgument
 * @throws Io
 * @throws LlmClient
 * @throws RenderPrompt
 * @throws Timeout
 */
export const AnswerWithTools$stream_async = defineFunction("user.toolloop.AnswerWithTools$stream", "async", ["user_message", "transcript"], ["client"]) as (user_message: string, transcript: string, $opts?: { client?: baml.llm.Client | undefined } | undefined) => Promise<baml.llm.Stream<string | null, string>>;

/**
 * BAML-INTERNAL ONLY. Do not call from a TypeScript host: a host value arrives
 * as a map, and a union-typed parameter cannot discriminate a map — it coerces
 * into the FIRST variant and throws `Missing field ... in external Instance`.
 * From the host, read the literal `tool` field directly (see provider-pattern.mjs).
 */
export const tool_of = defineFunction("user.toolloop.tool_of", "sync", ["call"]) as (call: GetWeather | WebSearch | RunCode) => string;

/**
 * BAML-INTERNAL ONLY. Do not call from a TypeScript host: a host value arrives
 * as a map, and a union-typed parameter cannot discriminate a map — it coerces
 * into the FIRST variant and throws `Missing field ... in external Instance`.
 * From the host, read the literal `tool` field directly (see provider-pattern.mjs).
 */
export const tool_of_async = defineFunction("user.toolloop.tool_of", "async", ["call"]) as (call: GetWeather | WebSearch | RunCode) => Promise<string>;

/**
 * Bridge-safe transcript: parallel primitive arrays, never an array of
 * instances (which lowers to maps and panics — see bridge-loop.mjs B3).
 */
export const build_transcript = defineFunction("user.toolloop.build_transcript", "sync", ["names", "args", "results"]) as (names: string[], args: string[], results: string[]) => string;

/**
 * Bridge-safe transcript: parallel primitive arrays, never an array of
 * instances (which lowers to maps and panics — see bridge-loop.mjs B3).
 */
export const build_transcript_async = defineFunction("user.toolloop.build_transcript", "async", ["names", "args", "results"]) as (names: string[], args: string[], results: string[]) => Promise<string>;

export class SearchAPI$stream {
  query!: string | null;
  constructor(init: {
    query: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Discriminated wrapper. A bare union return cannot be `$parse`d offline
 * ("Unions must be flattened"), so the loop selects through this instead.
 */
export class ToolInvocation$stream {
  tool!: "weather" | "search";
  weather!: WeatherAPI$stream | null;
  search!: SearchAPI$stream | null;
  constructor(init: {
    tool: "weather" | "search";
    weather: WeatherAPI$stream | null;
    search: SearchAPI$stream | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolTurn$stream {
  tool_name!: string | null;
  arguments_json!: string | null;
  result_json!: string | null;
  constructor(init: {
    tool_name: string | null;
    arguments_json: string | null;
    result_json: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class WeatherAPI$stream {
  city!: string | null;
  time_of_day!: string | null;
  constructor(init: {
    city: string | null;
    time_of_day: string | null;
  }) {
    Object.assign(this, init);
  }
}

export type ToolCall$stream = WeatherAPI$stream | SearchAPI$stream;

export class WeatherAPI {
  city!: string;
  time_of_day!: string;
  constructor(init: {
    city: string;
    time_of_day: string;
  }) {
    Object.assign(this, init);
  }
}

export class SearchAPI {
  query!: string;
  constructor(init: {
    query: string;
  }) {
    Object.assign(this, init);
  }
}

export type ToolCall = WeatherAPI | SearchAPI;

/**
 * Discriminated wrapper. A bare union return cannot be `$parse`d offline
 * ("Unions must be flattened"), so the loop selects through this instead.
 */
export class ToolInvocation {
  tool!: "weather" | "search";
  weather!: WeatherAPI | null;
  search!: SearchAPI | null;
  constructor(init: {
    tool: "weather" | "search";
    weather: WeatherAPI | null;
    search: SearchAPI | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolTurn {
  tool_name!: string;
  arguments_json!: string;
  result_json!: string;
  constructor(init: {
    tool_name: string;
    arguments_json: string;
    result_json: string;
  }) {
    Object.assign(this, init);
  }
}

export const tool_name = defineFunction("user.toolloop.tool_name", "sync", ["call"]) as (call: WeatherAPI | SearchAPI) => string;

export const tool_name_async = defineFunction("user.toolloop.tool_name", "async", ["call"]) as (call: WeatherAPI | SearchAPI) => Promise<string>;

export const tool_arguments_json = defineFunction("user.toolloop.tool_arguments_json", "sync", ["call"]) as (call: WeatherAPI | SearchAPI) => string;

export const tool_arguments_json_async = defineFunction("user.toolloop.tool_arguments_json", "async", ["call"]) as (call: WeatherAPI | SearchAPI) => Promise<string>;

/**
 * Host-side tool execution stand-in. Takes a class INSTANCE back as a
 * parameter — the in-BAML half of the C18 round-trip question.
 */
export const execute_tool = defineFunction("user.toolloop.execute_tool", "sync", ["call"]) as (call: WeatherAPI | SearchAPI) => string;

/**
 * Host-side tool execution stand-in. Takes a class INSTANCE back as a
 * parameter — the in-BAML half of the C18 round-trip question.
 */
export const execute_tool_async = defineFunction("user.toolloop.execute_tool", "async", ["call"]) as (call: WeatherAPI | SearchAPI) => Promise<string>;

/**
 * Narrow the wrapper back to the union so the rest of the loop is typed.
 * @throws InvalidArgument
 */
export const invocation_to_call = defineFunction("user.toolloop.invocation_to_call", "sync", ["inv"]) as (inv: ToolInvocation) => WeatherAPI | SearchAPI;

/**
 * Narrow the wrapper back to the union so the rest of the loop is typed.
 * @throws InvalidArgument
 */
export const invocation_to_call_async = defineFunction("user.toolloop.invocation_to_call", "async", ["inv"]) as (inv: ToolInvocation) => Promise<WeatherAPI | SearchAPI>;
