# DNS Configuration Examples for LibreChat Helm Chart
# This file demonstrates how to configure custom DNS settings for traffic redirection

# Example 1: Redirect AWS Bedrock traffic to a proxy server
dnsPolicy: "None"  # Ignore cluster DNS, use only custom DNS
dnsConfig:
  nameservers:
    - "10.0.0.10"  # Your custom DNS server that handles redirections
    - "8.8.8.8"    # Fallback to Google DNS for other domains
  searches:
    - "svc.cluster.local"
    - "cluster.local"
  options:
    - name: ndots
      value: "2"

---

# Example 2: Use corporate DNS server
dnsPolicy: "None"
dnsConfig:
  nameservers:
    - "192.168.1.53"  # Corporate DNS server
    - "192.168.1.54"  # Backup DNS server

---

# Example 3: Combine with hostAliases for simple redirects
dnsPolicy: "ClusterFirst"  # Use cluster DNS first
dnsConfig:
  options:
    - name: timeout
      value: "1"
    - name: attempts
      value: "2"

# Note: For simple host-to-IP mappings, you can also use hostAliases
# in combination with DNS configuration (add this to deployment spec):
# hostAliases:
#   - ip: "10.100.50.200"
#     hostnames:
#       - "bedrock-runtime.us-east-1.amazonaws.com"
#       - "api.openai.com"