import { cleanCodeToolOutput } from './cleanup';

/**
 * Real bash_tool outputs captured from a deployed conversation. Patterns
 * tested live: trailing single `Note:` paragraph, double trailing
 * `Note:` paragraphs, per-file `| <annotation>` suffixes (downloaded /
 * displayed / known-as-input), and inline-comma file lists.
 */
describe('cleanCodeToolOutput', () => {
  it('returns empty/falsy input unchanged', () => {
    expect(cleanCodeToolOutput('')).toBe('');
  });

  it('strips a trailing single `Note:` paragraph (mkdir-only output)', () => {
    const input = [
      'stdout:',
      'Folder created successfully!',
      '',
      'Generated files:',
      '- /mnt/data/test_folder/.dirkeep',
      '',
      '',
      'Note: Files from previous executions are automatically available and can be modified.',
    ].join('\n');
    const output = cleanCodeToolOutput(input);
    expect(output).not.toMatch(/Note:/);
    expect(output).toMatch(/Folder created successfully!/);
    expect(output).toMatch(/Generated files:/);
    expect(output).toMatch(/- \/mnt\/data\/test_folder\/\.dirkeep$/);
  });

  it('strips both trailing `Note:` paragraphs when two are emitted', () => {
    const input = [
      'stdout:',
      'File created successfully!',
      '',
      'Generated files:',
      '- /mnt/data/test_folder/test_file.txt',
      'Available files (inputs, not generated by this execution):',
      '- /mnt/data/test_folder/.dirkeep',
      '',
      '',
      'Note: Files from previous executions are automatically available and can be modified.',
      '',
      'Note: Files in "Available files" are inputs the user (or a skill) already provided to the sandbox. They were not produced by this execution and you should not present them as new outputs in your response.',
    ].join('\n');
    const output = cleanCodeToolOutput(input);
    expect(output).not.toMatch(/Note:/);
    expect(output).toMatch(/Generated files:/);
    expect(output).toMatch(/Available files \(inputs/);
  });

  it('strips per-file "downloaded" / "known to the user" / "displayed" annotations', () => {
    const input = [
      'Generated files:',
      '- /mnt/data/a.txt | File is already downloaded by the user',
      '- /mnt/data/b.png | Image is already displayed to the user',
      'Available files (inputs, not generated by this execution):',
      '- /mnt/data/c.txt | Available as an input — already known to the user',
    ].join('\n');
    const output = cleanCodeToolOutput(input);
    expect(output).not.toMatch(/already downloaded/);
    expect(output).not.toMatch(/already displayed/);
    expect(output).not.toMatch(/already known to the user/);
    expect(output).toMatch(/- \/mnt\/data\/a\.txt$/m);
    expect(output).toMatch(/- \/mnt\/data\/b\.png$/m);
    expect(output).toMatch(/- \/mnt\/data\/c\.txt$/m);
  });

  it('handles inline comma-separated file lists (small file count formatting)', () => {
    // The bash executor inlines the list with `, ` when ≤ 3 files.
    const input =
      'Available files (inputs, not generated by this execution):\n- /mnt/data/test_folder/test_file.txt | Available as an input — already known to the user, - /mnt/data/test_folder/.dirkeep | Available as an input — already known to the user';
    const output = cleanCodeToolOutput(input);
    expect(output).not.toMatch(/already known to the user/);
    expect(output).toMatch(/- \/mnt\/data\/test_folder\/test_file\.txt/);
    expect(output).toMatch(/- \/mnt\/data\/test_folder\/\.dirkeep/);
  });

  it('passes through output that contains no boilerplate (no false positives)', () => {
    const input = 'stdout:\nHello, world!\n';
    expect(cleanCodeToolOutput(input)).toBe('stdout:\nHello, world!');
  });

  it('does not strip the word "Note:" mid-output (only trailing paragraphs)', () => {
    // A user-authored echo `Note: this is real content` mid-output should
    // not be eaten by the trailing-Notes regex; only paragraphs that
    // start with `Note:` AFTER a blank line near end-of-string are matched.
    const input = [
      'stdout:',
      'Note: this is real content',
      'more output',
      '',
      'Generated files:',
      '- /mnt/data/foo.txt',
    ].join('\n');
    const output = cleanCodeToolOutput(input);
    expect(output).toMatch(/Note: this is real content/);
  });

  it('drops trailing blank lines after stripping', () => {
    const input =
      'stdout:\nresult\n\n\nNote: Files from previous executions are automatically available and can be modified.';
    expect(cleanCodeToolOutput(input)).toBe('stdout:\nresult');
  });
});
