// Generated repository-owned Responses prompts. Do not edit this file directly.

// BEGIN GENERATED RESPONSE PROMPTS
// Generated by scripts/generate_response_prompts.py; edit Atticus-Back-End/prompts/responses instead.
import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { logger } from '@librechat/data-schemas';

export const RESPONSE_PROMPTS_BY_APP_ID = {
  "1": { id: "juristai_app_1_federal_criminal", version: "3", key: "prompts/responses/federal-criminal.txt" },
  "2": { id: "juristai_app_2_civil_legal_operations", version: "3", key: "prompts/responses/civil-legal-operations.txt" },
  "3": { id: "juristai_app_3_seriesai_deal_lawyers", version: "1", key: "prompts/responses/seriesai-deal-lawyers.txt" },
  "4": { id: "juristai_app_4_seriesai_founders_employees", version: "1", key: "prompts/responses/seriesai-founders-employees.txt" },
  "5": { id: "juristai_app_5_in_house_account_manager", version: "1", key: "prompts/responses/in-house-account-manager.txt" },
} as const;

const responsePromptS3 = new S3Client({});

export async function resolveResponseAppInstructions(
  appId: string | number | undefined,
): Promise<string> {
  const appPrompt = RESPONSE_PROMPTS_BY_APP_ID[String(appId ?? '').trim() as keyof typeof RESPONSE_PROMPTS_BY_APP_ID];
  if (!appPrompt) return '';
  const bucket = process.env.PROMPTS_BUCKET?.trim() || 'juristai-system-prompts';
  try {
    const response = await responsePromptS3.send(new GetObjectCommand({ Bucket: bucket, Key: appPrompt.key }));
    const instructions = await response.Body?.transformToString('utf-8');
    if (!instructions?.trim()) throw new Error(`Empty Responses prompt in s3://${bucket}/${appPrompt.key}`);
    logger.info('responses_prompt_loaded', { appId: String(appId), promptId: appPrompt.id, key: appPrompt.key, versionId: response.VersionId });
    return instructions.trim();
  } catch (error) {
    logger.error('responses_prompt_unavailable', { appId: String(appId), promptId: appPrompt.id, key: appPrompt.key, error: (error as Error)?.message });
    throw error;
  }
}
// END GENERATED RESPONSE PROMPTS
