# PersistentVolumeClaim (PVC): Requests storage from the cluster
# This ensures data persists even if pods are deleted/restarted
---
# MongoDB data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: librechat
spec:
  storageClassName: manual
  volumeName: mongodb-pv
  accessModes:
    - ReadWriteOnce  # Can be mounted by single node at a time
  resources:
    requests:
      storage: 10Gi  # Request 10GB for MongoDB data

---
# Meilisearch data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: librechat
spec:
  storageClassName: manual
  volumeName: meilisearch-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 5GB for search index

---
# Vector database storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-data
  namespace: librechat
spec:
  storageClassName: manual
  volumeName: vectordb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 5GB for vector embeddings

---
# LibreChat uploads and logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-uploads
  namespace: librechat
spec:
  storageClassName: manual
  volumeName: librechat-uploads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 10GB for user uploads and logs
