import { useCallback, useEffect, useMemo, useRef } from 'react';
import { v4 } from 'uuid';
import { useToastContext } from '@librechat/client';
import { useRecoilValue, useSetRecoilState, useRecoilCallback } from 'recoil';
import {
  Constants,
  ContentTypes,
  isAgentsEndpoint,
  isAssistantsEndpoint,
} from 'librechat-data-provider';
import type {
  TAgentQueuedTurnFileRef,
  TMessage,
  TConversation,
  TMessageContentParts,
} from 'librechat-data-provider';
import type {
  RunEnd,
  PendingSteer,
  QueuedMessage,
  QueuedMessageOrigin,
  SettledQueuedTurnReceipt,
} from '~/store/families';
import type { AgentQueuedTurnReceipt, GenerationProtocolVersion } from '~/data-provider';
import type { ExtendedFile, FileSetter } from '~/common';
import {
  useCancelSteerMutation,
  useSteerMessageMutation,
  useMarkFilesUsageMutation,
  useAgentQueuedTurns,
  useCancelAgentQueuedTurnMutation,
  useEnqueueAgentQueuedTurnMutation,
  isDefiniteQueuedTurnRejection,
  isDefiniteQueuedTurnsUnsupported,
  supportsGenerationProtocolV2,
} from '~/data-provider';
import {
  appendAppliedSteerIds,
  carriedSteerContext,
  clearAllDrafts,
  getPendingDraftId,
  insertQueuedOrigin,
  mergeRestagedQuotes,
} from '~/utils';
import useSteerConvert from '~/hooks/Chat/useSteerConvert';
import { useLatestMessage } from '~/hooks/Messages';
import { useSetFilesToDelete } from '~/hooks/Files';
import useLocalize from '~/hooks/useLocalize';
import store from '~/store';

/** During-run submit routes: inject into the live run, or queue for after it. */
export type DuringRunAction = 'steer' | 'queue';

/** Composer state consumed into a queued item alongside the text. */
export interface QueuedMessageContext {
  quotes?: string[];
  manualSkills?: string[];
  clientRequestId?: string;
  recoverySteerId?: string;
  expectedPredecessorCreatedAt?: number;
  queuedMessageOrigin?: QueuedMessageOrigin;
}

/** Server-side cap on a usage touch (mirrors `FILES_USAGE_MAX_IDS`). */
const QUEUE_USAGE_MAX_FILES = 10;
/** Bound transport-outcome reconciliation while still guaranteeing several
 * list reads after the enqueue promise settles. Focus/remount remains a later
 * reconciliation path for exceptionally slow intermediaries. */
const QUEUED_TURN_RECONCILIATION_MS = 60_000;

type SteerErrorCode =
  | 'NO_ACTIVE_RUN'
  | 'RUN_PAUSED'
  | 'RUN_REPLACED'
  | 'STEER_QUEUE_FULL'
  | 'STEER_UNSUPPORTED'
  | string;

type SubmitSteerOptions = {
  preempt?: boolean;
  queuedOrigin?: QueuedMessageOrigin;
  /** Stable across transport retries so the server can dedupe a committed POST. */
  clientSteerId?: string;
  /** Preserve the generation identity on retries instead of targeting a newer
   * turn that may now occupy the same conversation-scoped stream id. */
  generationCreatedAt?: number;
  /** Same-id retries retain the original submission timestamp so a receipt
   * replay cannot reorder this steer behind a later queued follow-up. */
  createdAt?: number;
  /** Interpret a retry receipt using the source generation's negotiated
   * protocol, not whichever replacement generation is currently active. */
  generationProtocolVersion?: GenerationProtocolVersion;
};

function getSteerErrorCode(error: unknown): SteerErrorCode | undefined {
  const response = (error as { response?: { data?: { code?: string } } } | undefined)?.response;
  return response?.data?.code;
}

function isDefiniteSteerRejection(error: unknown): boolean {
  const status = (error as { response?: { status?: number } } | undefined)?.response?.status;
  return (
    status != null &&
    status >= 400 &&
    status < 500 &&
    // These statuses can be generated by an intermediary while the origin
    // request continues; keep their delivery outcome explicitly uncertain.
    status !== 408 &&
    status !== 425
  );
}

function isSameRunEpoch(a: RunEnd | null, b: RunEnd): boolean {
  if (a == null || a.conversationId !== b.conversationId) {
    return false;
  }
  if (a.generationCreatedAt != null || b.generationCreatedAt != null) {
    return a.generationCreatedAt === b.generationCreatedAt;
  }
  return a.endedAt === b.endedAt;
}

/** True when the latest assistant message carries an unresolved tool approval —
 *  the run is (or is about to be) paused, so a steer POST would 409. */
function hasLiveToolApproval(message: TMessage | null): boolean {
  if (message?.isCreatedByUser !== false) {
    return false;
  }
  const content = message.content;
  if (!Array.isArray(content)) {
    return false;
  }
  return content.some((part: TMessageContentParts | undefined) => {
    if (part?.type !== ContentTypes.TOOL_CALL) {
      return false;
    }
    const toolCall = part[ContentTypes.TOOL_CALL] as
      | { approval?: unknown; output?: string | null }
      | undefined;
    return toolCall?.approval != null && (toolCall.output?.length ?? 0) === 0;
  });
}

interface LiveMessageState {
  approval: boolean;
  parentMessageId?: string;
}

function selectLiveMessageState(message: TMessage | null): LiveMessageState {
  const parentMessageId =
    message?.isCreatedByUser === false && typeof message.messageId === 'string'
      ? message.messageId
      : undefined;
  return { approval: hasLiveToolApproval(message), parentMessageId };
}

function compareQueuedMessages(a: QueuedMessage, b: QueuedMessage): number {
  const priority = Number(b.priority ?? false) - Number(a.priority ?? false);
  if (priority !== 0) {
    return priority;
  }
  const aServerOrder = a.server?.revision;
  const bServerOrder = b.server?.revision;
  if (aServerOrder != null && bServerOrder != null && aServerOrder !== bServerOrder) {
    return aServerOrder - bServerOrder;
  }
  if (a.server != null && b.server == null) {
    return -1;
  }
  if (a.server == null && b.server != null) {
    return 1;
  }
  return a.createdAt - b.createdAt;
}

function queuedTurnCreatedAt(receipt: AgentQueuedTurnReceipt): number {
  const createdAt = Date.parse(receipt.createdAt);
  return Number.isFinite(createdAt) ? createdAt : 0;
}

function toQueuedTurnFileRefs(files: TMessage['files']): TAgentQueuedTurnFileRef[] | undefined {
  const refs = (files ?? []).flatMap((file): TAgentQueuedTurnFileRef[] => {
    if (typeof file.file_id !== 'string' || file.file_id.length === 0) {
      return [];
    }
    return [
      {
        file_id: file.file_id,
        ...(file.type != null && { type: file.type }),
        ...(file.filepath != null && { filepath: file.filepath }),
        ...(file.filename != null && { filename: file.filename }),
        ...(file.height != null && { height: file.height }),
        ...(file.width != null && { width: file.width }),
        ...(file.bytes != null && { bytes: file.bytes }),
      },
    ];
  });
  return refs.length > 0 ? refs : undefined;
}

function reconcileServerQueuedTurns(
  previous: QueuedMessage[],
  receipts: AgentQueuedTurnReceipt[],
  settledByRequestId: ReadonlyMap<string, SettledQueuedTurnReceipt>,
  authoritativeSnapshot = true,
): QueuedMessage[] {
  const previousByClientRequestId = new Map(
    previous.flatMap((item) =>
      item.clientRequestId != null ? [[item.clientRequestId, item] as const] : [],
    ),
  );
  const observedClientRequestIds = new Set(receipts.map((receipt) => receipt.clientRequestId));
  const projected = receipts.flatMap((receipt): QueuedMessage[] => {
    const settled = settledByRequestId.get(receipt.clientRequestId);
    if (settled?.status === 'admitted' || settled?.status === 'cancelled') {
      return [];
    }
    const optimistic = previousByClientRequestId.get(receipt.clientRequestId);
    if (
      (settled?.status === 'dead' || settled?.status === 'admitted_pending_boundary') &&
      receipt.status !== 'dead' &&
      receipt.status !== 'admitted'
    ) {
      return optimistic == null ? [] : [optimistic];
    }
    const boundaryPending = receipt.status === 'admitted';
    let status: NonNullable<QueuedMessage['server']>['status'] = 'rejected';
    if (boundaryPending) {
      status = 'uncertain';
    } else if (receipt.status === 'queued' || receipt.status === 'claimed') {
      status = receipt.status;
    }
    return [
      {
        id: optimistic?.id ?? receipt.clientRequestId,
        text: receipt.text,
        createdAt: queuedTurnCreatedAt(receipt),
        clientRequestId: receipt.clientRequestId,
        parentMessageId: receipt.parentMessageId,
        ...(receipt.expectedPredecessorCreatedAt != null && {
          expectedPredecessorCreatedAt: receipt.expectedPredecessorCreatedAt,
        }),
        ...(receipt.files != null && receipt.files.length > 0 && { files: receipt.files }),
        ...(receipt.quotes != null && receipt.quotes.length > 0 && { quotes: receipt.quotes }),
        ...(receipt.manualSkills != null &&
          receipt.manualSkills.length > 0 && {
            manualSkills: receipt.manualSkills,
          }),
        ...(receipt.priority === true && { priority: true }),
        server: {
          id: receipt.queuedTurnId,
          status,
          revision: receipt.revision,
          ...(boundaryPending && {
            uncertainSince: optimistic?.server?.uncertainSince ?? Date.now(),
          }),
          ...(receipt.position != null && { position: receipt.position }),
          ...(receipt.failure?.code != null && { errorCode: receipt.failure.code }),
          ...(receipt.failure?.message != null && { errorMessage: receipt.failure.message }),
        },
      },
    ];
  });
  const retained = previous.filter((item) => {
    if (item.server == null) {
      return true;
    }
    const settled =
      item.clientRequestId == null ? undefined : settledByRequestId.get(item.clientRequestId);
    if (settled?.status === 'admitted' || settled?.status === 'cancelled') {
      return false;
    }
    if (settled?.status === 'dead' || settled?.status === 'admitted_pending_boundary') {
      return item.clientRequestId == null || !observedClientRequestIds.has(item.clientRequestId);
    }
    if (item.clientRequestId == null || observedClientRequestIds.has(item.clientRequestId)) {
      return false;
    }
    if (!authoritativeSnapshot) {
      return true;
    }
    return (
      item.server.status === 'sending' ||
      item.server.status === 'uncertain' ||
      item.server.status === 'rejected'
    );
  });
  return [...retained, ...projected].sort(compareQueuedMessages);
}

export interface UseSteeringParams {
  index: number;
  conversationId: string;
  conversation: TConversation | null;
  isSubmitting: boolean;
  answerModeActive: boolean;
  /** Composer attachments — consumed into queued items (steering is text-only). */
  files?: Map<string, ExtendedFile>;
  setFiles?: FileSetter;
  /** Uploads still in flight: during-run submits are held like the send button. */
  filesLoading?: boolean;
  /** Submits text (and optional attachments/quotes/skills) as a normal new
   *  turn. Overrides are always explicit — a queued item is the FULL
   *  submission context, so absent fields must send as empty, never vacuum
   *  the composer. Returns `false` when `ask` refused without sending
   *  (in-flight guard, history not cached yet) so callers can restore
   *  instead of dropping. */
  sendNow: (
    text: string,
    files?: TMessage['files'],
    context?: QueuedMessageContext,
  ) => false | void;
  /** Stops the current generation (used by interrupt & send). */
  stopGenerating: () => void;
}

/**
 * The composer's during-run brain: decides what Enter does while a run is
 * generating (steer vs queue, per the user preference and run state), owns the
 * pending-steer / queued-message chip state, and implements the three actions
 * — steer (POST + optimistic chip), queue (client-side), and interrupt & send
 * (abort, then auto-send via the one-shot drain override).
 */
export default function useSteering({
  index,
  conversationId,
  conversation,
  isSubmitting,
  answerModeActive,
  files,
  setFiles,
  filesLoading = false,
  sendNow,
  stopGenerating,
}: UseSteeringParams) {
  const localize = useLocalize();
  const { showToast } = useToastContext();
  const setFilesToDelete = useSetFilesToDelete();
  const convertSteersToQueued = useSteerConvert();
  /** `mutate` is a stable callback; the mutation result objects are fresh
   * every render and would defeat the memoized return value below. */
  const { mutate: steerMessage } = useSteerMessageMutation();
  const { mutateAsync: cancelSteer } = useCancelSteerMutation();
  const { mutate: markFilesUsage } = useMarkFilesUsageMutation();
  const { mutate: enqueueAgentQueuedTurn } = useEnqueueAgentQueuedTurnMutation();
  const { mutateAsync: cancelAgentQueuedTurn } = useCancelAgentQueuedTurnMutation();
  const defaultAction = useRecoilValue<DuringRunAction>(store.duringRunDefaultAction);
  const setDefaultAction = useSetRecoilState(store.duringRunDefaultAction);
  const steerInterruptsByDefault = useRecoilValue(store.steerInterruptsByDefault);

  const endpoint = conversation?.endpointType ?? conversation?.endpoint;
  const steerable = !isAssistantsEndpoint(endpoint);
  const hasRealConvoId =
    conversationId != null && conversationId !== '' && conversationId !== Constants.NEW_CONVO;
  const serverQueueEnabled = isAgentsEndpoint(endpoint) && hasRealConvoId;
  /** v1 gates the during-run UI to the primary composer, like the HITL popover. */
  const enabled = steerable && index === 0;
  const queueKey = hasRealConvoId ? conversationId : Constants.NEW_CONVO;
  const queuedMessages = useRecoilValue(store.queuedMessagesByConvoId(queueKey));
  const setQueuedMessages = useSetRecoilState(store.queuedMessagesByConvoId(queueKey));
  const knownClientRequestIds = useMemo(
    () =>
      Array.from(
        new Set(
          queuedMessages.flatMap((item) =>
            item.server != null && item.clientRequestId != null ? [item.clientRequestId] : [],
          ),
        ),
      ).slice(0, 100),
    [queuedMessages],
  );
  const reconciliationUntil = queuedMessages.reduce<number | undefined>((latest, item) => {
    if (item.server?.status !== 'uncertain' || item.server.uncertainSince == null) {
      return latest;
    }
    const until = item.server.uncertainSince + QUEUED_TURN_RECONCILIATION_MS;
    return latest == null ? until : Math.max(latest, until);
  }, undefined);
  const nextReconciliationExpiry = queuedMessages.reduce<number | undefined>((earliest, item) => {
    if (
      item.server?.status !== 'uncertain' ||
      item.server.uncertainSince == null ||
      item.server.reconciliationExpired === true
    ) {
      return earliest;
    }
    const expiry = item.server.uncertainSince + QUEUED_TURN_RECONCILIATION_MS;
    return earliest == null ? expiry : Math.min(earliest, expiry);
  }, undefined);
  const { data: serverQueuedTurns } = useAgentQueuedTurns(
    conversationId,
    serverQueueEnabled,
    knownClientRequestIds,
    reconciliationUntil,
  );
  const activeGenerationCreatedAt = useRecoilValue(
    store.activeGenerationCreatedAtByConvoId(queueKey),
  );
  const activeGenerationProtocolVersion = useRecoilValue(
    store.activeGenerationProtocolVersionByConvoId(queueKey),
  );

  const applyQueuedTurnReceipts = useRecoilCallback(
    ({ snapshot, set }) =>
      (
        receipts: AgentQueuedTurnReceipt[],
        source: 'snapshot' | 'enqueue' | 'direct' = 'snapshot',
      ) => {
        const previousSettled = snapshot
          .getLoadable(store.settledQueuedTurnReceiptsByConvoId(queueKey))
          .getValue();
        const previousPending = snapshot
          .getLoadable(store.pendingQueuedTurnEnqueueIdsByConvoId(queueKey))
          .getValue();
        const completedRequestIds = new Set(
          source === 'enqueue' ? receipts.map((receipt) => receipt.clientRequestId) : [],
        );
        const nextPending = previousPending.filter((id) => !completedRequestIds.has(id));
        const settledByRequestId = new Map(
          previousSettled.map((receipt) => [receipt.clientRequestId, receipt]),
        );
        for (const receipt of receipts) {
          const existing = settledByRequestId.get(receipt.clientRequestId);
          if (
            existing != null &&
            !(
              existing.status === 'admitted_pending_boundary' &&
              receipt.status === 'admitted' &&
              receipt.effectivePredecessorCreatedAt != null
            )
          ) {
            continue;
          }
          let settled: SettledQueuedTurnReceipt | undefined;
          if (receipt.status === 'admitted' && receipt.effectivePredecessorCreatedAt != null) {
            settled = {
              clientRequestId: receipt.clientRequestId,
              status: 'admitted',
              effectivePredecessorCreatedAt: receipt.effectivePredecessorCreatedAt,
            };
          } else if (receipt.status === 'admitted') {
            settled = {
              clientRequestId: receipt.clientRequestId,
              status: 'admitted_pending_boundary',
            };
          } else if (receipt.status === 'cancelled') {
            settled = { clientRequestId: receipt.clientRequestId, status: 'cancelled' };
          } else if (
            receipt.status === 'dead' &&
            receipt.failure?.code !== 'ADMISSION_INDETERMINATE'
          ) {
            settled = { clientRequestId: receipt.clientRequestId, status: 'dead' };
          }
          if (settled == null) {
            continue;
          }
          settledByRequestId.set(receipt.clientRequestId, settled);
        }
        const terminalForReconciliation = new Map(settledByRequestId);
        const pendingRequestIds = new Set(nextPending);
        const nextSettled = [...settledByRequestId.values()].filter(
          (receipt) =>
            (receipt.status === 'admitted' && receipt.boundaryConsumed !== true) ||
            pendingRequestIds.has(receipt.clientRequestId),
        );
        if (source === 'enqueue') {
          set(store.pendingQueuedTurnEnqueueIdsByConvoId(queueKey), nextPending);
        }
        if (
          nextSettled.length !== previousSettled.length ||
          nextSettled.some((receipt, index) => receipt !== previousSettled[index])
        ) {
          set(store.settledQueuedTurnReceiptsByConvoId(queueKey), nextSettled);
        }
        if (source !== 'direct') {
          set(store.queuedMessagesByConvoId(queueKey), (previous) =>
            reconcileServerQueuedTurns(
              previous,
              receipts,
              terminalForReconciliation,
              source === 'snapshot',
            ),
          );
        }
      },
    [queueKey],
  );

  const finishQueuedTurnEnqueue = useRecoilCallback(
    ({ snapshot, set }) =>
      (clientRequestId: string): boolean => {
        const settledReceipts = snapshot
          .getLoadable(store.settledQueuedTurnReceiptsByConvoId(queueKey))
          .getValue();
        const settled = settledReceipts.find(
          (receipt) => receipt.clientRequestId === clientRequestId,
        );
        set(store.pendingQueuedTurnEnqueueIdsByConvoId(queueKey), (previous) =>
          previous.filter((id) => id !== clientRequestId),
        );
        if (
          settled != null &&
          (settled.status !== 'admitted' || settled.boundaryConsumed === true)
        ) {
          set(store.settledQueuedTurnReceiptsByConvoId(queueKey), (previous) =>
            previous.filter((receipt) => receipt.clientRequestId !== clientRequestId),
          );
        }
        return settled != null;
      },
    [queueKey],
  );

  useEffect(() => {
    if (!serverQueueEnabled || serverQueuedTurns == null) {
      return;
    }
    applyQueuedTurnReceipts(serverQueuedTurns);
  }, [serverQueueEnabled, serverQueuedTurns, applyQueuedTurnReceipts]);
  useEffect(() => {
    if (!serverQueueEnabled || nextReconciliationExpiry == null) {
      return;
    }
    const expire = () => {
      const observedAt = Date.now();
      setQueuedMessages((previous) =>
        previous.map((item) => {
          if (
            item.server?.status !== 'uncertain' ||
            item.server.uncertainSince == null ||
            item.server.reconciliationExpired === true ||
            item.server.uncertainSince + QUEUED_TURN_RECONCILIATION_MS > observedAt
          ) {
            return item;
          }
          return {
            ...item,
            server: { ...item.server, reconciliationExpired: true },
          };
        }),
      );
    };
    const delay = Math.max(0, nextReconciliationExpiry - Date.now());
    const timer = window.setTimeout(expire, delay);
    return () => window.clearTimeout(timer);
  }, [nextReconciliationExpiry, serverQueueEnabled, setQueuedMessages]);
  /** The start POST installs this epoch before any live mutation may be sent.
   * `isSubmitting` flips earlier so the user can keep typing; during that
   * bounded interval submits degrade to the local queue and Stop/steer refuse. */
  const canControlGeneration = activeGenerationCreatedAt != null;
  const duringRunActive = enabled && isSubmitting && !answerModeActive;
  /** Queue rows can be sent concurrently. Keep their captured origins while
   *  absent so a later capture still sees the complete logical queue. Origins
   *  are isolated per conversation because this hook survives navigation. */
  const queuedOriginsRef = useRef<Map<string, Map<string, QueuedMessageOrigin>>>(new Map());
  /** First-party FIFO admission: validation inside the steer route can await
   * agent ACL and attachment reads, so overlapping POSTs could otherwise reach
   * the durable queue out of submission order. Keep one request in flight per
   * conversation; later optimistic chips retain the epoch/id/time captured at
   * submission and dispatch only after the prior request settles. */
  const steerDispatchQueuesRef = useRef<
    Map<
      string,
      {
        active: boolean;
        pending: Array<(settle: () => void) => void>;
      }
    >
  >(new Map());
  const scheduleSteerDispatch = useCallback(
    (convoId: string, dispatch: (settle: () => void) => void) => {
      const existing = steerDispatchQueuesRef.current.get(convoId);
      const state = existing ?? { active: false, pending: [] };
      if (existing == null) {
        steerDispatchQueuesRef.current.set(convoId, state);
      }
      state.pending.push(dispatch);

      const startNext = () => {
        if (state.active) {
          return;
        }
        const next = state.pending[0];
        if (next == null) {
          if (steerDispatchQueuesRef.current.get(convoId) === state) {
            steerDispatchQueuesRef.current.delete(convoId);
          }
          return;
        }
        state.active = true;
        let settled = false;
        const settle = () => {
          if (settled) {
            return;
          }
          settled = true;
          const index = state.pending.indexOf(next);
          if (index >= 0) {
            state.pending.splice(index, 1);
          }
          state.active = false;
          startNext();
        };
        try {
          next(settle);
        } catch (error) {
          settle();
          throw error;
        }
      };

      startNext();
    },
    [],
  );
  /** `ask()` does not flip `isSubmitting` until the submission effect renders.
   * Two queued-row clicks in the same browser task would otherwise both remove
   * their items and the second submission could overwrite the first. */
  const idleSendInFlightRef = useRef(false);
  const pendingSteers = useRecoilValue(store.pendingSteersByConvoId(queueKey));

  useEffect(() => {
    if (!isSubmitting) {
      idleSendInFlightRef.current = false;
    }
  }, [isSubmitting]);

  /** Keep logical queue origins through the 202 ACK. They are needed to
   * reconstruct FIFO if several accepted queue items later return as terminal
   * leftovers. Once no live/failed chip references an origin, application or
   * conversion has settled it and the reconstruction entry can be released. */
  useEffect(() => {
    const origins = queuedOriginsRef.current.get(queueKey);
    if (origins == null) {
      return;
    }
    const referenced = new Set(
      pendingSteers.flatMap((steer) =>
        steer.queuedOrigin != null ? [steer.queuedOrigin.item.id] : [],
      ),
    );
    for (const originId of origins.keys()) {
      if (!referenced.has(originId)) {
        origins.delete(originId);
      }
    }
    if (origins.size === 0) {
      queuedOriginsRef.current.delete(queueKey);
    }
  }, [pendingSteers, queueKey]);

  /** The exact visible assistant tail is captured into a server queued turn,
   * while the approval bit keeps the steering controls honest. */
  const latestMessage = useLatestMessage(index, hasRealConvoId ? conversationId : null);
  const liveMessageState = useMemo(() => selectLiveMessageState(latestMessage), [latestMessage]);
  /** Both approval cards and `ask_user_question` suspend the current
   * generation while keeping its submission slot occupied. Answer mode hides
   * the ordinary during-run composer, but waiting-message controls still need
   * to know a live generation exists so they remain discoverable and disabled
   * instead of looking as though the action disappeared. */
  const pausedOnApproval =
    enabled && isSubmitting ? answerModeActive || (liveMessageState?.approval ?? false) : false;

  /** Whether a steer can reach the live run right now — independent of the
   *  user's default action, so the per-send menu can always override to
   *  steer when it's genuinely available. */
  const canSteer = hasRealConvoId && canControlGeneration && !pausedOnApproval;
  /** Whether a queued row has a real immediate-send path. Answer mode keeps
   * `isSubmitting` true while hiding during-run steering, so presenting Send
   * now there would be an enabled no-op. */
  const canSendQueuedNow = !isSubmitting || (duringRunActive && canSteer);
  /** Steering needs a live server-side job; degrade to queue otherwise. */
  const effectiveAction: DuringRunAction = canSteer ? defaultAction : 'queue';

  /** Live submission state for POST callbacks — the closure value can be
   *  stale by the time the steer response arrives. */
  const isSubmittingRef = useRef(isSubmitting);
  isSubmittingRef.current = isSubmitting;
  const visibleConversationRef = useRef(conversationId);
  visibleConversationRef.current = conversationId;

  /**
   * How each conversation's last run ended, kept because `useQueueDrain`
   * CONSUMES the one-shot signal — by the time a reclaim resolves it is already
   * gone. Every subscriber renders before the drain's effect nulls it, so the
   * outcome is captured first. Both carriers are watched: the index signal, and
   * the copy parked under the conversation when the run ended while the user
   * was looking elsewhere.
   *
   * Keyed by conversation because this hook is REUSED across chats: a single
   * slot would answer for whichever chat is on screen when the reclaim lands,
   * not the one the words belong to. An entry is dropped once that conversation
   * starts another run — an older end no longer describes what is happening.
   */
  const runEnd = useRecoilValue(store.runEndByIndex(index));
  const parkedRunEnd = useRecoilValue(store.pendingRunEndByConvoId(queueKey));
  const runEndsRef = useRef<Map<string, RunEnd>>(new Map());
  const observedRunEnd = [runEnd, parkedRunEnd].find(
    (end) => end != null && end.conversationId === conversationId,
  );
  if (observedRunEnd != null) {
    runEndsRef.current.set(conversationId, observedRunEnd);
  } else if (isSubmitting) {
    runEndsRef.current.delete(conversationId);
  }

  const upsertSteerChip = useRecoilCallback(
    ({ set }) =>
      (convoId: string, steer: PendingSteer) => {
        set(store.pendingSteersByConvoId(convoId), (prev) => {
          const existing = prev.findIndex((item) => item.steerId === steer.steerId);
          if (existing >= 0) {
            const next = [...prev];
            next[existing] = steer;
            return next;
          }
          return [...prev, steer];
        });
      },
    [],
  );

  const replaceSteerChip = useRecoilCallback(
    ({ set }) =>
      (convoId: string, localId: string, steer: PendingSteer | null) => {
        set(store.pendingSteersByConvoId(convoId), (prev) => {
          const next = prev.filter((item) => item.steerId !== localId);
          return steer ? [...next, steer] : next;
        });
      },
    [],
  );

  /**
   * Resolves the 202 ACK against the applied-id set: `on_steer_applied` rides
   * the SSE and can land BEFORE the HTTP response, in which case its removal
   * already passed — minting a `pending` chip here would strand it forever.
   * An ACK landing AFTER the run ended (final/abort/error already processed,
   * server queue drained or dropped) converts straight to a queued follow-up:
   * no later event will ever resolve a `pending` chip for a finished run.
   */
  const acknowledgeSteer = useRecoilCallback(
    ({ snapshot, set }) =>
      (convoId: string, localId: string, steer: PendingSteer): boolean => {
        const applied = snapshot.getLoadable(store.appliedSteerIdsByConvoId(convoId)).getValue();
        const alreadyApplied = applied.includes(steer.steerId) || applied.includes(localId);
        const alreadyAccepted = snapshot
          .getLoadable(store.acceptedSteerClientIdsByConvoId(convoId))
          .getValue()
          .includes(localId);
        const activeEpoch = snapshot
          .getLoadable(store.activeGenerationCreatedAtByConvoId(convoId))
          .getValue();
        /** A replacement can already be submitting when an older generation's
         * delayed 202 arrives. `isSubmitting` alone would re-mint the old chip
         * after replacement reconciliation, with no old apply event left to
         * settle it. Every POST reaching this callback captured a non-null
         * source epoch before dispatch, so either a mismatch or a later clear
         * proves that source generation is no longer active. */
        const runReplaced =
          steer.generationCreatedAt != null &&
          (activeEpoch == null || steer.generationCreatedAt !== activeEpoch);
        // This hook instance survives navigation. The visible pane's idle flag
        // says nothing about an off-screen origin run, so only infer ordinary
        // terminal state while the callback still belongs to the visible chat.
        const runOver =
          runReplaced || (visibleConversationRef.current === convoId && !isSubmittingRef.current);
        set(store.acceptedSteerClientIdsByConvoId(convoId), (prev) =>
          appendAppliedSteerIds(prev, [localId]),
        );
        set(store.pendingSteersByConvoId(convoId), (prev) => {
          const local = prev.find((item) => item.steerId === localId);
          let acknowledged = steer;
          if ((local?.preemptRevision ?? 0) > (steer.preemptRevision ?? 0)) {
            const { preempt: _stalePreempt, ...withoutStaleLabel } = steer;
            acknowledged = {
              ...withoutStaleLabel,
              ...(local?.preempt === true && { preempt: true }),
              preemptRevision: local?.preemptRevision,
            };
          }
          const next = prev.filter((item) => item.steerId !== localId);
          // Upsert: an SSE reconnect may have reseeded the chip under the
          // server id already — appending again would duplicate it.
          const alreadySeeded = next.some((item) => item.steerId === steer.steerId);
          return alreadyApplied || alreadyAccepted || runOver || alreadySeeded
            ? next
            : [...next, acknowledged];
        });
        /** `alreadyAccepted` can come from the correlation update that precedes
         * the delayed HTTP response; it proves server ownership, not delivery.
         * Once the source epoch is over/replaced we still must recover it. */
        if (alreadyApplied || !runOver) {
          return false;
        }
        // The server accepted but this visible run is already terminal. Its
        // terminal close may have parked the item, so the caller must route it
        // through the recovery converter (deterministic next-turn id), not an
        // ordinary editable queue row.
        return true;
      },
    [],
  );

  const settleReceiptReplay = useRecoilCallback(
    ({ set }) =>
      (convoId: string, localId: string, serverId: string) => {
        set(store.appliedSteerIdsByConvoId(convoId), (prev) =>
          appendAppliedSteerIds(prev, [localId, serverId]),
        );
        set(store.acceptedSteerClientIdsByConvoId(convoId), (prev) =>
          appendAppliedSteerIds(prev, [localId]),
        );
        set(store.pendingSteersByConvoId(convoId), (prev) =>
          prev.filter((steer) => steer.steerId !== localId && steer.steerId !== serverId),
        );
      },
    [],
  );

  /** Terminal/applied SSE can settle the optimistic client id before either
   * HTTP callback. Those callbacks must become no-ops or a lost response can
   * resurrect already-delivered words as a failed chip or queued fallback. */
  const isSteerAcceptedOrSettled = useRecoilCallback(
    ({ snapshot }) =>
      (convoId: string, clientSteerId: string) => {
        const applied = snapshot.getLoadable(store.appliedSteerIdsByConvoId(convoId)).getValue();
        if (applied.includes(clientSteerId)) {
          return true;
        }
        const accepted = snapshot
          .getLoadable(store.acceptedSteerClientIdsByConvoId(convoId))
          .getValue();
        if (accepted.includes(clientSteerId)) {
          return true;
        }
        return snapshot
          .getLoadable(store.pendingSteersByConvoId(convoId))
          .getValue()
          .some((steer) => steer.status === 'pending' && steer.clientSteerId === clientSteerId);
      },
    [],
  );

  /** Fire-and-forget TTL hold for uploads entering the client queue: a
   *  queued message can outlive the upload window (long run, approval pause)
   *  and send-time marking only happens at drain. The server extends the
   *  deadline rather than clearing it, so a queue this tab never drains still
   *  gets reaped. Failure is tolerated; send-time marking is the backstop. */
  const markQueuedFilesUsage = useCallback(
    (files?: TMessage['files']) => {
      if (files == null || files.length === 0) {
        return;
      }
      const file_ids: string[] = [];
      for (const file of files) {
        if (typeof file.file_id === 'string' && file.file_id.length > 0) {
          file_ids.push(file.file_id);
        }
        if (file_ids.length === QUEUE_USAGE_MAX_FILES) {
          break;
        }
      }
      if (file_ids.length > 0) {
        markFilesUsage({ file_ids });
      }
    },
    [markFilesUsage],
  );

  const updateQueuedMessage = useRecoilCallback(
    ({ set }) =>
      (id: string, update: (item: QueuedMessage) => QueuedMessage | null) => {
        set(store.queuedMessagesByConvoId(queueKey), (previous) =>
          previous.flatMap((item) => {
            if (item.id !== id) {
              return [item];
            }
            const next = update(item);
            return next == null ? [] : [next];
          }),
        );
      },
    [queueKey],
  );

  const enqueue = useRecoilCallback(
    ({ set }) =>
      (
        text: string,
        options?: {
          front?: boolean;
          files?: TMessage['files'];
          quotes?: string[];
          manualSkills?: string[];
          /** Set when the files were ALREADY queued/steered: their TTL was
           *  held when they first entered the queue (or at the steer 202). */
          skipUsageMark?: boolean;
          id?: string;
          createdAt?: number;
          clientRequestId?: string;
          expectedPredecessorCreatedAt?: number;
        },
      ) => {
        const trimmed = text.trim();
        if (trimmed.length === 0) {
          return;
        }
        const parentMessageId = liveMessageState?.parentMessageId;
        /** The active epoch is the authority-transfer fence. During startup an
         * existing branch tail may already be visible while no generation owns
         * it yet, so keep those turns local until the epoch is concrete. */
        const serverOwned =
          serverQueueEnabled && parentMessageId != null && activeGenerationCreatedAt != null;
        const generatedClientRequestId = options?.clientRequestId == null;
        const clientRequestId = options?.clientRequestId ?? (serverOwned ? v4() : undefined);
        const item: QueuedMessage = {
          id: options?.id ?? v4(),
          text: trimmed,
          createdAt: options?.createdAt ?? Date.now(),
          ...(clientRequestId != null && { clientRequestId }),
          ...(serverOwned && {
            parentMessageId,
            server: { status: 'sending' },
          }),
          ...((options?.expectedPredecessorCreatedAt ?? activeGenerationCreatedAt) != null && {
            expectedPredecessorCreatedAt:
              options?.expectedPredecessorCreatedAt ?? activeGenerationCreatedAt ?? undefined,
          }),
          ...(options?.files && options.files.length > 0 && { files: options.files }),
          ...(options?.quotes && options.quotes.length > 0 && { quotes: options.quotes }),
          ...(options?.manualSkills &&
            options.manualSkills.length > 0 && {
              manualSkills: options.manualSkills,
            }),
          ...(options?.front && { priority: true }),
        };
        set(store.queuedMessagesByConvoId(queueKey), (prev) =>
          [...prev, item].sort(compareQueuedMessages),
        );
        if (options?.skipUsageMark !== true) {
          markQueuedFilesUsage(options?.files);
        }
        if (!serverOwned || clientRequestId == null) {
          return;
        }
        set(store.pendingQueuedTurnEnqueueIdsByConvoId(queueKey), (previous) =>
          previous.includes(clientRequestId) ? previous : [...previous, clientRequestId],
        );
        const serverFiles = toQueuedTurnFileRefs(item.files);
        /** Commit the optimistic Recoil row before mutation callbacks can
         * reconcile it. This also makes synchronous test/adaptor completions
         * obey the same ordering as a real network response. */
        queueMicrotask(() =>
          enqueueAgentQueuedTurn(
            {
              conversationId,
              clientRequestId,
              parentMessageId,
              text: item.text,
              ...(serverFiles != null && { files: serverFiles }),
              ...(item.quotes != null && item.quotes.length > 0 && { quotes: item.quotes }),
              ...(item.manualSkills != null &&
                item.manualSkills.length > 0 && {
                  manualSkills: item.manualSkills,
                }),
              ...(item.priority === true && { priority: true }),
              ...(item.expectedPredecessorCreatedAt != null && {
                expectedPredecessorCreatedAt: item.expectedPredecessorCreatedAt,
              }),
            },
            {
              onSuccess: (receipt) => {
                applyQueuedTurnReceipts([receipt], 'enqueue');
              },
              onError: (error) => {
                if (finishQueuedTurnEnqueue(clientRequestId)) {
                  return;
                }
                updateQueuedMessage(item.id, (current) => {
                  if (isDefiniteQueuedTurnsUnsupported(error)) {
                    const {
                      server: _server,
                      parentMessageId: _parentMessageId,
                      clientRequestId: fallbackClientRequestId,
                      ...legacy
                    } = current;
                    return {
                      ...legacy,
                      ...(!generatedClientRequestId && fallbackClientRequestId != null
                        ? { clientRequestId: fallbackClientRequestId }
                        : {}),
                    };
                  }
                  if (!isDefiniteQueuedTurnRejection(error)) {
                    return {
                      ...current,
                      server: {
                        ...current.server,
                        status: 'uncertain',
                        uncertainSince: current.server?.uncertainSince ?? Date.now(),
                      },
                    };
                  }
                  const code = getSteerErrorCode(error);
                  return {
                    ...current,
                    server: {
                      ...current.server,
                      status: 'rejected',
                      ...(code != null && { errorCode: code }),
                    },
                  };
                });
              },
            },
          ),
        );
      },
    [
      queueKey,
      conversationId,
      serverQueueEnabled,
      liveMessageState?.parentMessageId,
      markQueuedFilesUsage,
      activeGenerationCreatedAt,
      enqueueAgentQueuedTurn,
      applyQueuedTurnReceipts,
      finishQueuedTurnEnqueue,
      updateQueuedMessage,
    ],
  );

  /** Consumes completed composer attachments into message file refs (clearing
   *  the composer) so they pair with THIS queued message instead of gluing
   *  onto whatever `ask` vacuums up next. */
  const takeComposerFiles = useCallback((): TMessage['files'] => {
    if (files == null || files.size === 0 || setFiles == null) {
      return undefined;
    }
    const taken = Array.from(files.values()).map((file) => ({
      file_id: file.file_id,
      filepath: file.filepath,
      type: file.type ?? '',
      height: file.height,
      width: file.width,
      // Retained beyond the submission shape so "Edit message" can restore
      // the attachment into the composer with its real name and size.
      filename: file.filename,
      bytes: file.size,
    }));
    setFiles(new Map());
    setFilesToDelete({});
    return taken;
  }, [files, setFiles, setFilesToDelete]);

  /** Consumes staged quote chips + manual skill picks (mirroring `ask()`'s
   *  fresh-submit drain of the same atoms) so they pair with THIS queued
   *  message instead of gluing onto whatever the user sends next. */
  const takeComposerContext = useRecoilCallback(
    ({ snapshot, reset }) =>
      (): QueuedMessageContext => {
        const quotes = snapshot
          .getLoadable(store.pendingQuotesByConvoId(conversationId))
          .getValue();
        const manualSkills = snapshot
          .getLoadable(store.pendingManualSkillsByConvoId(conversationId))
          .getValue();
        if (quotes.length > 0) {
          reset(store.pendingQuotesByConvoId(conversationId));
        }
        if (manualSkills.length > 0) {
          reset(store.pendingManualSkillsByConvoId(conversationId));
        }
        return {
          ...(quotes.length > 0 && { quotes }),
          ...(manualSkills.length > 0 && { manualSkills }),
        };
      },
    [conversationId],
  );

  /** Quotes-only drain for composer-origin steers: the excerpts ride the steer
   *  POST into the live run, while manual skill picks stay staged — a skill
   *  pick configures a NEW turn's agent run and cannot apply to a mid-run
   *  injection, so it keeps waiting for the next full submission. */
  const takeComposerQuotes = useRecoilCallback(
    ({ snapshot, reset }) =>
      (): QueuedMessageContext => {
        const quotes = snapshot
          .getLoadable(store.pendingQuotesByConvoId(conversationId))
          .getValue();
        if (quotes.length === 0) {
          return {};
        }
        reset(store.pendingQuotesByConvoId(conversationId));
        return { quotes };
      },
    [conversationId],
  );

  /** Returns rejected excerpts to the composer chips from the SURVIVING steer
   *  chip — used ONLY for a settled receipt replay, where the steer already
   *  injected in the source generation and no future applied event or
   *  terminal conversion will ever re-home the chip's quotes. An ordinary
   *  no-echo ACK deliberately does NOT reclaim: its steer is still queued, so
   *  the quotes stay carried on the pending chip — the applied-event
   *  reconciliation re-stages them at the actual moment of loss, while a
   *  terminal leftover conversion moves them onto the recovered row, which
   *  sends via `ask` where quotes work on any server. When no chip remains,
   *  another path already owns the excerpts and re-staging would
   *  double-deliver. The chip is stripped in the same update (including its
   *  captured queue-origin copy) so the restaged composer chips stay their
   *  single representation. */
  const reclaimRejectedChipQuotes = useRecoilCallback(
    ({ snapshot, set }) =>
      (convoId: string, steerIds: string[]) => {
        const chips = snapshot.getLoadable(store.pendingSteersByConvoId(convoId)).getValue();
        const chip = chips.find((steer) => steerIds.includes(steer.steerId));
        const quotes = chip?.quotes ?? chip?.queuedOrigin?.item.quotes;
        if (quotes == null || quotes.length === 0) {
          return;
        }
        set(store.pendingQuotesByConvoId(convoId), (prev) => mergeRestagedQuotes(prev, quotes));
        set(store.pendingSteersByConvoId(convoId), (prev) => {
          let changed = false;
          const next = prev.map((steer) => {
            const originHasQuotes = steer.queuedOrigin?.item.quotes != null;
            if (!steerIds.includes(steer.steerId) || (steer.quotes == null && !originHasQuotes)) {
              return steer;
            }
            changed = true;
            const { quotes: _quotes, ...rest } = steer;
            if (!originHasQuotes || rest.queuedOrigin == null) {
              return rest;
            }
            const { quotes: _originQuotes, ...originItem } = rest.queuedOrigin.item;
            return {
              ...rest,
              queuedOrigin: { ...rest.queuedOrigin, item: originItem },
            };
          });
          return changed ? next : prev;
        });
      },
    [],
  );

  /** Consumes the composer's autosaved draft once its text has been taken into
   *  a steer or queued item. The composer clears via the form's `reset()`,
   *  which is programmatic and never fires the `input` event `useAutoSave`
   *  listens on — so the draft would outlive the submit. It is keyed under
   *  this pane's pending draft key here (every caller is gated on
   *  `duringRunActive`, which requires `isSubmitting` and rules out the
   *  answer-mode draft key), and run end migrates a surviving pending draft
   *  onto the conversation and restores it: resurfacing text the user already
   *  sent. */
  const takeComposerDraft = useCallback(() => {
    clearAllDrafts(getPendingDraftId(index));
  }, [index]);

  const removeQueued = useRecoilCallback(
    ({ set }) =>
      (id: string) => {
        set(store.queuedMessagesByConvoId(queueKey), (prev) =>
          prev.filter((item) => item.id !== id),
        );
      },
    [queueKey],
  );

  const downgradeServerQueuedTurn = useRecoilCallback(
    ({ snapshot, set }) =>
      (id: string): boolean => {
        const queue = snapshot.getLoadable(store.queuedMessagesByConvoId(queueKey)).getValue();
        let found = false;
        const next = queue.map((item) => {
          if (item.id !== id) {
            return item;
          }
          found = true;
          const { server: _server, parentMessageId: _parentMessageId, ...local } = item;
          return local;
        });
        if (found) {
          set(store.queuedMessagesByConvoId(queueKey), next);
        }
        return found;
      },
    [queueKey],
  );

  /** Once a parked source is discarded it must never be retried as a recovery
   * attempt. Downgrade the row in place so a guarded Edit that finds a newer
   * draft can leave the same words, context, identity, and queue position as
   * an ordinary local follow-up. */
  const downgradeQueuedRecovery = useRecoilCallback(
    ({ snapshot, set }) =>
      (id: string): boolean => {
        const queue = snapshot.getLoadable(store.queuedMessagesByConvoId(queueKey)).getValue();
        let found = false;
        const next = queue.map((item) => {
          if (item.id !== id) {
            return item;
          }
          found = true;
          const {
            clientRequestId: _clientRequestId,
            recoverySteerId: _recoverySteerId,
            recoveryClientSteerId: _recoveryClientSteerId,
            ...ordinary
          } = item;
          return ordinary;
        });
        if (found) {
          set(store.queuedMessagesByConvoId(queueKey), next);
        }
        return found;
      },
    [queueKey],
  );

  /** Settle a queued row's terminal recovery source before an Edit/Remove.
   * Ordinary rows have no server copy. A v2 leftover first uses its durable
   * receipt to atomically discard the parked copy, then becomes an ordinary
   * local row; the caller decides whether the live composer can consume it.
   * The cancel deliberately omits the active epoch: the receipt belongs to the
   * terminal source generation, not whichever run now occupies the chat. */
  const discardQueued = useCallback(
    async (item: QueuedMessage): Promise<boolean> => {
      if (item.server != null) {
        if (item.server.status === 'rejected' && item.server.id == null) {
          return downgradeServerQueuedTurn(item.id);
        }
        if (item.server.id == null || !hasRealConvoId) {
          showToast({
            message: localize('com_ui_steer_cancel_failed'),
            status: 'error',
          });
          return false;
        }
        try {
          const receipt = await cancelAgentQueuedTurn({
            conversationId,
            queuedTurnId: item.server.id,
          });
          if (receipt.status !== 'cancelled') {
            showToast({
              message: localize('com_ui_steer_cancel_failed'),
              status: 'error',
            });
            return false;
          }
          applyQueuedTurnReceipts([receipt], 'direct');
          return downgradeServerQueuedTurn(item.id);
        } catch {
          showToast({
            message: localize('com_ui_steer_cancel_failed'),
            status: 'error',
          });
          return false;
        }
      }
      if (item.recoverySteerId == null) {
        return true;
      }
      if (item.recoveryClientSteerId == null || !hasRealConvoId) {
        showToast({
          message: localize('com_ui_steer_cancel_failed'),
          status: 'error',
        });
        return false;
      }
      try {
        const { removed } = await cancelSteer({
          conversationId,
          steerId: item.recoverySteerId,
          clientSteerId: item.recoveryClientSteerId,
        });
        if (removed !== true) {
          showToast({
            message: localize('com_ui_steer_cancel_failed'),
            status: 'error',
          });
          return false;
        }
        return downgradeQueuedRecovery(item.id);
      } catch {
        showToast({
          message: localize('com_ui_steer_cancel_failed'),
          status: 'error',
        });
        return false;
      }
    },
    [
      cancelSteer,
      cancelAgentQueuedTurn,
      applyQueuedTurnReceipts,
      conversationId,
      downgradeQueuedRecovery,
      downgradeServerQueuedTurn,
      hasRealConvoId,
      localize,
      showToast,
    ],
  );

  /** Capture-then-remove, including the item's neighbours, so any refused send
   *  or rejected steer can restore the ORIGINAL item in place even if the run
   *  drains an adjacent entry while the request is in flight. */
  const takeQueued = useRecoilCallback(
    ({ snapshot, set }) =>
      (id: string): QueuedMessageOrigin | undefined => {
        const queue = snapshot.getLoadable(store.queuedMessagesByConvoId(queueKey)).getValue();
        const index = queue.findIndex((item) => item.id === id);
        if (index < 0) {
          return undefined;
        }
        const item = queue[index];
        let queuedOrigins = queuedOriginsRef.current.get(queueKey);
        if (queuedOrigins == null) {
          queuedOrigins = new Map();
          queuedOriginsRef.current.set(queueKey, queuedOrigins);
        }
        let logicalQueue = queue;
        for (const pendingOrigin of queuedOrigins.values()) {
          logicalQueue = insertQueuedOrigin(logicalQueue, pendingOrigin);
        }
        const logicalIndex = logicalQueue.findIndex((queued) => queued.id === id);
        const origin = {
          item,
          beforeIds: logicalQueue.slice(0, logicalIndex).map((queued) => queued.id),
          afterIds: logicalQueue.slice(logicalIndex + 1).map((queued) => queued.id),
        };
        queuedOrigins.set(id, origin);
        set(store.queuedMessagesByConvoId(queueKey), (prev) =>
          prev.filter((item) => item.id !== id),
        );
        return origin;
      },
    [queueKey],
  );

  const releaseQueuedOrigin = useCallback(
    (origin: QueuedMessageOrigin) => {
      const queuedOrigins = queuedOriginsRef.current.get(queueKey);
      queuedOrigins?.delete(origin.item.id);
      if (queuedOrigins?.size === 0) {
        queuedOriginsRef.current.delete(queueKey);
      }
    },
    [queueKey],
  );

  const registerQueuedOrigin = useCallback(
    (origin: QueuedMessageOrigin) => {
      let queuedOrigins = queuedOriginsRef.current.get(queueKey);
      if (queuedOrigins == null) {
        queuedOrigins = new Map();
        queuedOriginsRef.current.set(queueKey, queuedOrigins);
      }
      queuedOrigins.set(origin.item.id, origin);
    },
    [queueKey],
  );

  /** Restore the exact item between its nearest surviving original neighbours,
   *  never duplicated. If every neighbour disappeared, newly front-prioritized
   *  entries stay ahead while ordinary entries created later stay behind. */
  const restoreQueued = useRecoilCallback(
    ({ set }) =>
      (origin: QueuedMessageOrigin) => {
        releaseQueuedOrigin(origin);
        set(store.queuedMessagesByConvoId(queueKey), (prev) => insertQueuedOrigin(prev, origin));
      },
    [queueKey, releaseQueuedOrigin],
  );

  /**
   * Re-posts a spent run-end signal so the drain wakes and reconsiders the
   * queue. No-op while a signal for THIS conversation is still armed: that
   * drain has not run yet and will see the item on its own, so arming a second
   * carrier would drain twice and send two messages.
   *
   * A signal for a DIFFERENT conversation is not that proof. The index slot is
   * shared, and the drain parks a foreign signal under its own conversation and
   * then only inspects the active one's queue — this item would never be looked
   * at. Park ours alongside it.
   */
  const rearmDrain = useRecoilCallback(
    ({ snapshot, set }) =>
      (convoId: string, end: RunEnd) => {
        const indexArmed = snapshot.getLoadable(store.runEndByIndex(index)).getValue();
        const parkedArmed = snapshot.getLoadable(store.pendingRunEndByConvoId(convoId)).getValue();
        if (isSameRunEpoch(indexArmed, end) || isSameRunEpoch(parkedArmed, end)) {
          return;
        }
        set(store.pendingRunEndByConvoId(convoId), end);
      },
    [index],
  );

  /** Restore a server-owned steer as the same queued follow-up and wake a
   * drain whose one-shot completion signal may already have been consumed
   * while the recovery request was in flight. Shared by reclaim and durable
   * receipt replay so neither round-trip can strand accepted words. */
  const queueRecoveredSteer = useCallback(
    (steer: PendingSteer) => {
      convertSteersToQueued(
        conversationId,
        [
          {
            steerId: steer.steerId,
            ...(steer.clientSteerId && { clientSteerId: steer.clientSteerId }),
            text: steer.text,
            createdAt: steer.createdAt,
            ...(steer.files && steer.files.length > 0 && { files: steer.files }),
            ...carriedSteerContext(steer),
            ...(steer.queuedOrigin && { queuedOrigin: steer.queuedOrigin }),
          },
        ],
        {
          /** A durable receipt belongs to the generation that produced it. The
           * visible conversation may already advertise a replacement/legacy
           * generation by the time this late ACK lands, but that must not strip
           * the receipt-bound recovery identity from the queued item. */
          generationProtocolVersion: steer.generationProtocolVersion,
        },
      );
      const lastRunEnd = runEndsRef.current.get(conversationId);
      if (lastRunEnd?.outcome === 'completed') {
        rearmDrain(conversationId, lastRunEnd);
      }
    },
    [conversationId, convertSteersToQueued, rearmDrain],
  );

  const armDrainAfterAbort = useRecoilCallback(
    ({ set }) =>
      () => {
        if (activeGenerationCreatedAt == null) {
          return;
        }
        set(store.drainAfterAbortByIndex(index), {
          conversationId: queueKey,
          generationCreatedAt: activeGenerationCreatedAt,
        });
      },
    [index, queueKey, activeGenerationCreatedAt],
  );

  /** POSTs a steer (text + files + quotes; the server merges the quotes into
   *  the model-bound turn at the injection boundary). `context` doubles as the
   *  RESTORE payload: every degradation path threads it back into the
   *  requeue/send fallback so the item's quotes and manual skills survive.
   *  Skill picks never ride the POST — they configure a NEW turn's run, so a
   *  queued-origin steer only carries them for restoration. */
  const submitSteer = useCallback(
    (
      text: string,
      steerFiles?: TMessage['files'],
      context?: QueuedMessageContext,
      opts?: SubmitSteerOptions,
    ): boolean => {
      const trimmed = text.trim();
      if (trimmed.length === 0 || !hasRealConvoId) {
        return false;
      }
      const preempt = opts?.preempt === true;
      const targetGenerationCreatedAt =
        opts?.generationCreatedAt ?? activeGenerationCreatedAt ?? undefined;
      if (targetGenerationCreatedAt == null) {
        return false;
      }
      const files = steerFiles && steerFiles.length > 0 ? steerFiles : undefined;
      const targetGenerationProtocolVersion =
        opts?.generationProtocolVersion ?? activeGenerationProtocolVersion;
      /** Rides every chip state so a terminal conversion (late ACK, run-end
       *  leftover report) can restore the queued item's full context. */
      const carried = carriedSteerContext(context);
      const localId = opts?.clientSteerId ?? `local-${v4()}`;
      /** The true submission time, carried through the ACK and failure chips so
       *  a later conversion sorts this steer by when it was SENT, not when its
       *  202 landed — otherwise a draft queued during the round-trip would drain
       *  ahead of a steer submitted before it. */
      const createdAt = opts?.createdAt ?? Date.now();
      /** If the steer loses its race with run finalization, its normal-send
       * fallback must still be tied to the generation it targeted. Otherwise
       * a newer run started by another tab can be replaced by this stale
       * fallback. Every fallback also carries a queue origin: an existing row
       * keeps its exact logical slot, while a composer-origin steer gets a
       * stable synthetic row so a predecessor 409 cannot discard its text or
       * files when the newer run wins. */
      const fallbackOrigin: QueuedMessageOrigin = opts?.queuedOrigin ?? {
        item: {
          id: localId,
          text: trimmed,
          createdAt,
          expectedPredecessorCreatedAt: targetGenerationCreatedAt,
          ...(files && { files }),
          ...carried,
          ...(context?.clientRequestId && {
            clientRequestId: context.clientRequestId,
          }),
          ...(context?.recoverySteerId && {
            recoverySteerId: context.recoverySteerId,
          }),
        },
        beforeIds: [],
        afterIds: [],
      };
      const fallbackContext: QueuedMessageContext = {
        ...context,
        expectedPredecessorCreatedAt: targetGenerationCreatedAt,
        queuedMessageOrigin: fallbackOrigin,
      };
      /** A queued-origin attempt must be reversible as the same queue item,
       *  not merely reproducible from its text. This preserves its identity,
       *  timestamp, priority, future fields, and original array position. */
      const restoreRejectedSteer = () => {
        if (opts?.queuedOrigin != null) {
          restoreQueued(opts.queuedOrigin);
        } else {
          enqueue(trimmed, { id: localId, createdAt, files, ...context });
        }
        const lastRunEnd = runEndsRef.current.get(conversationId);
        if (lastRunEnd?.outcome === 'completed') {
          rearmDrain(conversationId, lastRunEnd);
        }
      };
      if (opts?.queuedOrigin != null) {
        registerQueuedOrigin(opts.queuedOrigin);
      }
      upsertSteerChip(conversationId, {
        steerId: localId,
        text: trimmed,
        status: 'sending',
        createdAt,
        ...(files && { files }),
        ...(preempt && { preempt: true }),
        ...(targetGenerationCreatedAt != null && {
          generationCreatedAt: targetGenerationCreatedAt,
        }),
        generationProtocolVersion: targetGenerationProtocolVersion,
        ...(opts?.queuedOrigin && { queuedOrigin: opts.queuedOrigin }),
        ...carried,
      });
      scheduleSteerDispatch(conversationId, (settleDispatch) => {
        steerMessage(
          {
            conversationId,
            clientSteerId: localId,
            text: trimmed,
            ...(files && { files }),
            ...(carried.quotes && { quotes: carried.quotes }),
            ...(preempt && { preempt }),
            ...(targetGenerationCreatedAt != null && {
              generationCreatedAt: targetGenerationCreatedAt,
            }),
          },
          {
            onSuccess: (response) => {
              try {
                /** A 202 without the echo means a pre-quotes replica queued
                 *  the words without their excerpts. The quotes are NOT
                 *  re-staged here — the steer has not injected yet, so they
                 *  stay carried on the pending chip: a quote-less applied
                 *  event re-stages them at the actual loss, and a terminal
                 *  leftover conversion carries them onto the recovered row
                 *  instead (its normal send delivers quotes on any server).
                 *  Only a settled replay — an already-injected steer with no
                 *  future event to re-home the chip — reclaims immediately. */
                const quotesRejected = carried.quotes != null && response.quotesAccepted !== true;
                const canUseV2Receipt =
                  targetGenerationProtocolVersion === 2 && supportsGenerationProtocolV2(response);
                if (canUseV2Receipt && response.settled === true) {
                  if (response.leftover === true) {
                    queueRecoveredSteer({
                      steerId: response.steerId,
                      clientSteerId: localId,
                      text: trimmed,
                      status: 'pending',
                      createdAt,
                      ...(files && { files }),
                      ...(targetGenerationCreatedAt != null && {
                        generationCreatedAt: targetGenerationCreatedAt,
                      }),
                      generationProtocolVersion: targetGenerationProtocolVersion,
                      ...(opts?.queuedOrigin && {
                        queuedOrigin: opts.queuedOrigin,
                      }),
                      ...carried,
                    });
                  } else {
                    if (quotesRejected) {
                      reclaimRejectedChipQuotes(conversationId, [localId, response.steerId]);
                    }
                    settleReceiptReplay(conversationId, localId, response.steerId);
                  }
                  return;
                }
                /** The server's echo is authoritative: a deployment whose SDK
                 *  cannot seal mid-stream still queues the steer and answers
                 *  `preempt: false`, which relabels the chip to the ordinary
                 *  wording instead of surfacing an error. */
                const acknowledged = {
                  steerId: response.steerId,
                  clientSteerId: localId,
                  text: trimmed,
                  status: 'pending',
                  createdAt,
                  ...(files && { files }),
                  ...(response.preempt === true && { preempt: true }),
                  ...(response.preemptRevision != null && {
                    preemptRevision: response.preemptRevision,
                  }),
                  ...(targetGenerationCreatedAt != null && {
                    generationCreatedAt: targetGenerationCreatedAt,
                  }),
                  generationProtocolVersion: targetGenerationProtocolVersion,
                  ...(opts?.queuedOrigin && {
                    queuedOrigin: opts.queuedOrigin,
                  }),
                  ...carried,
                } satisfies PendingSteer;
                if (acknowledgeSteer(conversationId, localId, acknowledged)) {
                  /** Terminal conversion re-homes the words as a queued
                   *  follow-up that sends via `ask` — the carried quotes ride
                   *  it there, so nothing is re-staged. */
                  queueRecoveredSteer(acknowledged);
                }
              } finally {
                settleDispatch();
              }
            },
            onError: (error) => {
              try {
                if (isSteerAcceptedOrSettled(conversationId, localId)) {
                  replaceSteerChip(conversationId, localId, null);
                  return;
                }
                const code = getSteerErrorCode(error);
                const originStillVisible = visibleConversationRef.current === conversationId;
                if (code === 'NO_ACTIVE_RUN') {
                  // The run finished before the steer landed. While the final SSE
                  // is still settling, `ask()`'s in-flight guard would drop a
                  // direct send — queue it so the run-end drain fires it instead.
                  // The explicit empty array stops `ask` from vacuuming composer
                  // files staged for a DIFFERENT draft. A refused send (`false`)
                  // falls back to the queue too — the chip is already gone, so
                  // dropping the text here would lose it silently.
                  replaceSteerChip(conversationId, localId, null);
                  if (
                    !originStillVisible ||
                    isSubmittingRef.current ||
                    sendNow(trimmed, files ?? [], fallbackContext) === false
                  ) {
                    restoreRejectedSteer();
                  }
                  return;
                }
                if (
                  code === 'RUN_PAUSED' ||
                  code === 'STEER_UNSUPPORTED' ||
                  code === 'STEER_QUEUE_FULL'
                ) {
                  replaceSteerChip(conversationId, localId, null);
                  // The rejection can land AFTER the final SSE consumed the
                  // run-end signal (common on an unsupported SDK near run end):
                  // queueing then has nothing left to drain it, so mirror the
                  // NO_ACTIVE_RUN fallback and send once submission settled —
                  // queueing the refusal instead of dropping the text.
                  if (originStillVisible && !isSubmittingRef.current) {
                    if (sendNow(trimmed, files ?? [], fallbackContext) === false) {
                      restoreRejectedSteer();
                    }
                    return;
                  }
                  restoreRejectedSteer();
                  showToast({
                    message: localize('com_ui_steer_paused_queued'),
                    status: 'info',
                  });
                  return;
                }
                const errorData = (
                  error as {
                    response?: {
                      data?: { generationProtocolVersion?: unknown };
                    };
                  }
                )?.response?.data;
                if (
                  code === 'RUN_REPLACED' &&
                  targetGenerationProtocolVersion === 2 &&
                  supportsGenerationProtocolV2(errorData)
                ) {
                  /** A different live generation now owns this conversation. A
                   * normal-send fallback would replace that newer run (especially
                   * from a stale tab), so retain the instruction for its run-end
                   * drain regardless of this tab's local submission state. */
                  replaceSteerChip(conversationId, localId, null);
                  restoreRejectedSteer();
                  showToast({
                    message: localize('com_ui_steer_paused_queued'),
                    status: 'info',
                  });
                  return;
                }
                if (isDefiniteSteerRejection(error)) {
                  // A concrete origin 4xx proves the steer was rejected. Keep the
                  // ordinary failed controls (edit/queue/remove/retry) instead of
                  // the locked "delivery unknown" surface reserved for transport
                  // and 5xx ambiguity.
                  upsertSteerChip(conversationId, {
                    steerId: localId,
                    text: trimmed,
                    status: 'failed',
                    createdAt,
                    ...(files && { files }),
                    ...(preempt && { preempt: true }),
                    ...(targetGenerationCreatedAt != null && {
                      generationCreatedAt: targetGenerationCreatedAt,
                    }),
                    generationProtocolVersion: targetGenerationProtocolVersion,
                    ...(opts?.queuedOrigin && {
                      queuedOrigin: opts.queuedOrigin,
                    }),
                    ...carried,
                  });
                  return;
                }
                upsertSteerChip(conversationId, {
                  steerId: localId,
                  text: trimmed,
                  status: 'failed',
                  deliveryUncertain: true,
                  createdAt,
                  ...(files && { files }),
                  ...(preempt && { preempt: true }),
                  ...(targetGenerationCreatedAt != null && {
                    generationCreatedAt: targetGenerationCreatedAt,
                  }),
                  generationProtocolVersion: targetGenerationProtocolVersion,
                  ...(opts?.queuedOrigin && {
                    queuedOrigin: opts.queuedOrigin,
                  }),
                  ...carried,
                });
              } finally {
                settleDispatch();
              }
            },
          },
        );
      });
      return true;
    },
    [
      hasRealConvoId,
      conversationId,
      upsertSteerChip,
      replaceSteerChip,
      acknowledgeSteer,
      settleReceiptReplay,
      queueRecoveredSteer,
      reclaimRejectedChipQuotes,
      steerMessage,
      sendNow,
      enqueue,
      restoreQueued,
      rearmDrain,
      registerQueuedOrigin,
      isSteerAcceptedOrSettled,
      showToast,
      localize,
      activeGenerationCreatedAt,
      activeGenerationProtocolVersion,
      scheduleSteerDispatch,
    ],
  );

  /** Composer-originated steer: consumes the composer's attachments and quote
   *  chips so they ride the steer as one unit (the server re-fetches + encodes
   *  files and merges quotes at the injection boundary). Both are taken only
   *  after the guards pass — with `canSteer` true, `submitSteer` cannot
   *  refuse, so the drained context can never be stranded. */
  const steerFromComposer = useCallback(
    (text: string, preempt = false): boolean => {
      const trimmed = text.trim();
      if (trimmed.length === 0 || filesLoading || !canSteer) {
        return false;
      }
      const consumed = submitSteer(trimmed, takeComposerFiles(), takeComposerQuotes(), {
        preempt,
      });
      if (consumed) {
        takeComposerDraft();
      }
      return consumed;
    },
    [filesLoading, canSteer, takeComposerFiles, takeComposerQuotes, takeComposerDraft, submitSteer],
  );

  /** Composer-originated queue: carries the composer's attachments, quote
   *  chips, and manual skill picks as one unit. */
  const queueFromComposer = useCallback(
    (text: string): boolean => {
      const trimmed = text.trim();
      if (trimmed.length === 0 || filesLoading) {
        return false;
      }
      enqueue(trimmed, {
        files: takeComposerFiles(),
        ...takeComposerContext(),
      });
      takeComposerDraft();
      return true;
    },
    [filesLoading, enqueue, takeComposerFiles, takeComposerContext, takeComposerDraft],
  );

  /** Retry a failed chip through the normal steer path. */
  const retrySteer = useCallback(
    (
      steerId: string,
      text: string,
      steerFiles?: TMessage['files'],
      context?: QueuedMessageContext,
      opts?: SubmitSteerOptions,
    ) => {
      /** A failed interrupt-steer must retry AS an interrupt — resubmitting it
       *  as an ordinary steer would silently let generation run on. */
      submitSteer(text, steerFiles, context, {
        ...opts,
        clientSteerId: steerId,
      });
    },
    [submitSteer],
  );

  const removeSteer = useCallback(
    (steerId: string) => {
      replaceSteerChip(conversationId, steerId, null);
    },
    [conversationId, replaceSteerChip],
  );

  /**
   * Re-homes a steer the client just reclaimed from the server queue (see
   * `useSteerReclaim`) as a queued follow-up.
   *
   * Routed through the shared conversion rather than `enqueue` so it obeys the
   * same invariant as the leftover-steer path: the item keeps its ORIGINAL id
   * and `createdAt`, so a steer accepted before a later follow-up still drains
   * ahead of it — a fresh `Date.now()` would sort it last.
   *
   * The reclaim is a round-trip, so the run can end while it is in flight and
   * the drain can consume its one-shot run-end signal against an empty queue,
   * leaving nothing to auto-send this item. Rather than send it here, re-post
   * that spent signal so `useQueueDrain` runs again and decides: it owns the
   * completed-only rule, FIFO order, `NEW_CONVO` migration, and submitting via
   * `ask` (which, unlike the composer's `sendNow`, does not reset the form and
   * so cannot wipe a draft typed while the reclaim was in flight).
   *
   * Parked under the conversation rather than the index, so a run that ended
   * while the user was elsewhere still drains when they come back.
   */
  const queueReclaimedSteer = useCallback(
    (steer: PendingSteer) => {
      // A confirmed cancel has no parked server source. Restore one ordinary
      // queue item explicitly (the reclaim tombstone intentionally makes the
      // shared terminal converter ignore late payloads for these ids).
      if (steer.queuedOrigin != null) {
        restoreQueued(steer.queuedOrigin);
      } else {
        enqueue(steer.text, {
          id: steer.steerId,
          createdAt: steer.createdAt,
          files: steer.files,
          ...carriedSteerContext(steer),
          skipUsageMark: true,
        });
      }
      const lastRunEnd = runEndsRef.current.get(conversationId);
      if (lastRunEnd?.outcome === 'completed') {
        rearmDrain(conversationId, lastRunEnd);
      }
    },
    [conversationId, enqueue, rearmDrain, restoreQueued],
  );

  /** Convert a failed/unsent steer chip into a queued follow-up. */
  const convertSteerToQueue = useCallback(
    (
      steerId: string,
      text: string,
      steerFiles?: TMessage['files'],
      context?: QueuedMessageContext,
      queuedOrigin?: QueuedMessageOrigin,
    ) => {
      replaceSteerChip(conversationId, steerId, null);
      if (queuedOrigin != null) {
        restoreQueued(queuedOrigin);
        return;
      }
      enqueue(text, { files: steerFiles, ...context });
    },
    [conversationId, replaceSteerChip, restoreQueued, enqueue],
  );

  /** Chip action: send a queued message into the live run instead. Keys on
   *  steer availability, not the default action — a queue-preferring user
   *  clicking send-now explicitly asked to inject into the live run. The
   *  item's attachments ride the steer; its quotes/skills travel as the
   *  restore context so a degraded steer requeues/sends with them intact.
   *  `preempt` escalates the steer to interrupt at the next safe token
   *  boundary; it only means something on the live-run path. */
  const sendLocalQueuedNow = useCallback(
    (item: QueuedMessage, opts?: { preempt?: boolean }) => {
      /** In answer mode (and any other submission-owned non-steerable state)
       * there is no immediate path. Refuse before touching queue state so a
       * stale/direct caller cannot perform the old remove-and-restore no-op. */
      if (isSubmitting && (!duringRunActive || !canSteer || item.recoverySteerId != null)) {
        return;
      }
      /** UI callers always find the item; a stale/direct caller has no original
       *  neighbours, so restoration falls back to the queue's priority split. */
      const origin = takeQueued(item.id) ?? {
        item,
        beforeIds: [],
        afterIds: [],
      };
      const taken = origin.item;
      if (duringRunActive && canSteer) {
        const consumed = submitSteer(
          taken.text,
          taken.files,
          { quotes: taken.quotes, manualSkills: taken.manualSkills },
          {
            ...(opts?.preempt === true && { preempt: true }),
            queuedOrigin: origin,
          },
        );
        if (!consumed) {
          restoreQueued(origin);
        }
        return;
      }
      if (!isSubmitting) {
        if (idleSendInFlightRef.current) {
          restoreQueued(origin);
          return;
        }
        idleSendInFlightRef.current = true;
        // Explicit (possibly empty) overrides: the queued item is the full
        // submission context, never the composer's staged files/quotes/picks.
        let accepted: false | void;
        try {
          accepted = sendNow(taken.text, taken.files ?? [], {
            quotes: taken.quotes,
            manualSkills: taken.manualSkills,
            clientRequestId: taken.clientRequestId,
            recoverySteerId: taken.recoverySteerId,
            expectedPredecessorCreatedAt: taken.expectedPredecessorCreatedAt,
            queuedMessageOrigin: origin,
          });
        } catch (error) {
          idleSendInFlightRef.current = false;
          restoreQueued(origin);
          throw error;
        }
        if (accepted === false) {
          idleSendInFlightRef.current = false;
          // `ask` refused without sending — restore the chip so the user's
          // text is never silently dropped (mirrors useQueueDrain).
          restoreQueued(origin);
        } else {
          releaseQueuedOrigin(origin);
        }
        return;
      }
      /** The run still owns the send slot but cannot accept a steer (approval
       *  pause/answer transition): put the untouched item back where it was. */
      restoreQueued(origin);
    },
    [
      takeQueued,
      duringRunActive,
      canSteer,
      submitSteer,
      isSubmitting,
      sendNow,
      restoreQueued,
      releaseQueuedOrigin,
    ],
  );

  const queuedActionClaimsRef = useRef(new Set<string>());
  const sendQueuedNow = useCallback(
    (item: QueuedMessage, opts?: { preempt?: boolean }) => {
      if (item.server == null) {
        sendLocalQueuedNow(item, opts);
        return;
      }
      if (queuedActionClaimsRef.current.has(item.id)) {
        return;
      }
      queuedActionClaimsRef.current.add(item.id);
      void discardQueued(item)
        .then((discarded) => {
          if (discarded) {
            sendLocalQueuedNow(item, opts);
          }
        })
        .finally(() => {
          queuedActionClaimsRef.current.delete(item.id);
        });
    },
    [discardQueued, sendLocalQueuedNow],
  );

  /** Abort the current run and auto-send this text once the abort settles. */
  const interruptAndSend = useCallback(
    (text: string): boolean => {
      const trimmed = text.trim();
      if (trimmed.length === 0 || filesLoading || !canControlGeneration) {
        return false;
      }
      enqueue(trimmed, {
        front: true,
        files: takeComposerFiles(),
        ...takeComposerContext(),
      });
      takeComposerDraft();
      armDrainAfterAbort();
      stopGenerating();
      return true;
    },
    [
      filesLoading,
      canControlGeneration,
      enqueue,
      takeComposerFiles,
      takeComposerContext,
      takeComposerDraft,
      armDrainAfterAbort,
      stopGenerating,
    ],
  );

  /**
   * Interrupt & steer: the same POST, queue, chip lifecycle and degradation
   * ladder as an ordinary steer — the only difference is that the server asks
   * the generating replica to seal its model stream at the next
   * provider-safe boundary instead of waiting for a tool step. The partial
   * answer is kept and generation resumes in the same message.
   *
   * Falls back to `interruptAndSend` ONLY before a conversation exists:
   * steering needs a server-side job, so `submitSteer` hard-refuses without a
   * real conversationId, and an always-visible button would otherwise be dead
   * for the entire first turn — exactly when a user most wants to stop a long
   * answer.
   *
   * A run paused on tool approval refuses outright instead. `canSteer` is
   * false there too, but routing that into `interruptAndSend` would hard-abort
   * the run and discard the partial answer — the exact opposite of what this
   * action promises. The standalone button is disabled while paused; the
   * keyboard and hovercard paths reach here, so the guard lives here.
   */
  const interruptSteer = useCallback(
    (text: string): boolean => {
      const trimmed = text.trim();
      if (trimmed.length === 0 || filesLoading || pausedOnApproval || !canControlGeneration) {
        return false;
      }
      if (!hasRealConvoId) {
        return interruptAndSend(trimmed);
      }
      const consumed = submitSteer(trimmed, takeComposerFiles(), takeComposerQuotes(), {
        preempt: true,
      });
      if (consumed) {
        takeComposerDraft();
      }
      return consumed;
    },
    [
      filesLoading,
      pausedOnApproval,
      canControlGeneration,
      hasRealConvoId,
      interruptAndSend,
      takeComposerFiles,
      takeComposerQuotes,
      takeComposerDraft,
      submitSteer,
    ],
  );

  /** Routes a during-run submit to the effective action. Returns true when consumed. */
  const submitDuringRun = useCallback(
    (text: string): boolean => {
      if (!duringRunActive) {
        return false;
      }
      if (effectiveAction === 'steer') {
        /** Only the DEFAULT route honours the preference — the explicit Steer
         *  row and the Ctrl/Cmd+Enter alternate stay non-preempting, or they
         *  would become indistinguishable from Interrupt & steer. */
        return steerFromComposer(text, steerInterruptsByDefault);
      }
      return queueFromComposer(text);
    },
    [
      duringRunActive,
      effectiveAction,
      steerInterruptsByDefault,
      steerFromComposer,
      queueFromComposer,
    ],
  );

  /** Memoized so consumers like `memo(PendingSteerChips)` can bail on the
   * `steering` prop; a fresh literal here would defeat them every render. */
  return useMemo(
    () => ({
      enabled,
      queueKey,
      canSteer,
      canControlGeneration,
      duringRunActive,
      canSendQueuedNow,
      effectiveAction,
      defaultAction,
      pausedOnApproval,
      setDefaultAction,
      submitDuringRun,
      steerFromComposer,
      queueFromComposer,
      submitSteer,
      retrySteer,
      removeSteer,
      convertSteerToQueue,
      queueReclaimedSteer,
      enqueue,
      removeQueued,
      discardQueued,
      sendQueuedNow,
      interruptAndSend,
      interruptSteer,
    }),
    [
      enabled,
      queueKey,
      canSteer,
      canControlGeneration,
      duringRunActive,
      canSendQueuedNow,
      effectiveAction,
      defaultAction,
      pausedOnApproval,
      setDefaultAction,
      submitDuringRun,
      steerFromComposer,
      queueFromComposer,
      submitSteer,
      retrySteer,
      removeSteer,
      convertSteerToQueue,
      queueReclaimedSteer,
      enqueue,
      removeQueued,
      discardQueued,
      sendQueuedNow,
      interruptAndSend,
      interruptSteer,
    ],
  );
}

export type SteeringControls = ReturnType<typeof useSteering>;
