# PersistentVolumeClaim (PVC): Requests storage from the cluster
# This ensures data persists even if pods are deleted/restarted
---
# MongoDB data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: librechat
spec:
  # storageClassName: manual  <-- REMOVED: Let OVH choose the default class (usually csi-cinder-high-speed)
  # volumeName: mongodb-pv    <-- REMOVED: No manual binding
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Meilisearch data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: librechat
spec:
  # storageClassName: manual
  # volumeName: meilisearch-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Vector database storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-data
  namespace: librechat
spec:
  # storageClassName: manual
  # volumeName: vectordb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# LibreChat uploads and logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-uploads
  namespace: librechat
spec:
  # storageClassName: manual
  # volumeName: librechat-uploads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
