# Meilisearch: Fast search engine for LibreChat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.13.2
        ports:
        - containerPort: 7700
        env:
        - name: MEILI_NO_ANALYTICS
          value: "true"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: MEILI_MASTER_KEY
        - name: MEILI_ENV
          value: "production"
        volumeMounts:
        - name: meilisearch-storage
          mountPath: /meili_data  # Meilisearch data directory
          subPath: meilisearch  # Fix for cloud storage lost+found
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"  # Reduced for single node
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: meilisearch-storage
        persistentVolumeClaim:
          claimName: meilisearch-data

---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: librechat
spec:
  selector:
    app: meilisearch
  ports:
  - port: 7700
    targetPort: 7700
  type: ClusterIP
