# Vector Database: Stores embeddings for RAG (Retrieval Augmented Generation)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectordb
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
      - name: vectordb
        image: ankane/pgvector:latest  # PostgreSQL with vector extension
        ports:
        - containerPort: 5432
        env:
        # Load credentials from secrets (SECURE)
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_PASSWORD
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: RAG_OPENAI_API_KEY
        volumeMounts:
        - name: vectordb-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres  # Fix for lost+found error on cloud storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"  # Reduced for single node
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: vectordb-storage
        persistentVolumeClaim:
          claimName: vectordb-data

---
apiVersion: v1
kind: Service
metadata:
  name: vectordb
  namespace: librechat
spec:
  selector:
    app: vectordb
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---
# RAG API: Handles document retrieval and embeddings
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
      - name: rag-api
        image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "vectordb"
        - name: RAG_PORT
          value: "8000"
        - name: COLLECTION_NAME
          value: "testcollection"
        - name: EMBEDDING_MODEL
          value: "sentence-transformers/all-MiniLM-L6-v2"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: RAG_OPENAI_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"  # Reduced for single node
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: librechat
spec:
  selector:
    app: rag-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
