# LiteLLM: Proxy for multiple AI model providers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        args: ["--config", "/app/config.yaml", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: LITELLM_MASTER_KEY
        - name: LITELLM_SALT_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: LITELLM_SALT_KEY
        # Load PostgreSQL credentials
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: POSTGRES_DB
        # Build DATABASE_URL with variables
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@vectordb:5432/$(POSTGRES_DB)"
        - name: STORE_MODEL_IN_DB
          value: "true"
        # Mount litellm config file (create ConfigMap for this)
        volumeMounts:
        - name: litellm-config
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "512Mi"
            cpu: "150m"  # Reduced for single node
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: litellm-config
        configMap:
          name: litellm-config  # We'll create this next

---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: librechat
spec:
  selector:
    app: litellm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # Internal only, exposed via Ingress

---
# ConfigMap for LiteLLM configuration file
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: librechat
data:
  config.yaml: |
    # LiteLLM configuration
    # Add your model configurations here
    model_list:
      - model_name: gpt-4
        litellm_params:
          model: openai/gpt-4
          api_key: ${OPENAI_API_KEY}
