# Models Watcher: Automatically restarts LibreChat when LiteLLM models change
---
# 1. ConfigMap for the script
apiVersion: v1
kind: ConfigMap
metadata:
  name: models-watcher-script
  namespace: librechat
data:
  watch_models.sh: |
    #!/bin/sh
    set -eu

    AUTH_HEADER="Authorization: Bearer ${LITELLM_MASTER_KEY:-}"
    LITELLM_MODELS_URL="${LITELLM_MODELS_URL:-http://litellm:8000/v1/models}"
    CHECK_EVERY="${CHECK_EVERY:-15}"
    NAMESPACE="${NAMESPACE:-librechat}"
    DEPLOYMENT="${DEPLOYMENT:-librechat-api}"

    # Install dependencies
    apk add --no-cache curl kubectl

    hash_models() {
      curl -sf -H "$AUTH_HEADER" "$LITELLM_MODELS_URL" | sha256sum | awk '{print $1}'
    }

    restart_deployment() {
      echo "🔄 Restarting deployment $DEPLOYMENT in namespace $NAMESPACE..."
      kubectl rollout restart deployment/"$DEPLOYMENT" -n "$NAMESPACE"
    }

    echo "⏳ Waiting for LiteLLM models endpoint at $LITELLM_MODELS_URL..."
    until current="$(hash_models)"; do
      echo "Waiting for LiteLLM..."
      sleep 5
    done
    last="$current"
    echo "✅ Initial models hash: $last"
    echo "👀 Watching for changes every $CHECK_EVERY seconds..."

    while true; do
      sleep "$CHECK_EVERY"
      if current="$(hash_models)"; then
        if [ "$current" != "$last" ]; then
          echo "🚨 Models changed ($last -> $current). Triggering restart..."
          restart_deployment || echo "❌ Restart failed."
          last="$current"
        fi
      else
        echo "⚠️ Could not reach models endpoint; will retry."
      fi
    done

---
# 2. ServiceAccount (Identity for the pod)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: models-watcher-sa
  namespace: librechat

---
# 3. Role (Permissions to restart deployments)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restarter
  namespace: librechat
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "patch", "list", "watch"]

---
# 4. RoleBinding (Connect ServiceAccount to Role)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: models-watcher-binding
  namespace: librechat
subjects:
- kind: ServiceAccount
  name: models-watcher-sa
  namespace: librechat
roleRef:
  kind: Role
  name: deployment-restarter
  apiGroup: rbac.authorization.k8s.io

---
# 5. Deployment (The actual watcher pod)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-watcher
  namespace: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models-watcher
  template:
    metadata:
      labels:
        app: models-watcher
    spec:
      serviceAccountName: models-watcher-sa
      containers:
      - name: watcher
        image: alpine:3.20
        command: ["/bin/sh", "/scripts/watch_models.sh"]
        env:
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: LITELLM_MASTER_KEY
        - name: LITELLM_MODELS_URL
          value: "http://litellm:8000/v1/models"
        - name: CHECK_EVERY
          value: "15"
        - name: NAMESPACE
          value: "librechat"
        - name: DEPLOYMENT
          value: "librechat-api"
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: script-volume
        configMap:
          name: models-watcher-script
          defaultMode: 0755
