# LibreChat API: Your custom image with the application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat-api
  namespace: librechat
spec:
  replicas: 1  # Run 1 copy (reduced for memory constraints)
  selector:
    matchLabels:
      app: librechat-api
  template:
    metadata:
      labels:
        app: librechat-api
    spec:
      # Init container mimics wait_for_litellm from docker-compose
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
      - name: wait-for-litellm
        image: curlimages/curl:8.9.1
        command:
        - sh
        - -c
        - |
          echo "Waiting for LiteLLM at http://litellm:8000/v1/models ..."
          until curl -sf -H "Authorization: Bearer $(LITELLM_MASTER_KEY)" http://litellm:8000/v1/models >/dev/null 2>&1; do
            echo "LiteLLM not ready, waiting..."
            sleep 2
          done
          echo "LiteLLM is ready."
        env:
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-secrets
              key: LITELLM_MASTER_KEY
      containers:
      - name: api
        image: fekihatelm/librechat-custom:latest  # Your custom image!
        imagePullPolicy: IfNotPresent  # Use local image if available
        command: ["node", "api/server/index.js"]
        ports:
        - containerPort: 3080
        # Load all ConfigMap values as environment variables
        envFrom:
        - configMapRef:
            name: librechat-config
        - secretRef:
            name: librechat-secrets
        env:
        # Build MongoDB URI with injected variables - uses LIBRECHAT_DB_USER like docker-compose
        - name: MONGO_URI
          value: "mongodb://$(MONGO_ROOT_USER):$(MONGO_ROOT_PASS)@mongodb:27017/LibreChat?authSource=admin"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@vectordb:5432/$(POSTGRES_DB)"
        # Mount volumes for uploads, logs, images and config
        volumeMounts:
        - name: data-volume
          mountPath: /app/uploads
          subPath: uploads
        - name: data-volume
          mountPath: /app/api/logs
          subPath: logs
        - name: data-volume
          mountPath: /app/client/public/images
          subPath: images
        - name: librechat-config-file
          mountPath: /app/librechat.yaml
          subPath: librechat.yaml
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"  # Reduced for single node
          limits:
            memory: "4Gi"
            cpu: "2000m"
        # Health checks
        livenessProbe:  # Restart if unhealthy
          httpGet:
            path: /
            port: 3080
          initialDelaySeconds: 60  # Wait 60s before first check
          periodSeconds: 10         # Check every 10s
        readinessProbe:  # Don't send traffic until ready
          httpGet:
            path: /
            port: 3080
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: librechat-uploads
      - name: librechat-config-file
        configMap:
          name: librechat-yaml  # Create this ConfigMap with your librechat.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: librechat-api
  namespace: librechat
spec:
  selector:
    app: librechat-api
  ports:
  - port: 3080
    targetPort: 3080
  type: ClusterIP  # Internal only, NGINX will be the entry point
