import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

/**
 * The shared hashing rule behind `generate-baml.mjs` (which writes the stamp) and
 * `verify-baml-generated.mjs` (which checks it without the CLI installed). One
 * definition, so a build cannot disagree with the generator about what "fresh"
 * means.
 */

export const BAML_TOOLCHAIN_VERSION = '0.15.0';
export const PACKAGE_ROOT = path.resolve(import.meta.dirname, '..');
export const SOURCE_DIR = path.join(PACKAGE_ROOT, 'baml_src');
export const GENERATED_DIR = path.join(PACKAGE_ROOT, 'src/baml/generated');
export const FINGERPRINT_FILE = path.join(PACKAGE_ROOT, 'baml.generated.sha256');

const filesUnder = (dir, prefix = '') => {
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const relative = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(...filesUnder(path.join(dir, entry.name), relative));
      continue;
    }
    found.push(relative);
  }
  return found;
};

/** Path-sorted so the hash is stable across filesystems and checkout order. */
export const hashTree = (dir) => {
  const hash = createHash('sha256');
  for (const relative of filesUnder(dir).sort()) {
    hash.update(relative);
    hash.update('\0');
    hash.update(readFileSync(path.join(dir, relative)));
    hash.update('\0');
  }
  return hash.digest('hex');
};

export const currentFingerprint = () => ({
  toolchain: BAML_TOOLCHAIN_VERSION,
  source: hashTree(SOURCE_DIR),
  generated: hashTree(GENERATED_DIR),
});

export const renderFingerprint = ({ toolchain, source, generated }) =>
  [
    '# Generated by packages/api/scripts/generate-baml.mjs — do not edit by hand.',
    `toolchain ${toolchain}`,
    `baml_src ${source}`,
    `src/baml/generated ${generated}`,
    '',
  ].join('\n');

export const parseFingerprint = (text) => {
  const parsed = { toolchain: '', source: '', generated: '' };
  for (const line of text.split('\n')) {
    const [key, value] = line.trim().split(/\s+/);
    if (key === 'toolchain') parsed.toolchain = value ?? '';
    if (key === 'baml_src') parsed.source = value ?? '';
    if (key === 'src/baml/generated') parsed.generated = value ?? '';
  }
  return parsed;
};

export const exists = (target) => {
  try {
    return statSync(target) != null;
  } catch {
    return false;
  }
};
