import { readFileSync } from 'node:fs';
import path from 'node:path';
import { GENERATED_DIR } from './bamlFingerprint.mjs';

const BYTECODE_DECLARATION = 'export const BYTECODE = new Uint8Array([';
const BYTES_PER_ROW = 24;
const MAX_SOURCE_PATH_BYTES = 4096;

/**
 * Serialization-only source root. It intentionally matches the Closure A
 * artifact, so normalizing generated bytecode does not churn the committed SDK.
 * The path need not exist where the SDK is built or executed.
 */
export const CANONICAL_BAML_SOURCE_ROOT = '/home/maceo/Dev/silmari-chat/packages/api/baml_src';
export const INLINED_BYTECODE_FILE = path.join(GENERATED_DIR, 'baml_sdk', '_inlinedbaml.ts');

const bytecodeBounds = (text) => {
  const declaration = text.indexOf(BYTECODE_DECLARATION);
  if (declaration < 0) {
    throw new Error(`Missing ${BYTECODE_DECLARATION}`);
  }
  const bodyStart = declaration + BYTECODE_DECLARATION.length;
  const bodyEnd = text.indexOf(']);', bodyStart);
  if (bodyEnd < 0) {
    throw new Error('BAML bytecode array is not terminated.');
  }
  return { bodyEnd, bodyStart };
};

export const decodeBytecodeModule = (text) => {
  const { bodyEnd, bodyStart } = bytecodeBounds(text);
  const body = text.slice(bodyStart, bodyEnd);
  if (body.replace(/[\d,\s]/g, '') !== '') {
    throw new Error('BAML bytecode array contains an unexpected token.');
  }
  const values = Array.from(body.matchAll(/\d+/g), (match) => Number(match[0]));
  if (values.some((value) => !Number.isInteger(value) || value < 0 || value > 255)) {
    throw new Error('BAML bytecode array contains a value outside 0..255.');
  }
  return { bodyEnd, bodyStart, bytes: Buffer.from(values) };
};

const renderBytecodeModule = (text, bytes) => {
  const { bodyEnd, bodyStart } = bytecodeBounds(text);
  const rows = [];
  for (let index = 0; index < bytes.length; index += BYTES_PER_ROW) {
    rows.push(`  ${[...bytes.subarray(index, index + BYTES_PER_ROW)].join(', ')}, `);
  }
  return `${text.slice(0, bodyStart)}\n${rows.join('\n')}\n${text.slice(bodyEnd)}`;
};

const embeddedBamlSourcePathEntries = (bytes) => {
  const found = [];
  for (let prefixOffset = 0; prefixOffset <= bytes.length - 4; prefixOffset += 1) {
    const length = bytes.readUInt32LE(prefixOffset);
    if (length < 16 || length > MAX_SOURCE_PATH_BYTES) {
      continue;
    }
    const pathOffset = prefixOffset + 4;
    const pathEnd = pathOffset + length;
    if (pathEnd > bytes.length) {
      continue;
    }
    const embedded = bytes.subarray(pathOffset, pathEnd).toString('utf8');
    if (
      /^\/[\x20-\x7e]+\/baml_src\/[\x20-\x7e]+\.baml$/.test(embedded) &&
      Buffer.byteLength(embedded) === length
    ) {
      found.push({ length, path: embedded, pathEnd, pathOffset, prefixOffset });
      prefixOffset = pathEnd - 1;
    }
  }
  return found;
};

export const embeddedBamlSourcePaths = (bytes) =>
  embeddedBamlSourcePathEntries(bytes).map((entry) => entry.path);

export const assertCanonicalBamlSourcePaths = (text) => {
  const { bytes } = decodeBytecodeModule(text);
  const paths = embeddedBamlSourcePaths(bytes);
  if (paths.length === 0) {
    throw new Error('BAML bytecode contains no framed source paths.');
  }
  const nonCanonical = paths.filter(
    (embedded) =>
      embedded !== CANONICAL_BAML_SOURCE_ROOT &&
      !embedded.startsWith(`${CANONICAL_BAML_SOURCE_ROOT}/`),
  );
  if (nonCanonical.length > 0) {
    throw new Error(
      `BAML bytecode contains non-canonical source paths:\n  ${[...new Set(nonCanonical)].join(
        '\n  ',
      )}`,
    );
  }
  return paths;
};

export const normalizeBamlSourcePaths = (text, sourceRoot) => {
  const decoded = decodeBytecodeModule(text);
  const entries = embeddedBamlSourcePathEntries(decoded.bytes);
  if (entries.length === 0) {
    throw new Error('BAML bytecode contains no framed source paths to normalize.');
  }

  const normalizedSourceRoot = path.resolve(sourceRoot).split(path.sep).join('/');
  const chunks = [];
  let cursor = 0;
  let replacements = 0;
  for (const entry of entries) {
    chunks.push(decoded.bytes.subarray(cursor, entry.prefixOffset));
    let normalizedPath = entry.path;
    const isCanonical =
      entry.path === CANONICAL_BAML_SOURCE_ROOT ||
      entry.path.startsWith(`${CANONICAL_BAML_SOURCE_ROOT}/`);
    if (!isCanonical) {
      if (!entry.path.startsWith(`${normalizedSourceRoot}/`)) {
        throw new Error(`Cannot normalize unexpected BAML source path: ${entry.path}`);
      }
      normalizedPath = `${CANONICAL_BAML_SOURCE_ROOT}${entry.path.slice(
        normalizedSourceRoot.length,
      )}`;
      replacements += 1;
    }

    const encoded = Buffer.from(normalizedPath);
    const length = Buffer.alloc(4);
    length.writeUInt32LE(encoded.length);
    chunks.push(length, encoded);
    cursor = entry.pathEnd;
  }
  chunks.push(decoded.bytes.subarray(cursor));

  const normalizedBytes = Buffer.concat(chunks);
  const normalizedText = renderBytecodeModule(text, normalizedBytes);
  const roundTrip = decodeBytecodeModule(normalizedText).bytes;
  if (!roundTrip.equals(normalizedBytes)) {
    throw new Error('Normalized BAML bytecode failed its render/decode round trip.');
  }
  assertCanonicalBamlSourcePaths(normalizedText);
  return { replacements, text: normalizedText };
};

export const assertCanonicalGeneratedBamlSourcePaths = () =>
  assertCanonicalBamlSourcePaths(readFileSync(INLINED_BYTECODE_FILE, 'utf8'));
