import type { BamlCallContext } from '@boundaryml/baml-bridge';
import type { TurnPlan, TurnPlan$stream } from './generated/baml_sdk/host/index.js';
import type { Stream } from './generated/baml_sdk/baml/llm/index.js';
import { host } from './generated/baml_sdk/index.js';

/**
 * The exact compiled-client registry.
 *
 * Imported ONLY by `worker.mts`. Reaching it initializes the generated bytecode
 * and resolves `@boundaryml/baml-bridge`, so any other importer would defeat the
 * lazy boundary and make an ordinary non-BAML boot load the native runtime.
 *
 * Keys are the persisted logical client names, matched exactly: no default
 * entry, no case folding, no fuzzy lookup. A miss is a turn-level failure value,
 * never a fallback to another client.
 */

/**
 * The generated `$opts` type declares only `client`, but the bridge recognizes
 * `$ctx` as well and it is the ONLY way an `AbortSignal` reaches BAML — a plain
 * `signal` option throws `unknown optional argument`. Declaring the option shape
 * here keeps that single cast at the registry boundary instead of at every call.
 */
export interface GeneratedCallOptions {
  $ctx?: BamlCallContext;
}

export type GeneratedTakeTurn = (
  userMessage: string,
  transcript: string,
  allowedTools: string[],
  options?: GeneratedCallOptions,
) => Promise<TurnPlan>;

export type GeneratedStreamTurn = (
  userMessage: string,
  transcript: string,
  allowedTools: string[],
  options?: GeneratedCallOptions,
) => Promise<Stream<TurnPlan$stream | null, TurnPlan>>;

export interface CompiledBamlClient {
  readonly take: GeneratedTakeTurn;
  readonly stream: GeneratedStreamTurn;
}

const compiled = (take: unknown, stream: unknown): CompiledBamlClient =>
  Object.freeze({ take: take as GeneratedTakeTurn, stream: stream as GeneratedStreamTurn });

export const compiledClients: ReadonlyMap<string, CompiledBamlClient> = new Map([
  ['OpenRouter', compiled(host.HostTurnOpenRouter_async, host.HostTurnOpenRouter$stream_async)],
  [
    'OpenRouterFast',
    compiled(host.HostTurnOpenRouterFast_async, host.HostTurnOpenRouterFast$stream_async),
  ],
]);

/**
 * Runs once on worker initialization. A registry whose entries are not callable
 * would fail at request time, on the user's turn, with a native error; failing
 * here turns that into a startup fault the deployment can see.
 */
export const assertManifestIsCallable = (): void => {
  const seen = new Set<string>();
  for (const [name, entry] of compiledClients) {
    if (seen.has(name)) {
      throw new Error(`Duplicate compiled BAML client: ${name}`);
    }
    seen.add(name);
    if (typeof entry.take !== 'function' || typeof entry.stream !== 'function') {
      throw new Error(`Compiled BAML client ${name} is missing a callable entrypoint`);
    }
  }
};
