import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  ABORT_MESSAGE,
  BAML_WORKER_ABORT_GRACE_MS,
  MAX_TRANSCRIPT_ENTRIES,
  PORT_VERSION_MESSAGE,
  TRANSCRIPT_TOO_LARGE_MESSAGE,
  TRANSPORT_FAILED_MESSAGE,
  TRANSPORT_TIMEOUT_MESSAGE,
  UNCOMPILED_CLIENT_MESSAGE,
  unboundToolMessage,
} from './protocol';

/**
 * TS/subprocess harness for Behaviors 4.1, 4.3, 4.4 of the BAML adapter port.
 *
 * `runtime.mts` cannot be imported by Jest at all: the project's transform does
 * not handle `.mts`, and even if it did, the file expects to be loaded as real
 * ESM at a real `import.meta.url`, spawning a REAL `node:worker_threads` worker
 * that itself imports `@boundaryml/baml-bridge` and generated bytecode — none of
 * which Jest's Node/CJS test environment can host in-process. Closure A already
 * proved this same constraint means driving it as a standalone Node script, not
 * a Jest suite (`runtime.acceptance.mjs`).
 *
 * This suite keeps the assertions in TypeScript/Jest (readable failures, `expect`
 * matchers, `describe`/`it` grouping) while the actual execution happens in a
 * plain Node child process (`__fixtures__/runtimeScenario.mjs`) that imports the
 * BUILT `dist/baml/runtime.mjs` against a real loopback OpenAI-wire fixture and a
 * real single-use worker — exactly the artifact the package ships, exactly like
 * Closure A, just organized as individually named, narrowly-scoped behaviors
 * instead of one linear script.
 *
 * Requires `npm run build` to have produced `dist/baml/runtime.mjs` first, the
 * same precondition `npm run test:baml-runtime` (Closure A) already has.
 *
 * Timer interception, not a fake clock: `runtimeScenario.mjs` injects a
 * `BamlTimers` implementation that wraps the REAL `setTimeout` and additionally
 * fires a synchronous hook on every registration. Each call in that sequence was
 * empirically confirmed (see the scenario driver's header comment) to correspond
 * to a specific transition — operation start, pending pull, after the first
 * chunk, the finalizing boundary — which is what makes "abort right when X
 * happens" deterministic without racing real HTTP timing for the tricky cases.
 * Real, deliberately slow fixture delays are what prove a fast settlement is
 * genuine interruption rather than an accident of scheduling: every abort
 * scenario here configures a fixture whose UNINTERRUPTED duration is far longer
 * than the elapsed-time bound the assertions allow.
 */

const DRIVER = path.join(__dirname, '__fixtures__', 'runtimeScenario.mjs');

interface ScenarioChunk {
  readonly kind: string;
  readonly text?: string;
  readonly failure?: {
    readonly code: string;
    readonly message: string;
    readonly toolName?: string;
  };
}

interface ScenarioResult {
  readonly ok: boolean;
  readonly outcome?: 'resolved' | 'rejected' | 'yieldedFailure';
  readonly errorName?: string | null;
  readonly errorMessage?: string | null;
  readonly value?: {
    readonly kind: string;
    readonly text?: string;
    readonly calls?: ReadonlyArray<{ readonly name: string; readonly args: unknown }>;
    readonly failures?: ReadonlyArray<{
      readonly code: string;
      readonly message: string;
      readonly toolName?: string;
    }>;
    readonly failure?: { readonly code: string; readonly message: string };
  };
  readonly chunks?: readonly ScenarioChunk[];
  readonly elapsedMs?: number;
  readonly providerRequestCount?: number;
  readonly providerRequests?: ReadonlyArray<{
    readonly model?: string;
    readonly stream?: boolean;
    readonly prompt?: string;
    readonly aborted?: boolean;
  }>;
  readonly providerLastRequestAborted?: boolean | null;
  readonly diagnostics?: ReadonlyArray<{
    readonly clientName: string;
    readonly stage: string;
    readonly detail: string;
  }>;
  readonly setTimeoutLog?: readonly number[];
  readonly error?: string;
  readonly workerConstructed?: boolean;
}

/** JSON scenario config understood by `__fixtures__/runtimeScenario.mjs`. See its header for the full shape. */
type Scenario = Record<string, unknown>;

const runScenario = (scenario: Scenario): ScenarioResult => {
  const dir = mkdtempSync(path.join(tmpdir(), 'baml-runtime-spec-'));
  const file = path.join(dir, 'scenario.json');
  writeFileSync(file, JSON.stringify(scenario));
  try {
    const timeoutMs = typeof scenario.timeoutMs === 'number' ? scenario.timeoutMs : 20_000;
    const stdout = execFileSync(process.execPath, [DRIVER, file], {
      encoding: 'utf8',
      timeout: timeoutMs + 5_000,
    });
    const line = stdout.split('\n').find((entry) => entry.startsWith('RESULT_JSON:'));
    if (line == null) {
      throw new Error(`scenario driver produced no RESULT_JSON line, stdout was:\n${stdout}`);
    }
    return JSON.parse(line.slice('RESULT_JSON:'.length)) as ScenarioResult;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};

/**
 * No stack, path, environment name/value, credential, native constructor,
 * `$new`, or bridge internal may ever reach a PUBLIC message. The driver's own
 * scenarios prove native diagnostic text really does contain some of these
 * (see the retry-exhaustion scenario's `diagnostics[0].detail`, which is a real
 * absolute `baml_src` file path) — this asserts the public channel stays clean
 * even when the native channel is not.
 */
const FORBIDDEN_MESSAGE_PATTERNS: readonly RegExp[] = [
  /\/home\//,
  /\/Users\//,
  /node_modules/,
  /baml_src/,
  /\.rs[":]/,
  /panic/i,
  /credential/i,
  /api[_-]?key/i,
  /\$new/,
  /at .*:\d+:\d+/,
  /baml\.errors\./,
];

const assertPublicMessageIsSanitized = (message: string | null | undefined): void => {
  expect(typeof message).toBe('string');
  for (const pattern of FORBIDDEN_MESSAGE_PATTERNS) {
    expect(message).not.toMatch(pattern);
  }
};

const CALL_SCENARIO = (overrides: Scenario = {}): Scenario => ({
  clientName: 'OpenRouter',
  mode: 'call',
  input: { text: 'weather in Paris?' },
  provider: { kind: 'answer', reply: 'sunny' },
  ...overrides,
});

const STREAM_SCENARIO = (overrides: Scenario = {}): Scenario => ({
  clientName: 'OpenRouter',
  mode: 'stream',
  input: { text: 'weather in Paris?' },
  provider: { pieces: [{ text: JSON.stringify({ reply: 'sunny', tools: [] }), delayMs: 5 }] },
  ...overrides,
});

describe('Behavior 4.1 — exact port input and failure semantics', () => {
  it('threads the transcript into the declared worker/BAML arguments via the shared prompt, and returns no fabricated metadata', () => {
    const result = runScenario(
      CALL_SCENARIO({ input: { text: 'what is the weather in Paris right now?' } }),
    );

    expect(result.outcome).toBe('resolved');
    expect(result.value).toEqual({ kind: 'answer', text: 'sunny' });
    expect(result.providerRequestCount).toBe(1);
    expect(result.providerRequests?.[0]?.prompt).toContain(
      'what is the weather in Paris right now?',
    );
    // `meta` must never appear: bridge 0.15.0 exposes no verified public call
    // metadata, and the port forbids fabricating it.
    expect(result.value).not.toHaveProperty('meta');
  });

  it('maps a tool the model selected outside the current allowed-tool subset to an unbound failure, not a dispatch', () => {
    const result = runScenario(
      CALL_SCENARIO({
        input: { text: 'weather in paris', allowedTools: [] },
        provider: { body: { reply: null, tools: [{ tool: 'get_weather', city: 'Paris' }] } },
      }),
    );

    expect(result.outcome).toBe('resolved');
    expect(result.value?.kind).toBe('tool_calls');
    expect(result.value?.calls).toEqual([]);
    expect(result.value?.failures).toEqual([
      { code: 'unbound', message: unboundToolMessage('get_weather'), toolName: 'get_weather' },
    ]);
  });

  it('maps a tool the model selected inside the current allowed-tool subset to a real tool_calls outcome', () => {
    const result = runScenario(
      CALL_SCENARIO({
        input: { text: 'weather in paris', allowedTools: ['get_weather'] },
        provider: { body: { reply: null, tools: [{ tool: 'get_weather', city: 'Paris' }] } },
      }),
    );

    expect(result.value).toEqual({
      kind: 'tool_calls',
      calls: [{ name: 'get_weather', args: { city: 'Paris' } }],
      failures: [],
    });
  });

  it('rejects an unsupported port version as schema_mismatch before any worker or provider request exists', () => {
    const result = runScenario(CALL_SCENARIO({ input: { text: 'x', version: 2 } }));

    expect(result.outcome).toBe('yieldedFailure');
    expect(result.value).toEqual({
      kind: 'failure',
      failure: { code: 'schema_mismatch', message: PORT_VERSION_MESSAGE },
    });
    expect(result.providerRequestCount).toBe(0);
    // Synchronous precheck: no worker was ever created for this to take real time.
    expect(result.elapsedMs).toBeLessThan(50);
    expect(result.workerConstructed).toBe(false);
  });

  it('rejects an oversize transcript as schema_mismatch before any worker exists — call and stream both, with zero worker CONSTRUCTION, not merely zero provider requests', () => {
    const oversizeTranscript = Array.from({ length: MAX_TRANSCRIPT_ENTRIES + 1 }, () => ({
      role: 'system',
      content: '',
    }));

    const callResult = runScenario(
      CALL_SCENARIO({ input: { text: 'x', transcript: oversizeTranscript } }),
    );
    expect(callResult.outcome).toBe('yieldedFailure');
    expect(callResult.value).toEqual({
      kind: 'failure',
      failure: { code: 'schema_mismatch', message: TRANSCRIPT_TOO_LARGE_MESSAGE },
    });
    expect(callResult.providerRequestCount).toBe(0);
    expect(callResult.workerConstructed).toBe(false);

    const streamResult = runScenario(
      STREAM_SCENARIO({ input: { text: 'x', transcript: oversizeTranscript } }),
    );
    expect(streamResult.outcome).toBe('yieldedFailure');
    expect(streamResult.chunks).toEqual([
      {
        kind: 'failure',
        failure: { code: 'schema_mismatch', message: TRANSCRIPT_TOO_LARGE_MESSAGE },
      },
    ]);
    expect(streamResult.providerRequestCount).toBe(0);
    expect(streamResult.workerConstructed).toBe(false);
  });

  it('workerConstructed genuinely reflects real worker creation — an ordinary call constructs exactly one, proving the precheck assertions above are not vacuous', () => {
    const callResult = runScenario(CALL_SCENARIO());
    expect(callResult.outcome).toBe('resolved');
    expect(callResult.workerConstructed).toBe(true);

    const streamResult = runScenario(STREAM_SCENARIO());
    expect(streamResult.outcome).toBe('resolved');
    expect(streamResult.workerConstructed).toBe(true);
  });

  it.each(['NotCompiled', 'openrouter', 'OPENROUTER', '['])(
    'returns model_error for the unresolved client %j before any provider request — call and stream both, and the lookup itself does not throw',
    (clientName) => {
      const callResult = runScenario(
        CALL_SCENARIO({ clientName, provider: { kind: 'answer', reply: 'must not be reached' } }),
      );
      expect(callResult.outcome).toBe('yieldedFailure');
      expect(callResult.value).toEqual({
        kind: 'failure',
        failure: { code: 'model_error', message: UNCOMPILED_CLIENT_MESSAGE },
      });
      expect(callResult.providerRequestCount).toBe(0);

      const streamResult = runScenario(
        STREAM_SCENARIO({ clientName, provider: { kind: 'answer', reply: 'must not be reached' } }),
      );
      expect(streamResult.outcome).toBe('yieldedFailure');
      expect(streamResult.chunks).toEqual([
        { kind: 'failure', failure: { code: 'model_error', message: UNCOMPILED_CLIENT_MESSAGE } },
      ]);
      expect(streamResult.providerRequestCount).toBe(0);
    },
  );

  it('classification precedence: a caller-abort rejection wins over an unresolved-client failure value', () => {
    const result = runScenario(
      CALL_SCENARIO({
        clientName: 'TotallyUnknownClient',
        input: { text: 'x', signal: 'controller' },
        abort: { mode: 'preAborted' },
      }),
    );

    // If unresolved-client precedence had won instead, this would yield a
    // `{kind:'failure', failure:{code:'model_error', ...}}` VALUE, not a
    // rejection — the two are structurally distinguishable, so this is not
    // vacuous against a plausible wrong implementation.
    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('AbortError');
    expect(result.errorMessage).toBe(ABORT_MESSAGE);
    expect(result.providerRequestCount).toBe(0);
  });

  it('classification precedence: an unresolved-client failure value wins over what would otherwise be a transport failure', () => {
    // The fixture is configured to fail every request, but the unknown-client
    // preflight in the worker runs before any request is dispatched, so the
    // configured provider failure is never reached.
    const result = runScenario(
      CALL_SCENARIO({
        clientName: 'TotallyUnknownClient',
        provider: { kind: 'error', status: 500 },
      }),
    );

    expect(result.outcome).toBe('yieldedFailure');
    expect(result.value?.failure?.code).toBe('model_error');
    expect(result.providerRequestCount).toBe(0);
  });

  it('never leaks native error detail — including a real file path — into the public transport error message on retry exhaustion', () => {
    // FastPoolBackoff: max_retries 2 => 3 attempts, all fail => exhausted.
    const result = runScenario(
      CALL_SCENARIO({ clientName: 'OpenRouterFast', provider: { kind: 'error', status: 500 } }),
    );

    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('BamlTransportError');
    expect(result.errorMessage).toBe(TRANSPORT_FAILED_MESSAGE);
    assertPublicMessageIsSanitized(result.errorMessage);
    // The native channel legitimately DOES carry raw detail (for the redacted
    // structured logger only) — proving that is what makes the public-channel
    // assertion above meaningful rather than accidental.
    expect(result.diagnostics?.[0]?.detail ?? '').toEqual(expect.stringContaining('baml_src'));
  });
});

describe('Behavior 4.3 — every abort point stops upstream work', () => {
  it('pre-start: an already-aborted signal rejects synchronously, before any worker or provider request — call and stream both', () => {
    const callResult = runScenario(
      CALL_SCENARIO({ input: { text: 'x', signal: 'controller' }, abort: { mode: 'preAborted' } }),
    );
    expect(callResult.outcome).toBe('rejected');
    expect(callResult.errorName).toBe('AbortError');
    expect(callResult.providerRequestCount).toBe(0);
    expect(callResult.elapsedMs).toBeLessThan(50);

    const streamResult = runScenario(
      STREAM_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        abort: { mode: 'preAborted' },
      }),
    );
    expect(streamResult.outcome).toBe('rejected');
    expect(streamResult.errorName).toBe('AbortError');
    expect(streamResult.providerRequestCount).toBe(0);
    expect(streamResult.elapsedMs).toBeLessThan(50);
  });

  it('pending-pull: aborting while the first pull is in flight stops the operation before the provider ever answers', () => {
    // provider.kind 'hang' never responds at all; only an abort can end this.
    const callResult = runScenario(
      CALL_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        provider: { kind: 'hang' },
        abort: { mode: 'onSetTimeoutCall', atCall: 2 },
      }),
    );
    expect(callResult.outcome).toBe('rejected');
    expect(callResult.errorName).toBe('AbortError');
    expect(callResult.elapsedMs).toBeLessThan(2_000);

    const streamResult = runScenario(
      STREAM_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        provider: { kind: 'hang' },
        abort: { mode: 'onSetTimeoutCall', atCall: 2 },
      }),
    );
    expect(streamResult.outcome).toBe('rejected');
    expect(streamResult.errorName).toBe('AbortError');
    expect(streamResult.chunks).toEqual([]);
    expect(streamResult.elapsedMs).toBeLessThan(2_000);
  });

  it('after-partial: aborting right after the first delivered chunk stops the stream — no later chunk is ever observed', () => {
    // The second piece is deliberately delayed 3s; the consumer aborts the
    // instant it actually has the first chunk in hand (not via the timer-call
    // interception, which fires before delivery — see the driver's comment). A
    // settlement well under that 3s proves the second piece was never awaited,
    // not that it merely arrived quickly.
    const result = runScenario(
      STREAM_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        provider: {
          pieces: [
            { text: JSON.stringify({ reply: 'first part of the answer', tools: [] }), delayMs: 5 },
            {
              text: JSON.stringify({ reply: 'first part of the answer, and more', tools: [] }),
              delayMs: 3_000,
            },
          ],
        },
        abort: { mode: 'afterChunks', atCount: 1 },
      }),
    );

    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('AbortError');
    expect(result.chunks).toEqual([{ kind: 'text', text: 'first part of the answer' }]);
    expect(result.elapsedMs).toBeLessThan(2_000);
  });

  it('finalization boundary: a late abort request never corrupts or duplicates the terminal outcome — exactly one clean result either way', () => {
    // No artificial delay: the stream completes almost immediately once its one
    // piece is sent, so this abort (fired right as finalization begins) races a
    // near-instant natural completion. Both a clean resolve and a clean abort
    // are correct per the port's "exactly one terminal owner" rule; a hang, a
    // crash, or duplicated/partial content would not be.
    const result = runScenario(
      STREAM_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        provider: {
          pieces: [{ text: JSON.stringify({ reply: 'only one piece', tools: [] }), delayMs: 5 }],
        },
        abort: { mode: 'onSetTimeoutCall', atCall: 4 },
      }),
    );

    expect(result.elapsedMs).toBeLessThan(1_000);
    if (result.outcome === 'resolved') {
      expect(result.chunks).toEqual([{ kind: 'text', text: 'only one piece' }]);
    } else {
      expect(result.outcome).toBe('rejected');
      expect(result.errorName).toBe('AbortError');
      expect(result.chunks ?? []).toEqual([]);
    }
  });

  it('early consumer return(): stops upstream work immediately, without waiting for the next chunk', () => {
    // Second piece delayed 5s; the consumer calls `.return()` after the first
    // chunk. A fast settlement is only possible if `.return()` actually tore
    // down the operation instead of the consumer merely losing interest.
    const result = runScenario(
      STREAM_SCENARIO({
        provider: {
          pieces: [
            { text: JSON.stringify({ reply: 'first piece', tools: [] }), delayMs: 5 },
            { text: JSON.stringify({ reply: 'first piece plus more', tools: [] }), delayMs: 5_000 },
          ],
        },
        consumerReturn: { after: 1 },
      }),
    );

    expect(result.outcome).toBe('resolved');
    expect(result.chunks).toEqual([{ kind: 'text', text: 'first piece' }]);
    expect(result.elapsedMs).toBeLessThan(2_000);
  });

  it('every abort scenario above settles within a small, bounded multiple of BAML_WORKER_ABORT_GRACE_MS, not by luck', () => {
    // BAML_WORKER_ABORT_GRACE_MS is 250ms in production. Every abort scenario in
    // this file uses a fixture deliberately configured to take multiple SECONDS
    // if left uninterrupted (hang, or a several-second-delayed next piece), so a
    // sub-2s settlement is only reachable by genuinely stopping upstream work.
    expect(BAML_WORKER_ABORT_GRACE_MS).toBe(250);
  });
});

describe('Behavior 4.4 — retry and operation deadlines coexist', () => {
  it('a fixture that fails within the compiled retry budget still succeeds — the static retry policy is preserved, not overridden', () => {
    // OpenRouterFast: FastPoolBackoff, max_retries 2 => 3 total attempts allowed.
    // Failing exactly twice then succeeding proves retries genuinely happen (a
    // host override of max_retries:0 would fail outright on attempt 1) AND that
    // success mid-budget is not mistaken for still-failing.
    const result = runScenario(
      CALL_SCENARIO({
        clientName: 'OpenRouterFast',
        provider: { kind: 'answer', reply: 'third time lucky', failFirstN: 2 },
      }),
    );

    expect(result.outcome).toBe('resolved');
    expect(result.value).toEqual({ kind: 'answer', text: 'third time lucky' });
    expect(result.providerRequestCount).toBe(3);
  });

  it('a fixture that exhausts the compiled retry budget rejects as the sanitized transport-failed error, distinct from a timeout', () => {
    const result = runScenario(
      CALL_SCENARIO({ clientName: 'OpenRouterFast', provider: { kind: 'error', status: 500 } }),
    );

    expect(result.providerRequestCount).toBe(3);
    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('BamlTransportError');
    expect(result.errorMessage).toBe(TRANSPORT_FAILED_MESSAGE);
    expect(result.errorMessage).not.toBe(TRANSPORT_TIMEOUT_MESSAGE);
  });

  it('an operation deadline that fires rejects as the sanitized TIMEOUT transport error — a distinct code path from a provider failure', () => {
    // provider 'hang' never responds; the injected timer seam force-fires the
    // deadline handler directly instead of waiting the real 120s constant.
    const result = runScenario(
      CALL_SCENARIO({
        provider: { kind: 'hang' },
        deadline: { mode: 'forceOnSetTimeoutCall', atCall: 2 },
      }),
    );

    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('BamlTransportError');
    expect(result.errorMessage).toBe(TRANSPORT_TIMEOUT_MESSAGE);
    expect(result.errorMessage).not.toBe(TRANSPORT_FAILED_MESSAGE);
    assertPublicMessageIsSanitized(result.errorMessage);
  });

  it('caller abort wins its race against a simultaneous operation deadline', () => {
    // Both the abort request and the forced deadline fire from the SAME
    // interception point; the driver's abort check runs before its deadline
    // check, so this proves the terminal-state guard makes the later call a
    // no-op rather than corrupting or double-settling the outcome.
    const result = runScenario(
      CALL_SCENARIO({
        input: { text: 'x', signal: 'controller' },
        provider: { kind: 'hang' },
        abort: { mode: 'onSetTimeoutCall', atCall: 2 },
        deadline: { mode: 'forceOnSetTimeoutCall', atCall: 2 },
      }),
    );

    expect(result.outcome).toBe('rejected');
    expect(result.errorName).toBe('AbortError');
    expect(result.errorMessage).toBe(ABORT_MESSAGE);
  });
});
