import { parentPort } from 'node:worker_threads';
import { BamlCallContext } from '@boundaryml/baml-bridge';
import type { MessagePort } from 'node:worker_threads';
import type { TurnPlan, TurnPlan$stream } from './generated/baml_sdk/host/index.js';
import type {
  StartRequest,
  WireFailure,
  WireRejection,
  WireToolSelection,
  WireTurnPlan,
  WorkerMessage,
  WorkerRequest,
} from './protocol';
import { isAbort, isParseFailure, isTransport, messageOf } from './classify';
import { assertManifestIsCallable, compiledClients } from './manifest';
import {
  MODEL_ERROR_MESSAGE,
  PARSE_ERROR_MESSAGE,
  TRANSPORT_FAILED_MESSAGE,
  UNCOMPILED_CLIENT_MESSAGE,
  toChunkCandidate,
  toWireToolSelection,
} from './protocol';

/**
 * The single-use native worker.
 *
 * This is the only module in the package that touches generated bytecode, and
 * it runs one operation before the parent terminates it. Single-use is not
 * frugality: `next()` and `final()` are BLOCKING pulls that occupy this thread,
 * so a cooperative abort cannot be observed while one is in flight and the
 * parent's only reliable cancellation is `worker.terminate()`. A pooled worker
 * would have to survive that.
 *
 * Nothing native crosses back. Generated class instances are flattened to plain
 * data, and errors become one of a closed set of sanitized wire values.
 */

const port = parentPort;

if (port == null) {
  throw new Error('packages/api/dist/baml/worker.mjs must be started as a worker thread');
}

assertManifestIsCallable();

/**
 * Only ONE operation ever runs here, but the id is still checked on every
 * message: a stale abort for a previous id must not cancel the current call.
 */
let active: { operationId: string; ctx: BamlCallContext } | null = null;

const post = (message: WorkerMessage): void => {
  port.postMessage(message);
};

const failure = (code: WireFailure['code'], message: string, detail?: string): WireFailure =>
  detail == null ? { code, message } : { code, message, detail };

const rejection = (kind: WireRejection['kind'], message: string, detail: string): WireRejection => ({
  kind,
  message,
  detail,
});

/**
 * End of stream, bridge 0.15.0 edition.
 *
 * `next()` is typed `TurnPlan$stream | null`, but an exhausted stream does not
 * return `null` — it returns a partial with every declared field still
 * `undefined`, and it keeps returning one for as long as it is asked. Breaking
 * on `null` alone spins forever and never reaches `final()`; that is what a
 * loopback fixture showed before this guard existed. A live stream blocks inside
 * `next()` instead of answering with an empty partial, including before the
 * first byte of content, so this sentinel cannot end a stream early.
 */
const isExhausted = (snapshot: TurnPlan$stream | null | undefined): boolean => {
  if (snapshot === null || snapshot === undefined) {
    return true;
  }
  const partial = snapshot as unknown as { reply?: unknown; tools?: unknown };
  return partial.reply === undefined && partial.tools === undefined;
};

/**
 * Flattens a generated final `TurnPlan` to plain data. Only used for the fully
 * resolved result of `runCall`/`stream.final()`: BAML's own compiled parse
 * already validated that structure and throws (caught and classified in
 * `start()`) rather than returning something malformed, so a defensive
 * default here is a genuine "no claim" case, not a hidden parse failure. The
 * in-flight streaming partials in `runStream` go through `toChunkCandidate`
 * instead, which does not extend that same trust to an unfinished snapshot.
 */
const toWirePlan = (plan: TurnPlan): WireTurnPlan => {
  const source = plan as unknown as { reply?: unknown; tools?: unknown };
  const reply = typeof source.reply === 'string' ? source.reply : null;
  const tools = Array.isArray(source.tools)
    ? source.tools
        .map(toWireToolSelection)
        .filter((tool): tool is WireToolSelection => tool !== null)
    : [];
  return { reply, tools };
};

const runCall = async (request: StartRequest, ctx: BamlCallContext): Promise<void> => {
  const entry = compiledClients.get(request.clientName);
  if (entry == null) {
    return;
  }
  const { userMessage, transcript, allowedTools } = request.input;
  const plan = await entry.take(userMessage, transcript, [...allowedTools], { $ctx: ctx });
  post({ type: 'final', operationId: request.operationId, plan: toWirePlan(plan) });
};

/**
 * The pulls are the SYNCHRONOUS `next()` / `final()`, not `nextAsync()` /
 * `finalAsync()`: on bridge 0.15.0 the async pair resolves an aborted read with
 * an empty value instead of rejecting and does not reliably deliver
 * pre-final snapshots. Blocking this thread is acceptable precisely because the
 * worker is single-use and the parent can terminate it.
 *
 * `postMessage` does not need this thread's event loop, so snapshots still reach
 * the parent immediately while a pull is blocked.
 */
const runStream = async (request: StartRequest, ctx: BamlCallContext): Promise<void> => {
  const entry = compiledClients.get(request.clientName);
  if (entry == null) {
    return;
  }
  const { userMessage, transcript, allowedTools } = request.input;
  const stream = await entry.stream(userMessage, transcript, [...allowedTools], { $ctx: ctx });

  // Identical snapshots are dropped HERE, not just in the facade's delta rule.
  // A provider whose stream body the parser cannot advance through makes `next()`
  // return the same unchanged partial as fast as the loop can ask: a malformed
  // fixture produced 1.2M of them in a minute. Deduplicating at the source turns
  // that into silence, which is what the parent's idle deadline is built to end.
  let previous = '';

  for (;;) {
    const snapshot = stream.next();
    if (isExhausted(snapshot)) {
      break;
    }
    const raw = snapshot as unknown as { reply?: unknown; tools?: unknown };
    const candidate = toChunkCandidate(raw.reply, raw.tools);
    // A snapshot that fails validation is a genuine model parse failure, not
    // empty text: coercing it to a safe-looking default here would be exactly
    // the bug this function exists to close. One terminal failure, then stop
    // pulling — `stream.final()` below is never reached for this operation.
    if (!candidate.ok) {
      post({
        type: 'failure',
        operationId: request.operationId,
        failure: failure('parse_error', PARSE_ERROR_MESSAGE),
      });
      return;
    }
    const wire = candidate.value;
    const serialized = JSON.stringify(wire);
    if (serialized === previous) {
      continue;
    }
    previous = serialized;
    post({ type: 'chunk', operationId: request.operationId, snapshot: wire });
  }

  post({ type: 'finalizing', operationId: request.operationId });
  post({ type: 'final', operationId: request.operationId, plan: toWirePlan(stream.final()) });
};

const start = async (request: StartRequest): Promise<void> => {
  const { operationId, clientName } = request;

  if (!compiledClients.has(clientName)) {
    post({
      type: 'failure',
      operationId,
      failure: failure('model_error', UNCOMPILED_CLIENT_MESSAGE, `unknown client ${clientName}`),
    });
    return;
  }

  const ctx = new BamlCallContext();
  active = { operationId, ctx };
  post({ type: 'ready', operationId });

  try {
    await (request.mode === 'call' ? runCall(request, ctx) : runStream(request, ctx));
  } catch (error) {
    const detail = messageOf(error);
    if (isAbort(error, ctx.aborted === true)) {
      post({ type: 'rejection', operationId, rejection: rejection('abort', 'aborted', detail) });
      return;
    }
    if (isTransport(error)) {
      post({
        type: 'rejection',
        operationId,
        rejection: rejection('transport', TRANSPORT_FAILED_MESSAGE, detail),
      });
      return;
    }
    post({
      type: 'failure',
      operationId,
      failure: isParseFailure(error)
        ? failure('parse_error', PARSE_ERROR_MESSAGE, detail)
        : failure('model_error', MODEL_ERROR_MESSAGE, detail),
    });
  } finally {
    active = null;
  }
};

const onRequest = (request: WorkerRequest): void => {
  if (request.type === 'abort') {
    if (active?.operationId === request.operationId) {
      active.ctx.abort();
    }
    return;
  }
  void start(request);
};

(port as MessagePort).on('message', onRequest);
