import { parentPort } from 'node:worker_threads';
import { BamlCallContext } from '@boundaryml/baml-bridge';
import type { MessagePort } from 'node:worker_threads';
import type { TurnPlan, TurnPlan$stream } from './generated/baml_sdk/host/index.js';
import type {
  StartRequest,
  WireFailure,
  WireRejection,
  WireToolSelection,
  WireTurnPlan,
  WorkerMessage,
  WorkerRequest,
} from './protocol';
import { assertManifestIsCallable, compiledClients } from './manifest';
import {
  MODEL_ERROR_MESSAGE,
  PARSE_ERROR_MESSAGE,
  TRANSPORT_FAILED_MESSAGE,
  UNCOMPILED_CLIENT_MESSAGE,
} from './protocol';

/**
 * The single-use native worker.
 *
 * This is the only module in the package that touches generated bytecode, and
 * it runs one operation before the parent terminates it. Single-use is not
 * frugality: `next()` and `final()` are BLOCKING pulls that occupy this thread,
 * so a cooperative abort cannot be observed while one is in flight and the
 * parent's only reliable cancellation is `worker.terminate()`. A pooled worker
 * would have to survive that.
 *
 * Nothing native crosses back. Generated class instances are flattened to plain
 * data, and errors become one of a closed set of sanitized wire values.
 */

const port = parentPort;

if (port == null) {
  throw new Error('packages/api/dist/baml/worker.mjs must be started as a worker thread');
}

assertManifestIsCallable();

/**
 * Only ONE operation ever runs here, but the id is still checked on every
 * message: a stale abort for a previous id must not cancel the current call.
 */
let active: { operationId: string; ctx: BamlCallContext } | null = null;

const post = (message: WorkerMessage): void => {
  port.postMessage(message);
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null;

const messageOf = (error: unknown): string => {
  if (error instanceof Error) {
    return error.message;
  }
  return isRecord(error) && typeof error.message === 'string' ? error.message : String(error);
};

const classNameOf = (error: unknown): string =>
  isRecord(error) && typeof error.className === 'string' ? error.className : '';

/**
 * `baml.errors.LlmClient` straddles the line: it covers both a genuinely failed
 * request AND a request that succeeded but whose body did not match the return
 * type. The second is the model writing something unparseable — a per-turn
 * failure, not a transport fault — and rejecting for it would take down a turn
 * the contract says should surface as a value. The class name alone cannot
 * separate them, so the coercion shape is matched.
 */
const TRANSPORT_CLASSES = new Set([
  'baml.errors.Io',
  'baml.errors.LlmClient',
  'baml.errors.Timeout',
]);

/**
 * Retry exhaustion arrives as `baml.errors.DevOther` — the orchestrator's own
 * catch-all — rather than as the underlying `LlmClient` error, so the class name
 * alone would misfile a provider outage as a model failure. The orchestrator's
 * message is the discriminator, matched as a literal substring: no `RegExp` is
 * ever constructed from runtime text here.
 */
const ORCHESTRATION_EXHAUSTED = 'All orchestration steps failed';

/**
 * A literal test, never a constructed one: building a `RegExp` from a client or
 * model name would let a name containing `[` make the classifier itself throw.
 */
const COERCION_FAILURE = /Expected .+, got /;

const isAbort = (error: unknown, ctx: BamlCallContext | null): boolean => {
  if (ctx?.aborted === true) {
    return true;
  }
  const name = error instanceof Error ? error.name : '';
  return name === 'AbortError' || classNameOf(error).includes('Cancelled');
};

const isParseFailure = (error: unknown): boolean => COERCION_FAILURE.test(messageOf(error));

const isTransport = (error: unknown): boolean => {
  if (isParseFailure(error)) {
    return false;
  }
  return (
    TRANSPORT_CLASSES.has(classNameOf(error)) ||
    messageOf(error).includes(ORCHESTRATION_EXHAUSTED)
  );
};

const failure = (code: WireFailure['code'], message: string, detail?: string): WireFailure =>
  detail == null ? { code, message } : { code, message, detail };

const rejection = (kind: WireRejection['kind'], message: string, detail: string): WireRejection => ({
  kind,
  message,
  detail,
});

/**
 * The host reads the literal discriminator as a plain field: a union-typed BAML
 * parameter cannot discriminate a host map, so `tool` names the variant and the
 * remaining fields are its arguments.
 */
const toWireSelection = (selection: unknown): WireToolSelection | null => {
  if (!isRecord(selection) || typeof selection.tool !== 'string') {
    return null;
  }
  const { tool, ...rest } = selection;
  const args: Record<string, string | number | boolean | null> = {};
  for (const [key, value] of Object.entries(rest)) {
    if (value === null) {
      args[key] = null;
      continue;
    }
    const kind = typeof value;
    args[key] = kind === 'string' || kind === 'number' || kind === 'boolean' ? (value as string) : String(value);
  }
  return { name: tool, args };
};

/**
 * End of stream, bridge 0.15.0 edition.
 *
 * `next()` is typed `TurnPlan$stream | null`, but an exhausted stream does not
 * return `null` — it returns a partial with every declared field still
 * `undefined`, and it keeps returning one for as long as it is asked. Breaking
 * on `null` alone spins forever and never reaches `final()`; that is what a
 * loopback fixture showed before this guard existed. A live stream blocks inside
 * `next()` instead of answering with an empty partial, including before the
 * first byte of content, so this sentinel cannot end a stream early.
 */
const isExhausted = (snapshot: TurnPlan$stream | null | undefined): boolean => {
  if (snapshot === null || snapshot === undefined) {
    return true;
  }
  const partial = snapshot as unknown as { reply?: unknown; tools?: unknown };
  return partial.reply === undefined && partial.tools === undefined;
};

/** Flattens a generated `TurnPlan` (or its `$stream` partial) to plain data. */
const toWirePlan = (plan: TurnPlan | TurnPlan$stream): WireTurnPlan => {
  const source = plan as unknown as { reply?: unknown; tools?: unknown };
  const reply = typeof source.reply === 'string' ? source.reply : null;
  const tools = Array.isArray(source.tools)
    ? source.tools.map(toWireSelection).filter((tool): tool is WireToolSelection => tool !== null)
    : [];
  return { reply, tools };
};

const runCall = async (request: StartRequest, ctx: BamlCallContext): Promise<void> => {
  const entry = compiledClients.get(request.clientName);
  if (entry == null) {
    return;
  }
  const { userMessage, transcript, allowedTools } = request.input;
  const plan = await entry.take(userMessage, transcript, [...allowedTools], { $ctx: ctx });
  post({ type: 'final', operationId: request.operationId, plan: toWirePlan(plan) });
};

/**
 * The pulls are the SYNCHRONOUS `next()` / `final()`, not `nextAsync()` /
 * `finalAsync()`: on bridge 0.15.0 the async pair resolves an aborted read with
 * an empty value instead of rejecting and does not reliably deliver
 * pre-final snapshots. Blocking this thread is acceptable precisely because the
 * worker is single-use and the parent can terminate it.
 *
 * `postMessage` does not need this thread's event loop, so snapshots still reach
 * the parent immediately while a pull is blocked.
 */
const runStream = async (request: StartRequest, ctx: BamlCallContext): Promise<void> => {
  const entry = compiledClients.get(request.clientName);
  if (entry == null) {
    return;
  }
  const { userMessage, transcript, allowedTools } = request.input;
  const stream = await entry.stream(userMessage, transcript, [...allowedTools], { $ctx: ctx });

  // Identical snapshots are dropped HERE, not just in the facade's delta rule.
  // A provider whose stream body the parser cannot advance through makes `next()`
  // return the same unchanged partial as fast as the loop can ask: a malformed
  // fixture produced 1.2M of them in a minute. Deduplicating at the source turns
  // that into silence, which is what the parent's idle deadline is built to end.
  let previous = '';

  for (;;) {
    const snapshot = stream.next();
    if (isExhausted(snapshot)) {
      break;
    }
    const wire = toWirePlan(snapshot as TurnPlan$stream);
    const serialized = JSON.stringify(wire);
    if (serialized === previous) {
      continue;
    }
    previous = serialized;
    post({ type: 'chunk', operationId: request.operationId, snapshot: wire });
  }

  post({ type: 'finalizing', operationId: request.operationId });
  post({ type: 'final', operationId: request.operationId, plan: toWirePlan(stream.final()) });
};

const start = async (request: StartRequest): Promise<void> => {
  const { operationId, clientName } = request;

  if (!compiledClients.has(clientName)) {
    post({
      type: 'failure',
      operationId,
      failure: failure('model_error', UNCOMPILED_CLIENT_MESSAGE, `unknown client ${clientName}`),
    });
    return;
  }

  const ctx = new BamlCallContext();
  active = { operationId, ctx };
  post({ type: 'ready', operationId });

  try {
    await (request.mode === 'call' ? runCall(request, ctx) : runStream(request, ctx));
  } catch (error) {
    const detail = messageOf(error);
    if (isAbort(error, ctx)) {
      post({ type: 'rejection', operationId, rejection: rejection('abort', 'aborted', detail) });
      return;
    }
    if (isTransport(error)) {
      post({
        type: 'rejection',
        operationId,
        rejection: rejection('transport', TRANSPORT_FAILED_MESSAGE, detail),
      });
      return;
    }
    post({
      type: 'failure',
      operationId,
      failure: isParseFailure(error)
        ? failure('parse_error', PARSE_ERROR_MESSAGE, detail)
        : failure('model_error', MODEL_ERROR_MESSAGE, detail),
    });
  } finally {
    active = null;
  }
};

const onRequest = (request: WorkerRequest): void => {
  if (request.type === 'abort') {
    if (active?.operationId === request.operationId) {
      active.ctx.abort();
    }
    return;
  }
  void start(request);
};

(port as MessagePort).on('message', onRequest);
