const {
  ALLOW_REGISTRATION: ALLOW_REGISTRATION,
  VITE_DOMAIN_SERVER: DOMAIN_SERVER,
  VITE_SHOW_GOOGLE_LOGIN_OPTION: SHOW_GOOGLE_LOGIN_OPTION,
} = import.meta.env;

export {
  ALLOW_REGISTRATION,
  DOMAIN_SERVER,
  SHOW_GOOGLE_LOGIN_OPTION
};