import { CryptoId } from 'librechat-data-provider';
import { ReactNode } from 'react';
import {
  AdaIcon,
  ShibIcon,
  IotaIcon,
  PancakeSwapIcon,
  NemIcon,
  BonkIcon,
  DogwifhatIcon,
  WoofIcon,
  SolendIcon,
} from '~/components/svg';

export interface BlockchainNetwork {
  type?: 'Network' | 'Token';
  blockchain?: CryptoId;
  label: string;
  id: CryptoId;
  icon: ReactNode;
  placeholder: string;
  scanUrl: string;
}
export const blockchainNetworks: BlockchainNetwork[] = [
  {
    id: CryptoId.BTC,
    label: 'Bitcoin',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/btc.png" />,
    placeholder: 'Enter your BTC address',
    scanUrl: 'https://www.blockchain.com/explorer/addresses/btc/(walletaddress)',
  },
  {
    id: CryptoId.ETH,
    label: 'Ethereum',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/eth.png" />,
    placeholder: 'Enter your ETH address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    id: CryptoId.BNB,
    label: 'Binance',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/bnb.png" />,
    placeholder: 'Enter your BNB address',
    scanUrl: 'https://bscscan.com/address/(walletaddress)',
  },

  {
    id: CryptoId.ADA,
    label: 'Cardano',
    icon: <AdaIcon />,
    placeholder: 'Enter your ADA address',
    scanUrl: 'https://explorer.cardano.org/en/address?address=(walletaddress)',
  },
  {
    id: CryptoId.XRP,
    label: 'XRP',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/xrp.png" />,
    placeholder: 'Enter your XRP address',
    scanUrl: 'https://xrpscan.com/account/(walletaddress)',
  },
  {
    id: CryptoId.DOGE,
    label: 'Dogecoin',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/doge.png" />,
    placeholder: 'Enter your DOGE address',
    scanUrl: 'https://dogechain.info/address/(walletaddress)',
  },
  {
    id: CryptoId.DOT,
    label: 'Polkadot',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/dot.png" />,
    placeholder: 'Enter your DOT address',
    scanUrl: 'https://polkadot.subscan.io/account/(walletaddress)',
  },
  {
    id: CryptoId.BCH,
    label: 'Bitcoin Cash',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/bch.png" />,
    placeholder: 'Enter your BCH address',
    scanUrl: 'https://blockchair.com/bitcoin-cash/address/(walletaddress)',
  },

  {
    id: CryptoId.LTC,
    label: 'Litecoin',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/ltc.png" />,
    placeholder: 'Enter your LTC address',
    scanUrl: 'https://blockchair.com/litecoin/address/(walletaddress)',
  },
  {
    id: CryptoId.SOL,
    label: 'Solana',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/sol.png" />,
    placeholder: 'Enter your SOL address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },

  {
    id: CryptoId.MATIC,
    label: 'Matic',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/matic.png" />,
    placeholder: 'Enter your MATIC address',
    scanUrl: 'https://polygonscan.com/address/(walletaddress)',
  },

  {
    id: CryptoId.THETA,
    label: 'Theta',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/theta.png" />,
    placeholder: 'Enter your THETA address',
    scanUrl: 'https://explorer.thetatoken.org/account/(walletaddress)',
  },
  {
    id: CryptoId.XLM,
    label: 'Stellar',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/xlm.png" />,
    placeholder: 'Enter your XLM address',
    scanUrl: 'https://stellarchain.io/accounts/(walletaddress)',
  },

  {
    id: CryptoId.ICP,
    label: 'Dfinity',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/icp.png" />,
    placeholder: 'Enter your ICP address',
    scanUrl: 'https://dashboard.internetcomputer.org/account/(walletaddress)',
  },
  {
    id: CryptoId.VET,
    label: 'Vechain',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/vet.png" />,
    placeholder: 'Enter your VET address',
    scanUrl: 'https://explore.vechain.org/accounts/(walletaddress)/txs',
  },
  {
    id: CryptoId.FIL,
    label: 'Filecoin',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/fil.png" />,
    placeholder: 'Enter your FIL address',
    scanUrl: 'https://filscan.io/en/address/(walletaddress)',
  },
  {
    id: CryptoId.TRX,
    label: 'Tron',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/trx.png" />,
    placeholder: 'Enter your TRX address',
    scanUrl: 'https://tronscan.org/#/(walletaddress)',
  },
  {
    id: CryptoId.EOS,
    label: 'EOS',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/eos.png" />,
    placeholder: 'Enter your EOS address',
    scanUrl: 'https://bloks.io/account/(walletaddress)',
  },
  {
    id: CryptoId.XMR,
    label: 'Monero',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/xmr.png" />,
    placeholder: 'Enter your XMR address',
    scanUrl: 'https://bloks.io/(walletaddress)',
  },

  {
    id: CryptoId.NEO,
    label: 'NEO',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/neo.png" />,
    placeholder: 'Enter your NEO address',
    scanUrl: 'https://neo2.neotube.io/address/(walletaddress)',
  },

  {
    id: CryptoId.IOTA,
    label: 'IOTA',
    icon: <IotaIcon />,
    placeholder: 'Enter your IOTA address',
    scanUrl: 'https://explorer.iota.org/mainnet/addr/(walletaddress)',
  },
  {
    id: CryptoId.AVAX,
    label: 'Avalanche',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/avax.png" />,
    placeholder: 'Enter your AVAX address',
    scanUrl: 'https://avascan.info/blockchain/dexalot/address/(walletaddress)/transactions',
  },
  {
    id: CryptoId.DASH,
    label: 'Dash',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/dash.png" />,
    placeholder: 'Enter your DASH address',
    scanUrl: 'https://explorer.dash.org/insight/address/(walletaddress)',
  },
  {
    id: CryptoId.NEM,
    label: 'NEM',
    icon: <NemIcon />,
    placeholder: 'Enter your NEM address',
    scanUrl: 'https://zcashblockexplorer.com/address/(walletaddress)',
  },
  {
    id: CryptoId.ZEC,
    label: 'Zcash',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/zec.png" />,
    placeholder: 'Enter your ZEC address',
    scanUrl: 'https://explorer.nemtool.com/#s_account?account=(walletaddress)',
  },
];

export const networkTokens: BlockchainNetwork[] = [
  {
    id: CryptoId.UNI,
    type: 'Token',
    blockchain: CryptoId.ETH,
    label: 'Uniswap',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/uni.png" />,
    placeholder: 'Enter your UNI address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.USDT,
    label: 'Tether',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/usdt.png" />,
    placeholder: 'Enter your USDT address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.LINK,
    label: 'Chainlink',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/link.png" />,
    placeholder: 'Enter your LINK address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.WBTC,
    label: 'Wrapped Bitcoin',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/wbtc.png" />,
    placeholder: 'Enter your WBTC address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.DAI,
    label: 'DAI',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/dai.png" />,
    placeholder: 'Enter your DAI address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.AAVE,
    label: 'Aave',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/aave.png" />,
    placeholder: 'Enter your AAVE address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.COMP,
    label: 'Compound',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/comp.png" />,
    placeholder: 'Enter your COMP address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.SOL,
    id: CryptoId.SLORP,
    label: 'Slorp',
    icon: <img className="h-10 w-10" src="/assets/cryptocurrency/SlorpCoin.png" />,
    placeholder: 'Enter your Slorp Address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.SOL,
    id: CryptoId.Solend,
    label: 'Solend',
    icon: <SolendIcon />,
    placeholder: 'Enter your Solend Address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.SOL,
    id: CryptoId.Woof,
    label: 'Woof',
    icon: <WoofIcon />,
    placeholder: 'Enter your Woof Address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.SOL,
    id: CryptoId.Bonk,
    label: 'Bonk',
    icon: <BonkIcon />,
    placeholder: 'Enter your Bonk Address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.SOL,
    id: CryptoId.Dogwifhat,
    label: 'Dogwifhat',
    icon: <DogwifhatIcon />,
    placeholder: 'Enter your Dogwifhat Address',
    scanUrl: 'https://solscan.io/account/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.SHIB,
    label: 'Shiba',
    icon: <ShibIcon />,
    placeholder: 'Enter your SHIB address',
    scanUrl: 'https://neoscan.io/(walletaddress)',
  },
  {
    type: 'Token',
    blockchain: CryptoId.ETH,
    id: CryptoId.CAKE,
    label: 'PancakeSwap',
    icon: <PancakeSwapIcon />,
    placeholder: 'Enter your CAKE address',
    scanUrl: 'https://etherscan.io/address/(walletaddress)',
  },
];
