apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    argocd.argoproj.io/instance: librechat
  name: librechat-images-pvc
  namespace: librechat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.librechat.imageVolume.size }}
  storageClassName: ''
  volumeName: librechat-images-volume