/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// baml-cli is available with the baml package.

import { defineFunction } from "@boundaryml/baml-bridge";

/**
 * Returns the current BEX runtime ID for this function invocation: the
 * override set via `baml.id.set` / `$id = ...` if one is active, otherwise
 * the call's default `CallRef`. Returns an empty string when no BEX
 * function is running (e.g. during `$init`).
 */
export const current = defineFunction("baml.id.current", "sync", []) as () => string;

/**
 * Returns the current BEX runtime ID for this function invocation: the
 * override set via `baml.id.set` / `$id = ...` if one is active, otherwise
 * the call's default `CallRef`. Returns an empty string when no BEX
 * function is running (e.g. during `$init`).
 */
export const current_async = defineFunction("baml.id.current", "async", []) as () => Promise<string>;

const __baml_new = defineFunction("baml.id.new", "sync", []) as () => string;
export { __baml_new as new };

export const new_async = defineFunction("baml.id.new", "async", []) as () => Promise<string>;

/**
 * @throws InvalidArgument
 */
export const set = defineFunction("baml.id.set", "sync", ["id"]) as (id: string) => string;

/**
 * @throws InvalidArgument
 */
export const set_async = defineFunction("baml.id.set", "async", ["id"]) as (id: string) => Promise<string>;
