const path = require('path');
const mime = require('mime');
const { v4 } = require('uuid');
const { FileContext, FileSources } = require('librechat-data-provider');
const { getStrategyFunctions } = require('~/server/services/Files/strategies');
const { createFile } = require('~/models/File');
const { logger } = require('~/config');

const ANTHROPIC_API_BASE = 'https://api.anthropic.com/v1';
const ANTHROPIC_VERSION = '2023-06-01';
const FILES_BETA = 'files-api-2025-04-14';

/**
 * Build the headers for an Anthropic Files API request.
 * @param {string} apiKey
 * @returns {Record<string, string>}
 */
function buildFilesHeaders(apiKey) {
  return {
    'x-api-key': apiKey,
    'anthropic-version': ANTHROPIC_VERSION,
    'anthropic-beta': FILES_BETA,
  };
}

/**
 * Fetch metadata for an Anthropic file via raw HTTP (the SDK in this repo,
 * @anthropic-ai/sdk 0.27.x, doesn't expose client.beta.files).
 * @param {string} apiKey
 * @param {string} fileId
 * @returns {Promise<{ filename?: string, mime_type?: string, size_bytes?: number }>}
 */
async function fetchFileMetadata(apiKey, fileId) {
  const res = await fetch(`${ANTHROPIC_API_BASE}/files/${fileId}`, {
    method: 'GET',
    headers: buildFilesHeaders(apiKey),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Files API metadata ${res.status}: ${body}`);
  }
  return res.json();
}

/**
 * Download the bytes of a file from the Anthropic Files API.
 * @param {string} apiKey
 * @param {string} fileId
 * @returns {Promise<Buffer>}
 */
async function downloadFileBytes(apiKey, fileId) {
  const res = await fetch(`${ANTHROPIC_API_BASE}/files/${fileId}/content`, {
    method: 'GET',
    headers: buildFilesHeaders(apiKey),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Files API download ${res.status}: ${body}`);
  }
  const arrayBuffer = await res.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

/**
 * Download a file generated by Anthropic Skills / code execution and persist
 * it to LibreChat's configured file storage. Returns metadata that can be
 * pushed onto the assistant message's attachments array.
 *
 * Mirrors the pattern used by `processCodeOutput` in
 * api/server/services/Files/Code/process.js, but pulls bytes from the
 * Anthropic Files API (via raw fetch) instead of the LibreChat
 * code-execution sidecar.
 *
 * @param {object} params
 * @param {ServerRequest} params.req
 * @param {string} params.apiKey - Anthropic API key.
 * @param {string} params.file_id - The file_id returned in a code_execution_tool_result block.
 * @param {string} [params.filenameHint]
 * @param {string} [params.conversationId]
 * @param {string} [params.messageId]
 * @returns {Promise<object | null>} File attachment metadata, or null on error.
 */
async function processAnthropicFile({
  req,
  apiKey,
  file_id,
  filenameHint,
  conversationId,
  messageId,
}) {
  try {
    if (!apiKey) {
      throw new Error('Missing Anthropic API key');
    }

    const metadata = await fetchFileMetadata(apiKey, file_id);
    const realFilename = metadata?.filename ?? filenameHint ?? file_id;
    const mimeType =
      metadata?.mime_type ?? mime.getType(realFilename) ?? 'application/octet-stream';

    const buffer = await downloadFileBytes(apiKey, file_id);

    const fileSource = req.app.locals.fileStrategy;
    const { saveBuffer } = getStrategyFunctions(fileSource);
    if (!saveBuffer) {
      throw new Error(`File strategy "${fileSource}" does not support saveBuffer`);
    }

    const newFileId = v4();
    const ext = path.extname(realFilename) || `.${mime.getExtension(mimeType) ?? 'bin'}`;
    const storedName = `${newFileId}${ext}`;

    let filepath = await saveBuffer({
      userId: req.user.id,
      buffer,
      fileName: storedName,
      basePath: 'documents',
    });

    /* Local strategy quirk: saveLocalBuffer writes the bytes to
     * `paths.uploads/documents/{userId}/{file}` on disk but returns
     * `/documents/{userId}/{file}` as the URL. The download route at
     * GET /api/files/download/:userId/:file_id reads file.filepath via
     * getLocalFileStream, which only matches paths containing `/uploads/`
     * or `/images/`. Prepend `/uploads` so the on-disk location and the
     * URL prefix line up without modifying core LibreChat code. */
    if (
      fileSource === FileSources.local &&
      typeof filepath === 'string' &&
      !filepath.startsWith('/uploads/') &&
      !filepath.startsWith('/images/')
    ) {
      filepath = `/uploads${filepath}`;
    }

    const now = new Date().toISOString();
    const fileRecord = {
      file_id: newFileId,
      user: req.user.id,
      filename: realFilename,
      filepath,
      bytes: buffer.length,
      type: mimeType,
      source: fileSource,
      context: FileContext.message_attachment,
      usage: 1,
      createdAt: now,
      updatedAt: now,
    };

    await createFile(fileRecord, true);

    return Object.assign({}, fileRecord, { messageId, conversationId });
  } catch (error) {
    logger.error('[processAnthropicFile] Failed to download/persist Anthropic file', {
      file_id,
      error: error?.message ?? error,
    });
    return null;
  }
}

module.exports = { processAnthropicFile };
