/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// baml-cli is available with the baml package.

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

/**
 * A received UDP datagram: the payload bytes and the address of the sender.
 */
export class Datagram$stream {
  data!: Uint8Array;
  addr!: string | null;
  constructor(init: {
    data: Uint8Array;
    addr: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A bound TCP listener. Created by `baml.net.TcpListener.bind`. Calling `accept`
 * suspends the current BAML thread until an incoming connection arrives (or the
 * thread is cancelled). Modeled on Rust's `std::net::TcpListener`.
 */
export class TcpListener$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A TCP connection. Created by `baml.net.TcpStream.connect` or returned by
 * `baml.net.TcpListener.accept`. Modeled on Rust's `std::net::TcpStream`.
 */
export class TcpStream$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A UDP socket. Created by `baml.net.UdpSocket.bind`. UDP is connectionless and
 * message-oriented: every `send_to` / `recv_from` carries a single datagram.
 * Modeled on Rust's `std::net::UdpSocket`.
 */
export class UdpSocket$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Converts an optional timeout into the nanosecond count carried across the
 * sys-op boundary. `null` (no deadline) becomes `0n`, which the native layer
 * treats as unbounded (see `timeout_from_nanos`). Modeled on Rust's
 * `Option<Duration>`, where `None` means "block forever".
 */
export const _timeout_nanos = defineFunction("baml.net._timeout_nanos", "sync", ["timeout"]) as (timeout: baml.time.Duration | null) => bigint;

/**
 * Converts an optional timeout into the nanosecond count carried across the
 * sys-op boundary. `null` (no deadline) becomes `0n`, which the native layer
 * treats as unbounded (see `timeout_from_nanos`). Modeled on Rust's
 * `Option<Duration>`, where `None` means "block forever".
 */
export const _timeout_nanos_async = defineFunction("baml.net._timeout_nanos", "async", ["timeout"]) as (timeout: baml.time.Duration | null) => Promise<bigint>;

/**
 * A TCP connection. Created by `baml.net.TcpStream.connect` or returned by
 * `baml.net.TcpListener.accept`. Modeled on Rust's `std::net::TcpStream`.
 */
export class TcpStream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Opens a TCP connection to `addr` (e.g. `"127.0.0.1:8080"`) and returns the stream.
 * 
 * `timeout` bounds how long to wait for the connection to be established;
 * `null` (the default) waits indefinitely (subject to the OS default). On
 * expiry this throws `root.errors.Timeout`.
 * @throws Io
 * @throws Timeout
 */
  static connect = defineFunction("baml.net.TcpStream.connect", "sync", ["addr"], ["timeout"]) as (addr: string, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => TcpStream;
/**
 * Opens a TCP connection to `addr` (e.g. `"127.0.0.1:8080"`) and returns the stream.
 * 
 * `timeout` bounds how long to wait for the connection to be established;
 * `null` (the default) waits indefinitely (subject to the OS default). On
 * expiry this throws `root.errors.Timeout`.
 * @throws Io
 * @throws Timeout
 */
  static connect_async = defineFunction("baml.net.TcpStream.connect", "async", ["addr"], ["timeout"]) as (addr: string, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Promise<TcpStream>;
/**
 * @throws Io
 * @throws Timeout
 */
  static _connect = defineFunction("baml.net.TcpStream._connect", "sync", ["addr", "timeout_nanos"]) as (addr: string, timeout_nanos: bigint) => TcpStream;
/**
 * @throws Io
 * @throws Timeout
 */
  static _connect_async = defineFunction("baml.net.TcpStream._connect", "async", ["addr", "timeout_nanos"]) as (addr: string, timeout_nanos: bigint) => Promise<TcpStream>;
/**
 * Reads the next available bytes from the stream. Blocks until data arrives.
 * Returns an empty `uint8array` once the peer has closed the connection (EOF).
 * 
 * `timeout` bounds the wait for data; `null` (the default) blocks
 * indefinitely. On expiry this throws `root.errors.Timeout` and the stream
 * remains usable for a subsequent read.
 * @throws Io
 * @throws Timeout
 */
  read = defineInstanceFunction("baml.net.TcpStream.read", "sync", ["self"], ["timeout"]).bind(this) as ($opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Uint8Array;
/**
 * Reads the next available bytes from the stream. Blocks until data arrives.
 * Returns an empty `uint8array` once the peer has closed the connection (EOF).
 * 
 * `timeout` bounds the wait for data; `null` (the default) blocks
 * indefinitely. On expiry this throws `root.errors.Timeout` and the stream
 * remains usable for a subsequent read.
 * @throws Io
 * @throws Timeout
 */
  read_async = defineInstanceFunction("baml.net.TcpStream.read", "async", ["self"], ["timeout"]).bind(this) as ($opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Promise<Uint8Array>;
/**
 * @throws Io
 * @throws Timeout
 */
  _read = defineInstanceFunction("baml.net.TcpStream._read", "sync", ["self", "timeout_nanos"]).bind(this) as (timeout_nanos: bigint) => Uint8Array;
/**
 * @throws Io
 * @throws Timeout
 */
  _read_async = defineInstanceFunction("baml.net.TcpStream._read", "async", ["self", "timeout_nanos"]).bind(this) as (timeout_nanos: bigint) => Promise<Uint8Array>;
/**
 * Writes `data` to the stream. Blocks until every byte has been flushed.
 * 
 * `timeout` bounds the flush; `null` (the default) blocks indefinitely. On
 * expiry this throws `root.errors.Timeout`; an unknown amount of `data` may
 * already have been written.
 * @throws Io
 * @throws Timeout
 */
  write = defineInstanceFunction("baml.net.TcpStream.write", "sync", ["self", "data"], ["timeout"]).bind(this) as (data: Uint8Array, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => null;
/**
 * Writes `data` to the stream. Blocks until every byte has been flushed.
 * 
 * `timeout` bounds the flush; `null` (the default) blocks indefinitely. On
 * expiry this throws `root.errors.Timeout`; an unknown amount of `data` may
 * already have been written.
 * @throws Io
 * @throws Timeout
 */
  write_async = defineInstanceFunction("baml.net.TcpStream.write", "async", ["self", "data"], ["timeout"]).bind(this) as (data: Uint8Array, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Promise<null>;
/**
 * @throws Io
 * @throws Timeout
 */
  _write = defineInstanceFunction("baml.net.TcpStream._write", "sync", ["self", "data", "timeout_nanos"]).bind(this) as (data: Uint8Array, timeout_nanos: bigint) => null;
/**
 * @throws Io
 * @throws Timeout
 */
  _write_async = defineInstanceFunction("baml.net.TcpStream._write", "async", ["self", "data", "timeout_nanos"]).bind(this) as (data: Uint8Array, timeout_nanos: bigint) => Promise<null>;
/**
 * Closes the connection.
 * @throws Io
 */
  close = defineInstanceFunction("baml.net.TcpStream.close", "sync", ["self"]).bind(this) as () => null;
/**
 * Closes the connection.
 * @throws Io
 */
  close_async = defineInstanceFunction("baml.net.TcpStream.close", "async", ["self"]).bind(this) as () => Promise<null>;
}

/**
 * A bound TCP listener. Created by `baml.net.TcpListener.bind`. Calling `accept`
 * suspends the current BAML thread until an incoming connection arrives (or the
 * thread is cancelled). Modeled on Rust's `std::net::TcpListener`.
 */
export class TcpListener {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Binds to `addr` (e.g. `"127.0.0.1:8080"`) and returns a listener ready to
 * accept incoming connections.
 * @throws Io
 */
  static bind = defineFunction("baml.net.TcpListener.bind", "sync", ["addr"]) as (addr: string) => TcpListener;
/**
 * Binds to `addr` (e.g. `"127.0.0.1:8080"`) and returns a listener ready to
 * accept incoming connections.
 * @throws Io
 */
  static bind_async = defineFunction("baml.net.TcpListener.bind", "async", ["addr"]) as (addr: string) => Promise<TcpListener>;
/**
 * Waits for the next incoming connection and returns it as a `TcpStream`.
 * @throws Io
 */
  accept = defineInstanceFunction("baml.net.TcpListener.accept", "sync", ["self"]).bind(this) as () => TcpStream;
/**
 * Waits for the next incoming connection and returns it as a `TcpStream`.
 * @throws Io
 */
  accept_async = defineInstanceFunction("baml.net.TcpListener.accept", "async", ["self"]).bind(this) as () => Promise<TcpStream>;
/**
 * @throws Io
 */
  close = defineInstanceFunction("baml.net.TcpListener.close", "sync", ["self"]).bind(this) as () => null;
/**
 * @throws Io
 */
  close_async = defineInstanceFunction("baml.net.TcpListener.close", "async", ["self"]).bind(this) as () => Promise<null>;
}

/**
 * A UDP socket. Created by `baml.net.UdpSocket.bind`. UDP is connectionless and
 * message-oriented: every `send_to` / `recv_from` carries a single datagram.
 * Modeled on Rust's `std::net::UdpSocket`.
 */
export class UdpSocket {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Binds to `addr` (e.g. `"0.0.0.0:0"` for an OS-assigned ephemeral port) and
 * returns the socket.
 * @throws Io
 */
  static bind = defineFunction("baml.net.UdpSocket.bind", "sync", ["addr"]) as (addr: string) => UdpSocket;
/**
 * Binds to `addr` (e.g. `"0.0.0.0:0"` for an OS-assigned ephemeral port) and
 * returns the socket.
 * @throws Io
 */
  static bind_async = defineFunction("baml.net.UdpSocket.bind", "async", ["addr"]) as (addr: string) => Promise<UdpSocket>;
/**
 * Sends `data` as a single datagram to `addr`. Returns the number of bytes sent.
 * 
 * `timeout` bounds the send; `null` (the default) blocks indefinitely. On
 * expiry this throws `root.errors.Timeout`. Mirrors `UdpSocket::set_write_timeout`.
 * @throws Io
 * @throws Timeout
 */
  send_to = defineInstanceFunction("baml.net.UdpSocket.send_to", "sync", ["self", "data", "addr"], ["timeout"]).bind(this) as (data: Uint8Array, addr: string, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => number;
/**
 * Sends `data` as a single datagram to `addr`. Returns the number of bytes sent.
 * 
 * `timeout` bounds the send; `null` (the default) blocks indefinitely. On
 * expiry this throws `root.errors.Timeout`. Mirrors `UdpSocket::set_write_timeout`.
 * @throws Io
 * @throws Timeout
 */
  send_to_async = defineInstanceFunction("baml.net.UdpSocket.send_to", "async", ["self", "data", "addr"], ["timeout"]).bind(this) as (data: Uint8Array, addr: string, $opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Promise<number>;
/**
 * @throws Io
 * @throws Timeout
 */
  _send_to = defineInstanceFunction("baml.net.UdpSocket._send_to", "sync", ["self", "data", "addr", "timeout_nanos"]).bind(this) as (data: Uint8Array, addr: string, timeout_nanos: bigint) => number;
/**
 * @throws Io
 * @throws Timeout
 */
  _send_to_async = defineInstanceFunction("baml.net.UdpSocket._send_to", "async", ["self", "data", "addr", "timeout_nanos"]).bind(this) as (data: Uint8Array, addr: string, timeout_nanos: bigint) => Promise<number>;
/**
 * Receives a single datagram, returning its payload bytes together with the
 * address of the sender.
 * 
 * `timeout` bounds the wait for a datagram; `null` (the default) blocks
 * indefinitely. On expiry this throws `root.errors.Timeout` and the socket
 * remains usable. Mirrors `UdpSocket::set_read_timeout`.
 * @throws Io
 * @throws Timeout
 */
  recv_from = defineInstanceFunction("baml.net.UdpSocket.recv_from", "sync", ["self"], ["timeout"]).bind(this) as ($opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Datagram;
/**
 * Receives a single datagram, returning its payload bytes together with the
 * address of the sender.
 * 
 * `timeout` bounds the wait for a datagram; `null` (the default) blocks
 * indefinitely. On expiry this throws `root.errors.Timeout` and the socket
 * remains usable. Mirrors `UdpSocket::set_read_timeout`.
 * @throws Io
 * @throws Timeout
 */
  recv_from_async = defineInstanceFunction("baml.net.UdpSocket.recv_from", "async", ["self"], ["timeout"]).bind(this) as ($opts?: { timeout?: baml.time.Duration | null | undefined } | undefined) => Promise<Datagram>;
/**
 * @throws Io
 * @throws Timeout
 */
  _recv_from = defineInstanceFunction("baml.net.UdpSocket._recv_from", "sync", ["self", "timeout_nanos"]).bind(this) as (timeout_nanos: bigint) => Datagram;
/**
 * @throws Io
 * @throws Timeout
 */
  _recv_from_async = defineInstanceFunction("baml.net.UdpSocket._recv_from", "async", ["self", "timeout_nanos"]).bind(this) as (timeout_nanos: bigint) => Promise<Datagram>;
/**
 * Closes the socket.
 * @throws Io
 */
  close = defineInstanceFunction("baml.net.UdpSocket.close", "sync", ["self"]).bind(this) as () => null;
/**
 * Closes the socket.
 * @throws Io
 */
  close_async = defineInstanceFunction("baml.net.UdpSocket.close", "async", ["self"]).bind(this) as () => Promise<null>;
}

/**
 * A received UDP datagram: the payload bytes and the address of the sender.
 */
export class Datagram {
  data!: Uint8Array;
  addr!: string;
  constructor(init: {
    data: Uint8Array;
    addr: string;
  }) {
    Object.assign(this, init);
  }
}
