/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// baml-cli is available with the baml package.

import { defineFunction } from "@boundaryml/baml-bridge";

/**
 * Opaque builtin class. Construction is reserved to the bridge
 * boundary; users cannot construct or destructure it.
 */
export class HostValue$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * Internal: invoked only by compiler-synthesized host-callable wrapper
 * closures. Not directly callable by user code.
 * 
 * `T` is the expected return type and `E` the declared error contract,
 * both delivered to the native handler at runtime via the type-arg channel
 * (`type_arg_0` / `type_arg_1`). The completion site validates the host's
 * returned value against `T` and the thrown value against `E`: a return
 * that doesn't inhabit `T` and a throw that isn't a subtype of `E` both
 * become `baml.panics.HostContractViolation` (uncatchable). An on-contract
 * throw rides the VM's normal exception unwinder. A host value left
 * untyped at the boundary erases `E` to `unknown`, which accepts any
 * thrown value — including an opaque `baml.errors.HostCallable`.
 * 
 * `args` is a two-element pack the VM builds in `host_closure_call_sysop`:
 * `[positional_required_args, { optional_name: value }]`. The VM has already
 * split the call by the callable's declared params (using the captured
 * `Object::HostClosure`), dropping omitted optionals — so each bridge applies
 * its own calling convention (TS `$opts`, Python kwargs) without needing the
 * callee type on the wire.
 */
export const call_host_value = defineFunction("baml.host.call_host_value", "sync", ["handle", "args"], undefined, { typeParams: ["T", "E"] }) as <T, E>(handle: HostValue, args: unknown[]) => T;

/**
 * Internal: invoked only by compiler-synthesized host-callable wrapper
 * closures. Not directly callable by user code.
 * 
 * `T` is the expected return type and `E` the declared error contract,
 * both delivered to the native handler at runtime via the type-arg channel
 * (`type_arg_0` / `type_arg_1`). The completion site validates the host's
 * returned value against `T` and the thrown value against `E`: a return
 * that doesn't inhabit `T` and a throw that isn't a subtype of `E` both
 * become `baml.panics.HostContractViolation` (uncatchable). An on-contract
 * throw rides the VM's normal exception unwinder. A host value left
 * untyped at the boundary erases `E` to `unknown`, which accepts any
 * thrown value — including an opaque `baml.errors.HostCallable`.
 * 
 * `args` is a two-element pack the VM builds in `host_closure_call_sysop`:
 * `[positional_required_args, { optional_name: value }]`. The VM has already
 * split the call by the callable's declared params (using the captured
 * `Object::HostClosure`), dropping omitted optionals — so each bridge applies
 * its own calling convention (TS `$opts`, Python kwargs) without needing the
 * callee type on the wire.
 */
export const call_host_value_async = defineFunction("baml.host.call_host_value", "async", ["handle", "args"], undefined, { typeParams: ["T", "E"] }) as <T, E>(handle: HostValue, args: unknown[]) => Promise<T>;

/**
 * Opaque builtin class. Construction is reserved to the bridge
 * boundary; users cannot construct or destructure it.
 */
export class HostValue {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}
