# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.5

# Cache settings: Set to true to enable caching
cache: false

# File strategy s3/firebase
# fileStrategy: "s3"

# Custom interface configuration
interface:
  customWelcome: "Welcome to LibreChat! Enjoy your experience."
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true

# Example Actions Object Structure
actions:
  allowedDomains:
    - "swapi.dev"
    - "librechat.ai"
    - "google.com"


mcpServers:
  figma:
    command: npx
    args:
      - -y
      - "figma-developer-mcp"
      - "--figma-api-key"
      - "${MCP_FIGMA_API_KEY}"
      - "--stdio"
  
  atlassian:
    command: npx
    args:
      - -y
      - "mcp-remote"
      - "https://mcp.atlassian.com/v1/sse"
      - "--jira-url=${MCP_ATLASSIAN_JIRA_URL}"
      - "--jira-username=${MCP_ATLASSIAN_JIRA_USERNAME}"
      - "--jira-token=${MCP_ATLASSIAN_JIRA_TOKEN}"

# Definition of custom endpoints
endpoints:
  assistants:
    disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
    pollIntervalMs: 3000  # Polling interval for checking assistant updates
    timeoutMs: 180000  # Timeout for assistant operations
    # Should only be one or the other, either `supportedIds` or `excludedIds`
    supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
    # excludedIds: ["asst_excludedAssistantId"]
    # Only show assistants that the user created or that were created externally (e.g. in Assistants playground).
    # privateAssistants: false # Does not work with `supportedIds` or `excludedIds`
    # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
    retrievalModels: ["gpt-4-turbo-preview"]
    # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  agents:
    # (optional) Default recursion depth for agents, defaults to 25
    recursionLimit: 50
    # (optional) Max recursion depth for agents, defaults to 25
    maxRecursionLimit: 100
    # (optional) Disable the builder interface for agents
    disableBuilder: false
    # (optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["execute_code", "file_search", "actions", "tools"]
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "gpt-4o"
    plugins: true
    assistants: false
    groups:
    # Group-level configuration
    - group: "${AZURE_OPENAI_INSTANCE}"
      apiKey: "${AZURE_OPENAI_API_KEY}" 
      instanceName: "${AZURE_OPENAI_INSTANCE}"
      version: "2025-01-01-preview"
      # Model-level configuration
      models:
        gpt-4o:
          deploymentName: gpt-4o
  
  