name: _TS Build and Deploy

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag'
        required: false
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set dynamic image tag
      id: set-tag
      shell: pwsh
      run: |
        $tag = "${{ github.event.inputs.imageTag }}"
        if ($tag -eq "latest" -or $tag -eq "") {
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $tag = "v-$shortSha"
        }
        echo "IMAGE_TAG=$tag" >> $env:GITHUB_OUTPUT
      
    - name: Run build and deploy script
      shell: pwsh
      run: |
        $secretsHashtable = @{
          "MONGO_URI" = "${{ secrets.MONGO_URI }}"
          "CREDS_KEY" = "${{ secrets.CREDS_KEY }}"
          "CREDS_IV" = "${{ secrets.CREDS_IV }}"
          "JWT_SECRET" = "${{ secrets.JWT_SECRET }}"
          "JWT_REFRESH_SECRET" = "${{ secrets.JWT_REFRESH_SECRET }}"
          "SESSION_SECRET" = "${{ secrets.SESSION_SECRET }}"
          "AZURE_OPENAI_API_KEY" = "${{ secrets.AZURE_OPENAI_API_KEY }}"
          "EMAIL_PASSWORD" = "${{ secrets.EMAIL_PASSWORD }}"
          "REGISTRY_USERNAME" = "${{ secrets.REGISTRY_USERNAME }}"
          "REGISTRY_PASSWORD" = "${{ secrets.REGISTRY_PASSWORD }}"
        }

        $envVarsHashtable = @{
          "EMAIL_FROM" = "${{ vars.EMAIL_FROM }}"
          "EMAIL_FROM_NAME" = "${{ vars.EMAIL_FROM_NAME }}"
          "EMAIL_USERNAME" = "${{ vars.EMAIL_USERNAME }}"
        }

        ./custom/scripts/build-and-deploy.ps1 `
          -ImageName "ts-librechat" `
          -ImageTag "${{ steps.set-tag.outputs.IMAGE_TAG }}" `
          -Registry "registry.totalsoft.local" `
          -Namespace "librechat" `
          -HelmReleaseName "librechat" `
          -RegistryUsername "${{ secrets.REGISTRY_USERNAME }}" `
          -RegistryPassword "${{ secrets.REGISTRY_PASSWORD }}" `
          -Secrets $secretsHashtable `
          -EnvVars $envVarsHashtable
