name: _TS Clean Up Docker Registry

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run (no actual deletion)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      targetRepositories:
        description: 'Comma-separated list of target repositories to clean up'
        required: false
        type: string
        default: 'librechat-custom'

jobs:
  cleanup:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install regctl
      shell: bash
      env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        # Download regctl (Docker registry client)
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o regctl
        chmod +x regctl
        echo "$SUDO_PASSWORD" | sudo -S mv regctl /usr/local/bin/
        
    - name: Identify and delete orphaned images
      shell: bash
      env:
        REGISTRY_URL: registry.totalsoft.local
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        DRY_RUN: ${{ github.event.inputs.dryRun || 'true' }}
        TARGET_REPOSITORIES: ${{ github.event.inputs.targetRepositories || secrets.TARGET_REPOSITORIES || 'librechat-custom' }}
      run: |
        echo "Looking for orphaned images in $REGISTRY_URL"
        
        # Login to registry
        echo "$REGISTRY_PASSWORD" | regctl registry login $REGISTRY_URL --user $REGISTRY_USERNAME --pass-stdin
        
        # Determine which repositories to process
        if [ -n "$TARGET_REPOSITORIES" ]; then
          # Use the specified repositories (comma-separated list)
          IFS=',' read -ra REPOS <<< "$TARGET_REPOSITORIES"
          echo "Processing specified repositories: ${REPOS[*]}"
        else
          # If somehow we got here with empty TARGET_REPOSITORIES, use librechat-custom as default
          REPOS=("librechat-custom")
          echo "Using default repository: librechat-custom"
        fi
        
        for REPO in "${REPOS[@]}"; do
          # Trim whitespace
          REPO=$(echo "$REPO" | xargs)
          echo "Processing repository: $REPO"
          
          # Get all tags for this repository
          TAGS=$(regctl tag ls $REGISTRY_URL/$REPO)
          
          # Create a list to exclude manifests referenced by multi-arch images
          EXCLUDE_LIST=()
          
          # First, identify all manifests referenced by multi-arch images to exclude them from deletion
          for TAG in $TAGS; do
            echo "Checking tag $TAG for multi-arch manifests"
            # Get the manifest for the tagged image
            MANIFEST_INFO=$(regctl manifest get $REGISTRY_URL/$REPO:$TAG || echo "")
            
            # Check if it's a multi-arch image (manifest list)
            if echo "$MANIFEST_INFO" | grep -q "MediaType:.*manifest.list"; then
              echo "Found multi-arch image: $REGISTRY_URL/$REPO:$TAG"
              # Get the list of referenced manifests (digests)
              REFERENCED_MANIFESTS=$(regctl manifest get $REGISTRY_URL/$REPO:$TAG | grep "Digest:" | grep -v "Name:" | awk '{print $2}')
              
              # Add each referenced manifest to the exclusion list
              for DIGEST in $REFERENCED_MANIFESTS; do
                echo "Adding referenced manifest $DIGEST to exclusion list"
                EXCLUDE_LIST+=("$DIGEST")
              done
            fi
          done
          
          echo "Excluding ${#EXCLUDE_LIST[@]} manifests referenced by multi-arch images"
          
          # Keep only the latest 5 tags for each repository
          if [ $(echo "$TAGS" | wc -l) -gt 5 ]; then
            # Sort tags by creation date (assuming version tags with dates or incremental numbers)
            # Keep the 5 most recent tags
            TAGS_TO_DELETE=$(echo "$TAGS" | sort -V | head -n -5)
            
            echo "Tags to keep for $REPO: $(echo "$TAGS" | sort -V | tail -n 5)"
            echo "Tags to delete for $REPO: $TAGS_TO_DELETE"
            
            # Delete old tags
            if [ "$DRY_RUN" = "false" ]; then
              for TAG in $TAGS_TO_DELETE; do
                echo "Deleting $REGISTRY_URL/$REPO:$TAG"
                TAG_DIGEST=$(regctl digest $REGISTRY_URL/$REPO:$TAG)
                
                # Check if this digest is in our exclusion list
                if [[ " ${EXCLUDE_LIST[@]} " =~ " $TAG_DIGEST " ]]; then
                  echo "Skipping deletion of $TAG (digest $TAG_DIGEST) as it's referenced by a multi-arch image"
                else
                  regctl tag delete $REGISTRY_URL/$REPO:$TAG
                fi
              done
              
              # Now find and delete any unreferenced manifests
              MANIFESTS=$(regctl manifest ls $REGISTRY_URL/$REPO)
              for MANIFEST in $MANIFESTS; do
                # Skip manifests in the exclusion list
                if [[ " ${EXCLUDE_LIST[@]} " =~ " $MANIFEST " ]]; then
                  echo "Skipping deletion of manifest $MANIFEST as it's referenced by a multi-arch image"
                  continue
                fi
                
                # Check if manifest has tags
                MANIFEST_TAGS=$(regctl tag ls --referrer "$MANIFEST" $REGISTRY_URL/$REPO)
                if [ -z "$MANIFEST_TAGS" ]; then
                  echo "Deleting untagged manifest $MANIFEST"
                  regctl manifest delete $REGISTRY_URL/$REPO@$MANIFEST
                fi
              done
            else
              echo "[DRY RUN] Would delete these tags: $TAGS_TO_DELETE"
              echo "[DRY RUN] Would also delete any unreferenced manifests not part of multi-arch images"
            fi
          else
            echo "Repository $REPO has 5 or fewer tags, skipping cleanup"
          fi
        done
        
    - name: Run garbage collection
      shell: bash
      env:
        REGISTRY_POD: ${{ secrets.REGISTRY_POD_NAME }}
        REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
        DRY_RUN: ${{ github.event.inputs.dryRun || 'true' }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        if [ "$DRY_RUN" = "false" ]; then
          echo "Running garbage collection to reclaim space"
          echo "$SUDO_PASSWORD" | sudo -S kubectl -n $REGISTRY_NAMESPACE exec -it $REGISTRY_POD -- bin/registry garbage-collect /etc/docker/registry/config.yml --delete-untagged=true
        else
          echo "[DRY RUN] Would run garbage collection"
        fi 