name: _TS Build and Deploy

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag'
        required: false
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set dynamic image tag
      id: set-tag
      shell: pwsh
      run: |
        $tag = "${{ github.event.inputs.imageTag }}"
        if ($tag -eq "latest" -or $tag -eq "") {
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $tag = "v-$shortSha"
        }
        echo "IMAGE_TAG=$tag" >> $env:GITHUB_OUTPUT
      
    - name: Run build and deploy script
      shell: pwsh
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        ./custom/scripts/build-and-deploy.ps1 `
          -ImageName "ts-librechat" `
          -ImageTag "${{ steps.set-tag.outputs.IMAGE_TAG }}" `
          -Registry "registry.totalsoft.local" `
          -Namespace "librechat" `
          -HelmReleaseName "librechat" `
          -RegistryUsername "$env:REGISTRY_USERNAME" `
          -RegistryPassword "$env:REGISTRY_PASSWORD" 