name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: rgHeblo
  WEBAPP_NAME: trivichat

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: node
            file: Dockerfile
            image_name: librechat
          - target: api-build
            file: Dockerfile.multi
            image_name: librechat-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare environment
        run: cp .env.example .env

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
          platforms: linux/amd64
          target: ${{ matrix.target }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/librechat:${{ github.sha }}
