name: Build and Deploy LibreChat

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag'
        required: false
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set dynamic image tag
      id: set-tag
      shell: pwsh
      run: |
        $tag = "${{ github.event.inputs.imageTag }}"
        if ($tag -eq "latest" -or $tag -eq "") {
          $tag = "v-${{ github.sha.substring(0, 7) }}"
        }
        echo "::set-output name=IMAGE_TAG::$tag"
      
    - name: Run build and deploy script
      shell: pwsh
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        ./custom/build-and-deploy.ps1 `
          -ImageName "librechat-custom" `
          -ImageTag "${{ steps.set-tag.outputs.IMAGE_TAG }}" `
          -Registry "registry.totalsoft.local" `
          -Namespace "librechat" `
          -HelmReleaseName "librechat" `
          -MongoUri "$env:MONGO_URI" `
          -RegistryUsername "$env:REGISTRY_USERNAME" `
          -RegistryPassword "$env:REGISTRY_PASSWORD" 