name: Docker Build and Push to GHCR

on:
  # Allow manual triggering with custom parameters
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'jm-production'
        type: string
      tag:
        description: 'Docker image tag (default: latest)'
        required: false
        default: 'latest'
        type: string
      dockerfile:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile.multi'
        type: string
  
  # Automatic build on push to jm-production
  push:
    branches:
      - jm-production

jobs:
  deploy-gh-runner-aci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          # Use the specified branch from manual input or jm-production for auto runs
          ref: ${{ github.event.inputs.branch || 'jm-production' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Use specified Dockerfile or default
          file: ${{ github.event.inputs.dockerfile || 'Dockerfile.multi' }}
          push: true
          # Use specified tag or default to latest
          tags: ghcr.io/jmaddington/librechat:${{ github.event.inputs.tag || 'latest' }}
          # Add build cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log out from GitHub Docker Registry
        run: docker logout ghcr.io