name: Sync with Upstream and Run CI

on:
  # Run on a schedule (every hour)
  schedule:
    - cron: '0 7 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main-upstream
          fetch-depth: 0
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/danny-avila/LibreChat.git
          git fetch upstream
      
      - name: Check for new changes
        id: check_changes
        run: |
          # Get the latest commit hash from upstream/main
          UPSTREAM_HASH=$(git rev-parse upstream/main)
          # Get the latest commit hash that was merged from upstream into our main branch
          BASE_HASH=$(git merge-base main upstream/main)
          
          if [ "$UPSTREAM_HASH" = "$BASE_HASH" ]; then
            echo "No new changes in upstream repository"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "New changes detected in upstream repository"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Sync with upstream
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Save our workflow files to a temp directory
          mkdir -p /tmp/workflows
          cp .github/workflows/jm*.yml /tmp/workflows/
          
          # Reset our main branch to match upstream main
          git fetch upstream
          git reset --hard upstream/main
          
          # Ensure .github/workflows directory exists
          mkdir -p .github/workflows
          
          # Copy our workflow files back
          cp /tmp/workflows/jm*.yml .github/workflows/
          
          # Commit and push the changes
          git add .github/workflows/jm*.yml
          git commit -m "Keep specified workflow files after resetting to upstream main"
          
          # Push changes to origin (with force since we did a hard reset)
          git push --force origin main-upstream
        
      # The workflows will be automatically triggered because we pushed to main
      # We don't need to explicitly trigger them