name: Stripe Build Librechat Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatic trigger on new commits on any branch
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo sanitized GitHub ref and commit SHA
        run: |
          echo "GitHub commit SHA: ${{ github.sha }}"
          echo "GitHub ref name: ${{ github.ref_name }}"
          SANITIZED_REF_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "SANITIZED_REF_NAME=${SANITIZED_REF_NAME}" >> $GITHUB_ENV
          echo "SANITIZED_REF_NAME=${SANITIZED_REF_NAME}"

      - name: Fetch tags and set the latest tag
        run: |
          git fetch --tags
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Prepare the environment
      - name: Prepare environment
        run: |
          cp .env.example .env



      # Build and push Docker images for each target
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            stripe/librechat:${{ github.sha }}
            stripe/librechat:${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
            ${{ github.ref_name == 'develop' && 'stripe/librechat:latest' || '' }}
          platforms: linux/arm64
          target: node
